// src/data/t3-primitives/chap6.ts
import { Chapitre } from '../../types/course';

export const chapitre5: Chapitre = {
  id: 't3-chap6',
  titre: 'Exercices Type BAC',
  duree: 45,
  niveau: 'BAC',
  xpGain: 100,
  gratuit: false,
  objectifs: [
    'Résoudre les 5 exercices d\'Échauffement de niveau BASE sur les polynômes, exponentielles et fractions',
    'Maîtriser les 5 exercices d\'Entraînement de niveau MOYEN (composées, aires croisées, lissage moyen)',
    'Dominer les 10 grands Sujets de synthèse du BAC (IPP, modélisation économique, cinématique du gbaka)',
    'S\'exercer sans filet sur les 10 défis en autonomie complète du Sac de Frappe',
  ],
  sections: [
    {
      id: 's1',
      titre: 'Introduction — Monter sur le Ring de l\'Examen',
      blocs: [
        {
          type: 'text',
          id: 'b1-accroche',
          contenu: 'Champion(ne), te voilà dans l\'arène ! On a forgé les outils au maquis, maintenant on monte sur le ring pour rafler tous les points d\'analyse au BAC.',
        },
        {
          type: 'text',
          id: 'b1',
          contenu: "L'épreuve de mathématiques en Terminale D est conçue pour évaluer tes compétences sur une durée de quatre (04) heures, avec un coefficient de 4. L'exercice 5 (l'étude de fonction) et l'exercice 6 (la situation complexe) sont ceux qui rapportent le plus de points, et ils utilisent tous les deux les intégrales. C'est là que tu vas faire la différence.",
        },
        {
          type: 'dialogue',
          id: 'b2-strategie-bac',
          pf: "Vieux père, je suis chaud, je connais mes formules. Mais quand je vois un sujet de BAC entier, avec les questions a), b), c), je perds mes moyens. Je ne sais plus par quoi commencer !",
          gf: "C'est l'erreur du débutant, petit. Le BAC, ce n'est pas un concours de vitesse, c'est un jeu d'échecs. Règle numéro 1 : Ne cherche jamais à deviner une primitive au hasard. Utilise le processus EDUCTOME. Règle numéro 2 : Lis TOUT l'exercice avant de commencer. Très souvent, la question « b » te donne la réponse de la question « a » déguisée !",
        },
        {
          type: 'dialogue',
          id: 'b3-strategie-bac-suite',
          pf: "Vraiment ? Donc si je bloque sur le calcul d'une dérivée ou d'une primitive, je peux regarder la suite ?",
          gf: "Exactement ! Si la question 2 dit : « En déduire que f est croissante », ça veut dire que ta dérivée de la question 1 DOIT être positive. C'est une boussole. Et pour les calculs d'aires, n'oublie jamais de vérifier le signe de ta fonction avant d'intégrer, sinon tu vas tomber dans le piège de l'aire négative !",
        },
        {
          type: 'text',
          id: 'b4-transition',
          contenu: 'Enfile tes gants, Champion(ne). On active tout de suite les réflexes de calcul avec les 5 exercices d\'échauffement de niveau BASE.',
        },
      ],
    },
    {
      id: 's2',
      titre: '5.1 Exercices Niveau BASE (Échauffement Musculaire)',
      blocs: [
        {
          type: 'text',
          id: 'b5-accroche',
          contenu: 'Prends 5 minutes maximum par énoncé. Objectif : valider la fluidité de tes formules directes.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-1',
          niveau: 'BASE',
          enonce: 'Exercice 5.1.1 — Primitives de fonctions polynômes :\nCalculer une primitive de la fonction $f$ définie sur $\\mathbb{R}$ par $f(x) = 4x^3 - 3x^2 + 2x - 7$.',
          etapes: [
            'Étape 1 : Identifie la nature de la fonction : c\'est un polynôme simple. On intègre monôme par monôme.',
            'Étape 2 : Applique la formule $x^n \\to \\frac{1}{n+1}x^{n+1}$ terme par terme.',
            'Étape 3 : Bloc 1 : $4 \\times \\frac{x^4}{4} = x^4$. Bloc 2 : $-3 \\times \\frac{x^3}{3} = -x^3$. Bloc 3 : $2 \\times \\frac{x^2}{2} = x^2$. Bloc 4 : $-7 \\to -7x$.',
            'Étape 4 : Assemble le tout en ajoutant la constante : $F(x) = x^4 - x^3 + x^2 - 7x + C$.',
          ],
          reponse: 'x^4 - x^3 + x^2 - 7x + C',
          conseil: 'Vérification par la Règle d\'Or : si tu dérives $F(x)$, tu retombes bien sur $4x^3 - 3x^2 + 2x - 7$.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-2',
          niveau: 'BASE',
          enonce: 'Exercice 5.1.2 — Primitive avec exponentielle :\nCalculer une primitive de la fonction $g$ définie sur $\\mathbb{R}$ par $g(x) = 3e^{2x} - 5$.',
          etapes: [
            'Étape 1 : Identifie la forme : structure linéaire avec exponentielle composée de type $e^{ax}$.',
            'Étape 2 : Le terme $3e^{2x}$ conserve son coefficient 3, et la primitive de $e^{2x}$ donne $\\frac{1}{2}e^{2x}$.',
            'Étape 3 : Le produit donne $\\frac{3}{2}e^{2x}$. Le terme constant $-5$ gagne la variable $x$ pour donner $-5x$.',
            'Étape 4 : Ajoute la constante pour clore le calcul : $G(x) = \\frac{3}{2}e^{2x} - 5x + C$.',
          ],
          reponse: '\\frac{3}{2}e^{2x} - 5x + C',
          conseil: 'Vérifie au brouillon : la dérivée de $\\frac{3}{2}e^{2x}$ est $\\frac{3}{2} \\times 2e^{2x} = 3e^{2x}$. C\'est parfaitement validé.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-3',
          niveau: 'BASE',
          enonce: 'Exercice 5.1.3 — Primitive avec fraction inverse :\nCalculer une primitive de la fonction $h$ définie sur $]0 ; +\\infty[$ par $h(x) = \\frac{2}{x} + x^2$.',
          etapes: [
            'Étape 1 : Sépare les termes : on a une fonction inverse combinée avec une puissance standard.',
            'Étape 2 : Réécris le premier bloc sous la forme $2 \\times \\frac{1}{x}$. Sa primitive usuelle donne $2\\ln|x|$.',
            'Étape 3 : Comme le domaine est strictement positif $]0; +\\infty[$, les barres de valeur absolue sautent : $2\\ln(x)$.',
            'Étape 4 : Le monôme $x^2$ donne $\\frac{x^3}{3}$. Rassemble le tout : $H(x) = 2\\ln(x) + \\frac{x^3}{3} + C$.',
          ],
          reponse: '2\\ln(x) + \\frac{x^3}{3} + C',
          conseil: 'La Règle d\'Or confirme immédiatement : $H\'(x) = 2 \\times \\frac{1}{x} + \\frac{3x^2}{3} = \\frac{2}{x} + x^2$.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-4',
          niveau: 'BASE',
          enonce: 'Exercice 5.1.4 — Intégrale définie simple :\nCalculer la valeur exacte de l\'intégrale numérique suivante : $I = \\int_1^3 (2x - 1) dx$.',
          etapes: [
            'Étape 1 : Trouve d\'abord la primitive de l\'expression : $F(x) = x^2 - x$.',
            'Étape 2 : Écris ton crochet d\'attente sur ta copie : $I = [x^2 - x]_1^3$.',
            'Étape 3 : Évalue la borne supérieure : $F(3) = 3^2 - 3 = 9 - 3 = 6$.',
            'Étape 4 : Évalue la borne inférieure : $F(1) = 1^2 - 1 = 1 - 1 = 0$.',
            'Étape 5 : Calcule la soustraction finale : $I = F(3) - F(1) = 6 - 0 = 6$.',
          ],
          reponse: '6',
          conseil: 'Pas besoin de trimballer la constante C dans une intégrale définie, elle s\'annule systématiquement dans la soustraction.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-5',
          niveau: 'BASE',
          enonce: 'Exercice 5.1.5 — Calcul d\'aire standard :\nL\'unité graphique est fixée à 1 cm. Calculer l\'aire de la surface délimitée par la courbe de $f(x) = x^2$, l\'axe des abscisses, et les droites verticales d\'équations $x = 0$ et $x = 2$.',
          etapes: [
            'Étape 1 : Vérifie le signe : sur $[0; 2]$, $x^2 \\ge 0$, la courbe survole l\'axe horizontal.',
            'Étape 2 : Pose l\'intégrale de surface associée : $\\text{Aire} = \\int_0^2 x^2 dx \\times \\text{u.a.}$',
            'Étape 3 : Évalue le crochet de la primitive : $[\\frac{x^3}{3}]_0^2 = \\frac{2^3}{3} - \\frac{0^3}{3} = \\frac{8}{3} \\text{ u.a.}$.',
            'Étape 4 : Convertis avec l\'unité graphique : $1 \\text{ u.a.} = 1\\text{ cm} \\times 1\\text{ cm} = 1\\text{ cm}^2$.',
            'Étape 5 : Conclus proprement : la surface mesure $\\frac{8}{3}\\text{ cm}^2$ (environ 2,67 cm²).',
          ],
          reponse: '\\frac{8}{3}',
          conseil: 'N\'oublie pas d\'écrire l\'unité physique cm² à la fin pour rendre ton résultat conforme.',
        },
        {
          type: 'text',
          id: 'b6-transition',
          contenu: 'L\'échauffement est validé. Montons tout de suite en régime pour acquérir la musculature technique de niveau MOYEN.',
        },
      ],
    },
    {
      id: 's3',
      titre: '5.2 Exercices Niveau MOYEN (Technique d\'Ajustement)',
      blocs: [
        {
          type: 'text',
          id: 'b7-accroche',
          contenu: 'Ici, on apprend à forcer l\'apparition des coefficients manquants pour plier les fonctions composées et les pièges de signes. Sors ton brouillon.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-1',
          niveau: 'MOYEN',
          enonce: 'Exercice 5.2.1 — Primitive de fonction composée :\nCalculer l\'ensemble des primitives de la fonction $f(x) = (2x + 1)^3$ sur $\\mathbb{R}$.',
          etapes: [
            'Étape 1 : Identifie la structure : c\'est une forme composée de type $u\'u^n$ avec $n=3$.',
            'Étape 2 : Pose ta brique interne : $u(x) = 2x + 1 \\implies u\'(x) = 2$. Mais le coefficient 2 est absent de l\'énoncé !',
            'Étape 3 : Force l\'apparition du 2 en compensant avec son inverse $\\frac{1}{2}$ devant : $f(x) = \\frac{1}{2} \\times 2(2x + 1)^3$.',
            'Étape 4 : Applique la formule théorique $\\frac{u^{n+1}}{n+1}$ : $F(x) = \\frac{1}{2} \\times \\frac{(2x+1)^4}{4} + C$.',
            'Étape 5 : Réduis les fractions : $F(x) = \\frac{(2x+1)^4}{8} + C$. C\'est validé !',
          ],
          reponse: '\\frac{(2x + 1)^4}{8} + C',
          conseil: 'Redérive dans ta tête pour valider : $\\frac{1}{8} \\times 4 \\times 2(2x+1)^3 = \\frac{8}{8}(2x+1)^3 = (2x+1)^3$.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-2',
          niveau: 'MOYEN',
          enonce: 'Exercice 5.2.2 — Primitive de la structure u\'/u :\nCalculer la famille de primitives de la fonction $g(x) = \\frac{x}{x^2 + 1}$ sur $\\mathbb{R}$.',
          etapes: [
            'Étape 1 : Fraction complexe variable, on pense immédiatement au modèle $\\frac{u\'}{u}$ qui produit du $\\ln|u|$.',
            'Étape 2 : Extrais le dénominateur : $u(x) = x^2 + 1 \\implies u\'(x) = 2x$. Le numérateur possède x, il manque le coefficient 2.',
            'Étape 3 : Ajuste l\'expression : $g(x) = \\frac{1}{2} \\times \\frac{2x}{x^2 + 1}$. On détient la forme exacte $\\frac{1}{2} \\times \\frac{u\'}{u}$.',
            'Étape 4 : Intègre : $G(x) = \\frac{1}{2}\\ln|x^2 + 1| + C$.',
            'Étape 5 : Rigueur absolue : comme $x^2 + 1 > 0$ sur $\\mathbb{R}$, tu peux remplacer les valeurs absolues par des parenthèses : $G(x) = \\frac{1}{2}\\ln(x^2 + 1) + C$.',
          ],
          reponse: '\\frac{1}{2}\\ln(x^2 + 1) + C',
          conseil: 'Justifie le retrait des barres de valeur absolue en précisant que le contenu du trinôme est strictement positif.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-3',
          niveau: 'MOYEN',
          enonce: 'Exercice 5.2.3 — Surface emprisonnée entre deux courbes :\nL\'unité graphique est de 1 cm. Calculer l\'aire du domaine délimité par la parabole d\'équation $y = x^2$ et la ligne droite d\'équation $y = 2x$.',
          etapes: [
            'Étape 1 (Intersections) : Égale les deux fonctions : $x^2 = 2x \\implies x^2 - 2x = 0 \\implies x(x-2) = 0$. Les bornes de calcul sont 0 et 2.',
            'Étape 2 (Position) : Sur $[0; 2]$, évalue la différence : pour $x=1$, $2(1) - 1^2 = 1 > 0$. La droite survole donc la parabole.',
            'Étape 3 (Intégrer) : Pose le calcul (Haut - Bas) : $\\text{Aire} = \\int_0^2 (2x - x^2) dx$.',
            'Étape 4 (Calcul) : Extrais la primitive : $[x^2 - \\frac{x^3}{3}]_0^2 = (2^2 - \\frac{2^3}{3}) - 0 = 4 - \\frac{8}{3} = \\frac{12-8}{3} = \\frac{4}{3} \\text{ u.a.}$.',
            'Étape 5 (Unité) : Unité = 1 cm $\\implies 1 \\text{ u.a.} = 1\\text{ cm}^2$. L\'aire mesure donc $\\frac{4}{3}\\text{ cm}^2$.',
          ],
          reponse: '\\frac{4}{3}',
          conseil: 'L\'étude de position relative évite de se tromper de sens lors du montage de la soustraction de l\'intégrale.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-4',
          niveau: 'MOYEN',
          enonce: 'Exercice 5.2.4 — Intégration avec bascule et traversée d\'axe :\nL\'unité graphique est de 1 cm. Calculer l\'aire de la surface délimitée par $f(x) = x^2 - 4$, l\'axe des abscisses, et les frontières verticales $x = 0$ et $x = 3$.',
          etapes: [
            'Étape 1 (Signe) : Résous $x^2 - 4 = 0 \\implies (x-2)(x+2) = 0$. Sur $[0; 3]$, la courbe traverse l\'axe au point critique $x = 2$.',
            'Étape 2 (Intervalles) : Sur $[0; 2]$, $f(x) \\le 0$ (en dessous de l\'axe). Sur $[2; 3]$, $f(x) \\ge 0$ (au-dessus de l\'axe).',
            'Étape 3 (Chasles) : Découpe l\'intégrale en appliquant un signe moins correcteur sur le premier bloc : $\\text{Aire} = -\\int_0^2 (x^2 - 4)dx + \\int_2^3 (x^2 - 4)dx$.',
            'Étape 4 (Bloc 1) : $-[\\frac{x^3}{3} - 4x]_0^2 = -(\\frac{8}{3} - 8) = -(-\\frac{16}{3}) = \\frac{16}{3}$.',
            'Étape 5 (Bloc 2) : $[\\frac{x^3}{3} - 4x]_2^3 = (\\frac{27}{3}-12) - (\\frac{8}{3}-8) = -3 - (-\\frac{16}{3}) = \\frac{7}{3}$.',
            'Étape 6 (Total) : Somme les deux superficies : $\\frac{16}{3} + \\frac{7}{3} = \\frac{23}{3}\\text{ cm}^2$.',
          ],
          reponse: '\\frac{23}{3}',
          conseil: 'Si tu avais calculé l\'intégrale brute directe de 0 à 3 sans découper, les surfaces se seraient soustraites, faussant l\'aire réelle.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-5',
          niveau: 'MOYEN',
          enonce: 'Exercice 5.2.5 — Valeur moyenne et lissage thermique :\nLa température en °C enregistrée à Abidjan lors de la saison sèche est modélisée par $T(t) = 25 + 5\\sin(t)$ entre $t=6$ et $t=18$ heures. Calcule la température moyenne lissée sur cette période journalière.',
          etapes: [
            'Étape 1 : Applique la formule officielle de la valeur moyenne : $\\mu = \\frac{1}{b-a}\\int_a^b T(t)dt \\implies \\mu = \\frac{1}{18-6} \\int_6^{18} (25 + 5\\sin(t)) dt$.',
            'Étape 2 : Le coefficient lisseur extérieur vaut $\\frac{1}{12}$.',
            'Étape 3 : Extrais la primitive associée : $F(t) = 25t - 5\\cos(t)$.Pose le crochet : $\\mu = \\frac{1}{12} [25t - 5\\cos(t)]_6^{18}$.',
            'Étape 4 : Déploie l\'évaluation numérique des bornes : $\\frac{1}{12} [ (25(18) - 5\\cos(18)) - (25(6) - 5\\cos(6)) ]$.',
            'Étape 5 : Réduis les valeurs constantes : $\\frac{1}{12} [ 450 - 150 - 5\\cos(18) + 5\\cos(6) ] = \\frac{1}{12} [ 300 - 5\\cos(18) + 5\\cos(6) ]$.',
            'Étape 6 : Formule épurée finale : $\\mu = 25 + \\frac{5}{12}(\\cos(6) - \\cos(18)) \\text{ °C}$.',
          ],
          reponse: '25 + \\frac{5}{12}(\\cos(6) - \\cos(18))',
          conseil: 'La valeur moyenne représente la température constante idéale qu\'il ferait si la chaleur était répartie uniformément sur toute la durée d\'étude.',
        },
        {
          type: 'text',
          id: 'b8-transition',
          contenu: 'La technique est robuste, l\'échauffement est terminé. Range tes notes, concentre-toi au maximum : on monte sur le ring des 10 grands Sujets du BAC.',
        },
      ],
    },
    {
      id: 's4',
      titre: '5.3 Sujets Niveau BAC — Le Grand Marathon de Synthèse',
      blocs: [
        {
          type: 'text',
          id: 'b9-accroche',
          contenu: 'Champion(ne), voici les 10 grands thèmes d\'analyse qui tombent le plus fréquemment au BAC ivoirien. Prends tes armes, on les détruit un par un.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-1',
          niveau: 'BAC',
          enonce: 'SUJET 1 : Étude de fonction et calcul d\'aire classique\n[Temps recommandé : 25 min]\n\nSoit la fonction f définie par $f(x) = x^3 - 3x + 2$. On note (C) sa courbe représentative dans un repère orthogonal (Unité graphique : 2 cm).\n\na) Calculer $f\'(x)$ et dresser le tableau de variations complet de f sur $[-2; 2]$.\nb) Déterminer l\'équation réduite de la droite tangente (T) au point d\'abscisse $x_0 = 0$.\nc) Montrer que pour tout réel x de cet intervalle, $f(x) \\ge 0$.\nd) Calculer l\'aire exacte du domaine délimité par (C), l\'axe des abscisses, et les droites $x=0$ et $x=2$.',
          etapes: [
            'Correction a) : Variations. On dérive : $f\'(x) = 3x^2 - 3 = 3(x^2 - 1) = 3(x - 1)(x + 1)$. Les deux racines sont $-1$ et $1$. Le coefficient $a=3>0$ impose un signe positif à l\'extérieur. La courbe croît sur $[-2; -1]$, décroît sur $[-1; 1]$, puis croît sur $[1; 2]$. Images clés : $f(-2)=0, f(-1)=4, f(1)=0, f(2)=4$.',
            'Correction b) : Tangente en 0. On évalue : $f(0) = 2$ et $f\'(0) = -3$. L\'équation s\'assemble : $y = -3(x - 0) + 2 \\implies y = -3x + 2$.',
            'Correction c) : Positivité. En observant le tableau de variations complet, le point le plus bas (le minimum absolu) de f sur l\'intervalle est atteint en $x=1$ et sa valeur est de $f(1) = 0$. Par conséquent, la fonction est toujours supérieure ou égale à son minimum, d\'où $f(x) \\ge 0$.',
            'Correction d) : Aire géométrique. Puisque $f(x) \\ge 0$ sur $[0; 2]$, on intègre directement : $\\text{Aire} = \\int_0^2 (x^3 - 3x + 2) dx \\times \\text{u.a.}$. La primitive est $\\frac{x^4}{4} - \\frac{3x^2}{2} + 2x$. On applique le crochet : $[\\frac{x^4}{4} - \\frac{3x^2}{2} + 2x]_0^2 = (\\frac{16}{4} - \\frac{12}{2} + 4) - 0 = 4 - 6 + 4 = 2 \\text{ u.a.}$.\nConversion : unité = 2 cm $\\implies 1 \\text{ u.a.} = 2\\text{ cm} \\times 2\\text{ cm} = 4\\text{ cm}^2$. Aire finale = $2 \\times 4 = 8\\text{ cm}^2$.',
          ],
          reponse: '8\\text{ cm}^2',
          conseil: 'L\'étude de la valeur du minimum à la question (c) sert de sésame pour justifier l\'intégration directe sans découpage de signe à la question (d).',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-2',
          niveau: 'BAC',
          enonce: 'SUJET 2 : L\'Intégration Par Parties (IPP de référence)\n[Temps recommandé : 20 min]\n\nSoit la fonction f définie sur $[0; 1]$ par l\'expression $f(x) = xe^x$.\n\na) Déterminer la fonction dérivée $f\'(x)$ et justifier que f est strictement croissante.\nb) À l\'aide d'une intégration par parties, calculer la valeur numérique exacte de l\'intégrale définie : $I = \\int_0^1 xe^x dx$.',
          etapes: [
            'Correction a) : Dérivation. Structure de type produit $uv$ avec $u=x \\implies u\'=1$ et $v=e^x \\implies v\'=e^x$. On assemble : $f\'(x) = (1)e^x + x(e^x) = e^x(x + 1)$. Sur l\'intervalle $[0; 1]$, le terme $x+1 > 0$ et l\'exponentielle $e^x > 0$. La dérivée $f\'(x)$ est strictement positive, la fonction f est donc strictement croissante.',
            'Correction b) : Intégration par parties. Formule officielle : $\\int u v\' = [u v] - \\int u\' v$. On choisit d\'abaisser le degré de x en posant : \n  - $u(x) = x \\implies u\'(x) = 1$\n  - $v\'(x) = e^x \\implies v(x) = e^x$\nOn applique le protocole : $I = [xe^x]_0^1 - \\int_0^1 1 \\cdot e^x dx = (1\\cdot e^1 - 0) - [e^x]_0^1 = e - (e^1 - e^0) = e - e + 1 = 1$. Le résultat exact est 1.',
          ],
          reponse: '1',
          conseil: 'Choisis toujours d\'affecter la variable polynomiale (ici x) à la fonction u(x) lors de ton IPP pour faire disparaître son degré lors de la dérivation interne.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-3',
          niveau: 'BAC',
          enonce: 'SUJET 3 : Aire fermée entre une parabole et une droite oblique\n[Temps recommandé : 25 min]\n\nSoit la fonction f définie par $f(x) = x^2 - 2x$ et la droite (D) d\'équation linéaire $g(x) = x$. (L\'unité graphique du plan est fixée à 1 cm).\n\na) Déterminer les coordonnées précises des points d\'intersection de la courbe (C) et de la droite (D).\nb) Étudier la position relative de la courbe par rapport à (D).\nc) Calculer la surface exacte du domaine géométrique enfermé par les deux tracés.',
          etapes: [
            'Correction a) : Intersections. On résout $f(x) = g(x) \\implies x^2 - 2x = x \\implies x^2 - 3x = 0 \\implies x(x-3) = 0$. Les points de contact critiques sont $A(0; 0)$ et $B(3; 3)$. Bornes d\'intégration : 0 et 3.',
            'Correction b) : Position. On étudie le signe de la différence : $f(x) - g(x) = x^2 - 3x$. C\'est un trinôme du second degré possédant un coefficient $a=1>0$. Il est donc négatif à l\'intérieur de ses racines. Sur l\'intervalle $[0; 3]$, $f(x) - g(x) \\le 0$, ce qui prouve que la courbe se situe EN DESSOUS de la droite (D).',
            'Correction c) : Calcul de la surface. Puisque la droite (D) est dominante en haut, on intègre la différence positive : $\\text{Aire} = \\int_0^3 (g(x) - f(x)) dx = \\int_0^3 (-x^2 + 3x) dx$. La primitive associée est $-\\frac{x^3}{3} + \\frac{3x^2}{2}$. On applique le crochet : $[-\\frac{x^3}{3} + \\frac{3x^2}{2}]_0^3 = (-\\frac{27}{3} + \\frac{3(9)}{2}) - 0 = -9 + 13,5 = 4,5 \\text{ u.a.}$. L\'unité étant de 1 cm, la surface mesure exactement $4,5\\text{ cm}^2$ (ou $\\frac{9}{2}\\text{ cm}^2$).',
          ],
          reponse: '4,5',
          conseil: 'Pense à valider tes bornes d\'intégration au brouillon avant de te lancer dans l\'évaluation des crochets.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-4',
          niveau: 'BAC',
          enonce: 'SUJET 4 : Modélisation Économique d\'une Récolte de Cacao\n[Temps recommandé : 20 min]\n\nLe coût marginal de traitement du cacao (en milliers de FCFA) pour une quantité q de tonnes est modélisé par la fonction : $C_m(q) = 3q^2 - 4q + 5$. On sait que les coûts fixes de structure (production nulle, $q=0$) s\'élèvent à 100 milliers de FCFA.\n\na) Justifier proprement que la fonction du Coût Total C(q) correspond à une primitive du coût marginal.\nb) Déterminer l\'expression algébrique complète de la fonction du Coût Total C(q).\nc) Calculer le coût total exact pour une récolte de 10 tonnes.',
          etapes: [
            'Correction a) : Justification. En économie d\'entreprise, le coût marginal représente la variation instantanée du coût global pour une tonne supplémentaire traitée. C\'est la définition stricte de la dérivée : $C\'(q) = C_m(q)$. Par inversion mécanique, la fonction du Coût Total C(q) est donc une primitive de la fonction marginale.',
            'Correction b) : Expression. On intègre le polynôme : $C(q) = \\int (3q^2 - 4q + 5) dq = 3\\frac{q^3}{3} - 4\\frac{q^2}{2} + 5q + K = q^3 - 2q^2 + 5q + K$. Exploitons la condition initiale des coûts fixes : $C(0) = 100 \\implies 0^3 - 2(0)^2 + 5(0) + K = 100 \\implies K = 100$. La fonction recherchée est : $C(q) = q^3 - 2q^2 + 5q + 100$.',
            'Correction c) : Évaluation. Pour une production de 10 tonnes, on évalue $C(10) = 10^3 - 2(10)^2 + 5(10) + 100 = 1000 - 200 + 50 + 100 = 950$ milliers de FCFA. Le coût total de la récolte s\'élève donc à 950 000 FCFA.',
          ],
          reponse: '950000',
          conseil: 'Les coûts fixes correspondent toujours mathématiquement à la constante d\'intégration K déterminée à l\'origine (q=0).',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-5',
          niveau: 'BAC',
          enonce: 'SUJET 5 : Fonction rationnelle et primitive logarithmique\n[Temps recommandé : 20 min]\n\nSoit la fonction f définie sur $]0 ; +\\infty[$ par l\'expression $f(x) = \\frac{x^2 + 1}{x}$. (L\'unité graphique est fixée à 2 cm).\n\na) Vérifier l\'égalité algébrique suivante : $f(x) = x + \\frac{1}{x}$.\nb) En déduire l\'expression générale d\'une primitive F de la fonction f sur cet intervalle.\nc) Calculer l\'aire exacte du domaine situé sous la courbe délimité par les droites vertical d\'équations $x=1$ et $x=3$.',
          etapes: [
            'Correction a) : Vérification. On sépare les termes du numérateur sur le dénominateur commun : $\\frac{x^2+1}{x} = \\frac{x^2}{x} + \\frac{1}{x} = x + \\frac{1}{x}$. L\'égalité est validée.',
            'Correction b) : Primitive. En exploitant cette nouvelle écriture, on primitive terme à terme : la primitive de $x$ donne $\\frac{x^2}{2}$, et celle de $\\frac{1}{x}$ donne $\\ln|x|$. Comme $x>0$, les barres de valeur absolue s\'effacent : $F(x) = \\frac{x^2}{2} + \\ln(x) + C$.',
            'Correction c) : Aire. La fonction étant strictement positive sur $[1; 3]$, on intègre : $I = \\int_1^3 (x + \\frac{1}{x}) dx = [\\frac{x^2}{2} + \\ln(x)]_1^3 = (\\frac{9}{2} + \\ln(3)) - (\\frac{1}{2} + \\ln(1)) = \\frac{8}{2} + \\ln(3) = 4 + \\ln(3) \\text{ u.a.}$.\nConversion : unité = 2 cm $\\implies 1 \\text{ u.a.} = 2 \\times 2 = 4\\text{ cm}^2$. $\\text{Aire totale} = 4 \\times (4 + \\ln(3)) = 16 + 4\\ln(3)\\text{ cm}^2$.',
          ],
          reponse: '16 + 4\\ln(3)',
          conseil: 'Scinder une fraction lourde en blocs simples est le réflexe numéro 1 des majors pour s\'éviter des calculs de primitives inextricables.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-6',
          niveau: 'BAC',
          enonce: 'SUJET 6 : Calcul de valeur moyenne d\'un rendement agricole\n[Temps recommandé : 15 min]\n\nLa production de manioc d\'un champ au cours des 4 premières années d\'exploitation suit le modèle fonctionnel : $P(t) = 2t + 5$ (où t est en années et P en tonnes).\n\na) Calculer la valeur moyenne exacte du rendement sur la période allant de l\'année $t=0$ à l\'année $t=4$.\nb) Donner une interprétation concrète de ce résultat.',
          etapes: [
            'Correction a) : Valeur moyenne. On déploie la formule de l\'intervalle : $\\mu = \\frac{1}{4-0} \\int_0^4 (2t + 5) dt$. Le lisseur extérieur vaut $\\frac{1}{4}$. La primitive de la fonction est $t^2 + 5t$. Appliquons le crochet d\'attente : $\\mu = \\frac{1}{4} [t^2 + 5t]_0^4 = \\frac{1}{4} [ (4^2 + 5(4)) - 0 ] = \\frac{1}{4} [ 16 + 20 ] = \\frac{1}{4} \\times 36 = 9$ tonnes.',
            'Correction b) : Interprétation. La valeur moyenne obtenue est de 9 tonnes de manioc par an. Cela signifie que si la production avait été totalement constante et uniforme sur ces 4 années, le champ aurait produit exactement le même tonnage cumulé total de 36 tonnes.',
          ],
          reponse: '9',
          conseil: 'Ne confonds pas l\'intégrale brute (le cumul total de 36 tonnes) et la valeur moyenne (le rendement lissé de 9 tonnes par an).',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-7',
          niveau: 'BAC',
          enonce: 'SUJET 7 : Surfaces de intersections doubles (Courbes croisées)\n[Temps recommandé : 25 min]\n\nSoit les fonctions f et g définies sur $[-1; 1]$ par $f(x) = x^3$ et $g(x) = x$.\n\na) Déterminer les abscisses exactes de tous les points d\'intersection des deux courbes.\nb) Justifier de façon rigoureuse que l\'aire totale emprisonnée entre les deux tracés sur l'intervalle $[-1; 1]$ est égale à $\\frac{1}{2} \\text{ u.a.}$',
          etapes: [
            'Correction a) : Intersections. On pose $f(x) = g(x) \\implies x^3 = x \\implies x^3 - x = 0 \\implies x(x^2 - 1) = 0 \\implies x(x-1)(x+1) = 0$. Les trois abscisses de croisement sont $x = -1, x = 0$, et $x = 1$.',
            'Correction b) : Aire totale. On étudie la position relative sur chaque intervalle. Sur $[-1; 0]$, $x^3 \\ge x$, la courbe de f est au-dessus. Sur $[0; 1]$, $x \\ge x^3$, la courbe de g est supérieure. On applique la relation de Chasles pour découper le calcul : $\\text{Aire} = \\int_{-1}^0 (x^3 - x) dx + \\int_0^1 (x - x^3) dx$. Using the primitive $\\frac{x^4}{4} - \\frac{x^2}{2}$ : \n  - Bloc 1 : $[\\frac{x^4}{4} - \\frac{x^2}{2}]_{-1}^0 = 0 - (\\frac{1}{4} - \\frac{1}{2}) = \\frac{1}{4}$.\n  - Bloc 2 : $[\\frac{x^2}{2} - \\frac{x^4}{4}]_0^1 = (\\frac{1}{2} - \\frac{1}{4}) - 0 = \\frac{1}{4}$.\n$\\text{Aire totale} = \\frac{1}{4} + \\frac{1}{4} = \\frac{1}{2} \\text{ u.a.}$. La démonstration est validée !',
          ],
          reponse: '\\frac{1}{2}',
          conseil: 'La parité et la symétrie des fonctions impaires permettent de constater que les deux surfaces découpées possèdent exactement la même aire.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-8',
          niveau: 'BAC',
          enonce: 'SUJET 8 : Situation Complexe — Cinématique d\'un Gbaka d\'Adjamé\n[Temps recommandé : 20 min]\n\nLa vitesse instantanée d\'un « Gbaka » (en m/s) circulant sur la route de Bingerville est modélisée en fonction du temps t par l\'expression : $v(t) = t^2 + 2t$ (pour t en secondes).\n\na) Exprimer la fonction de la distance parcourue d(t) sachant qu\'à l\'instant initial t = 0 s, le véhicule est à l\'arrêt complet (distance nulle).\nb) Calculer la distance exacte parcourue par le Gbaka entre la 1ère et la 3ème seconde du trajet.',
          etapes: [
            'Correction a) : Fonction distance. La vitesse instantanée est la dérivée temporelle de la position. Par conséquent, la distance d(t) est la primitive de v(t) : $d(t) = \\int (t^2 + 2t) dt = \\frac{t^3}{3} + t^2 + C$. Appliquons la condition initiale d\'arrêt : $d(0) = 0 \\implies \\frac{0^3}{3} + 0^2 + C = 0 \\implies C = 0$. La trajectoire est donnée par : $d(t) = \\frac{t^3}{3} + t^2$.',
            'Correction b) : Distance parcourue. On calcule l\'intégrale définie entre 1 et 3 s : $\\int_1^3 (t^2 + 2t) dt = d(3) - d(1)$. On calcule d(3) : $\\frac{3^3}{3} + 3^2 = 9 + 9 = 18$ m. On calcule d(1) : $\\frac{1^3}{3} + 1^2 = \\frac{4}{3}$ m. Distance finale = $18 - \\frac{4}{3} = \\frac{54 - 4}{3} = \\frac{50}{3}$ m (soit environ 16,67 mètres).',
          ],
          reponse: '\\frac{50}{3}',
          conseil: 'La cinématique se résout mécaniquement grâce aux primitives : la distance est la primitive de la vitesse, qui est elle-même la primitive de l\'accélération.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-9',
          niveau: 'BAC',
          enonce: 'SUJET 9 : Intégrale d\'une forme logarithmique composée\n[Temps recommandé : 15 min]\n\nSoit la fonction f définie sur l\'intervalle $[1; e]$ par l\'expression $f(x) = \\frac{\\ln(x)}{x}$.\n\na) Justifier proprement que f(x) est de la structure composée du produit $u\'(x) \\times u(x)$.\nb) En déduire la valeur exacte de l\'intégrale définie : $J = \\int_1^e \\frac{\\ln(x)}{x} dx$.',
          etapes: [
            'Correction a) : Structure. L\'expression peut se réécrire sous la forme d\'un produit direct : $f(x) = \\frac{1}{x} \\times \\ln(x)$. Posons la brique interne $u(x) = \\ln(x)$. Sa dérivée associée est $u\'(x) = \\frac{1}{x}$. Nous détenons bien la forme exacte demandée $u\'(x) \\times u(x)^1$.',
            'Correction b) : Calcul de l\'intégrale. La primitive d\'une forme $u\'u^1$ suit le modèle $\\frac{1}{2}u^2$. La primitive de notre fonction est donc $F(x) = \\frac{(\\ln(x))^2}{2}$. Appliquons le théorème fondamental : $J = [\\frac{(\\ln(x))^2}{2}]_1^e = \\frac{(\\ln(e))^2}{2} - \\frac{(\\ln(1))^2}{2} = \\frac{1^2}{2} - \\frac{0^2}{2} = \\frac{1}{2}$. La valeur exacte est $\\frac{1}{2}$.',
          ],
          reponse: '\\frac{1}{2}',
          conseil: 'Repérer la présence de la dérivée usuelle $\\frac{1}{x}$ collée à un logarithme est l\'astuce ultime pour plier ce type d\'exercice en 5 secondes.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-t3-10',
          niveau: 'BAC',
          enonce: 'SUJET 10 : Le Problème de Synthèse du BAC D\n[Temps recommandé : 30 min]\n\nSoit la fonction f définie sur $]0 ; +\\infty[$ par l\'expression : $f(x) = x - 1 + \\frac{2}{x}$. On note (C) sa courbe représentative (Unité : 1 cm) et (D) la droite d\'équation affine $y = x - 1$.\n\na) Étudier les limites de f en $0^+$ et en $+\\infty$.\nb) Démontrer que la droite (D) constitue une asymptote oblique à la courbe en $+\\infty$.\nc) Calculer $f\'(x)$ et dresser le tableau de variations complet de f.\nd) Calculer la surface exacte du domaine compris entre la courbe (C), l\'asymptote (D) et les droites verticales $x=1$ et $x=e$.',
          etapes: [
            'Correction a) : Limites. En $0^+$ : $\\lim (x-1) = -1$ et $\\lim \\frac{2}{x} = +\\infty \\implies \\lim_{x \\to 0^+} f(x) = +\\infty$ (asymptote verticale $x=0$). En $+\\infty$ : $\\lim (x-1) = +\\infty$ et $\\lim \\frac{2}{x} = 0 \\implies \\lim_{x \\to +\\infty} f(x) = +\\infty$.',
            'Correction b) : Asymptote oblique. On étudie la limite de la différence : $\\lim_{x \\to +\\infty} (f(x) - y_{(D)}) = \\lim_{x \\to +\\infty} \\frac{2}{x} = 0$. La droite (D) est bien asymptote oblique.',
            'Correction c) : Dérivée et variations. On dérive terme à terme : $f\'(x) = 1 - 0 - \\frac{2}{x^2} = \\frac{x^2 - 2}{x^2}$. Le dénominateur $x^2$ est strictement positif. On résout $x^2 - 2 = 0 \\implies x = \\sqrt{2}$ (car $x>0$). La dérivée est négative sur $]0; \\sqrt{2}[$ (la courbe descend) et positive sur $]\\sqrt{2}; +\\infty[$ (la courbe monte). Le minimum local est situé à l\'abscisse $\\sqrt{2}$.',
            'Correction d) : Aire géométrique. On intègre la différence positive entre les frontières données : $f(x) - y_{(D)} = \\frac{2}{x}$. Sur l\'intervalle $[1; e]$, $\\frac{2}{x} > 0$, la courbe est au-dessus. $\\text{Aire} = \\int_1^e \\frac{2}{x} dx \\times \\text{u.a.} = [2\\ln(x)]_1^e = 2\\ln(e) - 2\\ln(1) = 2(1) - 0 = 2 \\text{ u.a.}$. L\'unité étant de 1 cm, la surface mesure exactement $2\\text{ cm}^2$.',
          ],
          reponse: '2\\text{ cm}^2',
          conseil: 'L\'asymptote oblique et la courbe s\'enferment mutuellement. L\'intégration de leur différence est le grand classique des fins de problèmes d\'analyse.',
        },
      ],
    },
    {
      id: 's5',
      titre: '5.4 Exercices pour t\'Entraîner Seul (Le Sac de Frappe)',
      blocs: [
        {
          type: 'text',
          id: 'b12-accroche',
          contenu: 'Maintenant, pas de pitié, pas de filet de sécurité. Voici 10 défis flash pour forger ton autonomie. Seul le résultat final est fourni, la démarche t\'appartient !',
        },
        {
          type: 'exercise',
          id: 'sac-t3-1',
          niveau: 'BASE',
          enonce: '5.4.1 : Déterminer la primitive générale de la fonction polynomiale : $f(x) = 5x^4 - 2x + 1$',
          etapes: ['Résous l\'énoncé sur ton brouillon et valide ton expression avec le bouton réponse.'],
          reponse: 'x^5 - x^2 + x + C',
          conseil: 'Applique la règle de puissance terme à terme en simplifiant immédiatement les fractions de tête.',
        },
        {
          type: 'exercise',
          id: 'sac-t3-2',
          niveau: 'BASE',
          enonce: '5.4.2 : Calculer la valeur numérique exacte de l\'intégrale définie : $I = \\int_{-1}^2 3x^2 dx$',
          etapes: ['Mets en place ton crochet d\'attente, évalue la borne haute moins la borne basse.'],
          reponse: '9',
          conseil: 'Fais attention aux puissances impaires sur la borne inférieure négative : $(-1)^3 = -1$.',
        },
        {
          type: 'exercise',
          id: 'sac-t3-3',
          niveau: 'BASE',
          enonce: '5.4.3 : Trouver l\'ensemble des primitives de la fonction constante fractionnaire : $g(x) = \\frac{1}{2}$',
          etapes: ['Rappelle-toi la règle de remontage d\'un nombre fixe spectateur.'],
          reponse: '\\frac{1}{2}x + C',
          conseil: 'Une constante gagne simplement la variable linéaire lors de l\'intégration.',
        },
        {
          type: 'exercise',
          id: 'sac-t3-4',
          niveau: 'MOYEN',
          enonce: '5.4.4 : Déterminer la primitive générale de la composée exponentielle linéaire : $h(x) = e^{3x}$',
          etapes: ['Applique la compensation par l\'inverse du coefficient de l\'exposant devant ton bloc.'],
          reponse: '\\frac{1}{3}e^{3x} + C',
          conseil: 'Le coefficient 3 se retrouve en division sous l\'expression.',
        },
        {
          type: 'exercise',
          id: 'sac-t3-5',
          niveau: 'MOYEN',
          enonce: '5.4.5 : Calculer la valeur moyenne exacte de la fonction constante $f(x) = 2$ sur l\'intervalle $[4 ; 10]$',
          etapes: ['Déploie la formule avec le lisseur extérieur $\\frac{1}{b-a}$.'],
          reponse: '2',
          conseil: 'La valeur moyenne d\'une fonction constante est mathématiquement égale à cette constante elle-même.',
        },
        {
          type: 'exercise',
          id: 'sac-t3-6',
          niveau: 'MOYEN',
          enonce: '5.4.6 : Calculer la valeur exacte de l\'intégrale trigonométrique : $I = \\int_0^{\\pi/2} \\cos(x) dx$',
          etapes: ['Remonte au parent du cosinus, pose le crochet et évalue les angles usuels.'],
          reponse: '1',
          conseil: 'Rappelle-toi que $\\sin(\\pi/2) = 1$ et $\\sin(0) = 0$.',
        },
        {
          type: 'exercise',
          id: 'sac-t3-7',
          niveau: 'BAC',
          enonce: '5.4.7 : Calculer la superficie en cm² sous la courbe d\'équation $y = x^3$ entre $x = 0$ et $x = 2$ sachant que l\'unité graphique est de 1 cm.',
          etapes: ['Vérifie la positivité, intègre la puissance et applique l\'unité physique.'],
          reponse: '4\\text{ cm}^2',
          conseil: 'Le crochet donne $[\\frac{x^4}{4}]_0^2 = \\frac{16}{4} = 4 \\text{ u.a.}$, convertis directement avec 1 cm².',
        },
        {
          type: 'exercise',
          id: 'sac-t3-8',
          niveau: 'BAC',
          enonce: '5.4.8 : Déterminer l\'ensemble des primitives de la fraction rationnelle : $f(x) = \\frac{2x}{x^2 + 4}$',
          etapes: ['Vérifie si le numérateur correspond à la dérivée exacte de ta brique du bas.'],
          reponse: '\\ln(x^2 + 4) + C',
          conseil: 'Comme $x^2 + 4$ est strictement positif sur $\\mathbb{R}$, tu peux d\'office remplacer la valeur absolue par des parenthèses.',
        },
        {
          type: 'exercise',
          id: 'sac-t3-9',
          niveau: 'BAC',
          enonce: '5.4.9 : Déterminer une primitive générale de la fonction composée exponentielle : $f(x) = xe^{x^2}$',
          etapes: ['Force l\'apparition du coefficient 2 de la dérivée de l\'exposant et compense devant.'],
          reponse: '\\frac{1}{2}e^{x^2} + C',
          conseil: 'Applique le modèle ajusté $\\frac{1}{2}u\'e^u$.',
        },
        {
          type: 'exercise',
          id: 'sac-t3-10',
          niveau: 'BAC',
          enonce: '5.4.10 : Si une courbe traverse l\'axe des abscisses au point critique $x = 1$ et qu\'on cherche sa surface sur $[0; 2]$, quelle méthode emploies-tu ?',
          etapes: ['Réponds en un mot ou par l\'énoncé de la propriété théorique requise.'],
          reponse: 'La relation de Chasles',
          conseil: 'Découpe ton intégrale de 0 à 1 et de 1 à 2 en inversant le bloc négatif pour additionner deux superficies positives.',
        },
      ],
    },
  ],
  quiz: [],
};