// src/data/t3-primitives/chap4.ts
import { Chapitre } from '../../types/course';

export const chapitre3: Chapitre = {
  id: 't3-chap4',
  titre: 'Calculer les Primitives — La Méthode',
  duree: 45,
  niveau: 'MOYEN',
  xpGain: 75,
  gratuit: false,
  objectifs: [
    'Maîtriser le tableau complet des primitives usuelles de référence',
    'Appliquer la règle de la constante et de la fonction affine intégrée',
    'Manipuler les 4 formes reines de primitives composées au BAC',
    'Déployer l\'Algorithme de Décision et le Processus EDUCTOME en 5 étapes',
    'Esquiver le piège de la division par zéro avec l\'exception de 1/x',
    'Résoudre avec succès les 10 exercices fondamentaux d\'entraînement',
  ],
  sections: [
    {
      id: 's1',
      titre: 'Introduction — La recette du Garba Mathématique',
      blocs: [
        {
          type: 'text',
          id: 'b1-accroche',
          contenu: 'Champion(ne), te voilà arrivé au cœur du réacteur. Quittons la théorie pour acquérir la force du calcul mécanique et briller devant ta copie !',
        },
        {
          type: 'text',
          id: 'b1',
          contenu: "Dans le chapitre précédent, on a beaucoup discuté. Tu as saisi l'intuition, tu as visualisé les gbakas et les réservoirs d'eau. C'est parfait. Mais au BAC, le correcteur ne te notera pas sur ta capacité à imaginer, il te notera sur ta capacité à calculer.",
        },
        {
          type: 'text',
          id: 'b2',
          contenu: "📖 L'ANECDOTE DU GRAND FRÈRE :\nQuand j'étais en Terminale au Lycée Classique d'Abidjan, le fameux \"Cacao\", on avait un camarade qu'on appelait \"Le Philosophe\". Il comprenait toujours la théorie avant tout le monde. Quand le prof expliquait que l'intégrale c'était l'aire sous la courbe, il hochait la tête avec un grand sourire. Mais le jour du premier devoir surveillé sur les primitives, il a eu 04/20. Pourquoi ? Parce qu'il essayait de \"deviner\" les primitives au hasard, au feeling, sans connaître ses formules. Il m'a dit : « Vieux père, je sais ce que c'est, mais face au de type u'e^u ou u'/u, je bégaie ! ».\nJe lui ai répondu : « Écoute, les primitives, c'est exactement comme préparer le Garba. Tu peux comprendre philosophiquement que c'est un mélange de poisson thon et d'attiéké. Mais si tu ne connais pas la dose exacte de sel, d'huile et d'assaisonnement, ton Garba sera immangeable. En maths, tes ingrédients, ce sont tes formules. »",
        },
        {
          type: 'text',
          id: 'b3',
          contenu: "Tu as compris le concept, maintenant on apprend à CALCULER. Fini la philosophie, on passe à la technique pure. Prends ton cahier, on va dresser le tableau de tes ingrédients indispensables.",
        },
        {
          type: 'text',
          id: 'b4-transition',
          contenu: 'Ouvrons tout de suite l\'armoire aux ingrédients : le tableau complet des primitives directes à posséder en mémoire.',
        },
      ],
    },
    {
      id: 's2',
      titre: '3.1 Tableau des Primitives Usuelles & 3.2 Composées',
      blocs: [
        {
          type: 'text',
          id: 'b5-accroche',
          contenu: 'Ce tableau est ton bouclier. Apprends-le par cœur pour identifier le parent direct de chaque fonction usuelle.',
        },
        {
          type: 'text',
          id: 'b5',
          contenu: "Ce tableau est ton outil de référence. Tu ne dois pas \"essayer\" de t'en souvenir, tu dois le connaître sur le bout des doigts, comme ton propre numéro. Ce sont les primitives directes, les \"parents\" évidents des fonctions que tu as appris à dériver dans le Tome 2.",
        },
        {
          type: 'table',
          id: 'table-primitives-directes',
          titre: 'Primitives Usuelles de Référence',
          headers: ['Fonction $f(x)$', 'Primitive Générale $F(x)$', 'Intervalle de validité'],
          rows: [
            ['$k$ (constante)', '$kx + C$', '$x \\in \\mathbb{R}$'],
            ['$x$', '$\\frac{1}{2}x^2 + C$', '$x \\in \\mathbb{R}$'],
            ['$x^n$ ($n \\neq -1$)', '$\\frac{1}{n+1}x^{n+1} + C$', '$x \\in \\mathbb{R}$'],
            ['$\\frac{1}{x^2}$', '$-\\frac{1}{x} + C$', '$x \\neq 0$'],
            ['$\\frac{1}{\\sqrt{x}}$', '$2\\sqrt{x} + C$', '$x > 0$'],
            ['$e^x$', '$e^x + C$', '$x \\in \\mathbb{R}$'],
            ['$e^{ax}$ ($a \\neq 0$)', '$\\frac{1}{a}e^{ax} + C$', '$x \\in \\mathbb{R}$'],
            ['$\\frac{1}{x}$', '$\\ln|x| + C$', '$x \\neq 0$'],
            ['$\\cos(x)$', '$\\sin(x) + C$', '$x \\in \\mathbb{R}$'],
            ['$\\sin(x)$', '$-\\cos(x) + C$', '$x \\in \\mathbb{R}$'],
          ],
        },
        {
          type: 'text',
          id: 'b6',
          contenu: "Observons 3 exemples d'application directe immédiate :\n\n• Exemple 1 : On te donne $f(x) = x^4$. Tu regardes la ligne $x^n$ avec $n=4$. La formule donne : $F(x) = \\frac{1}{4+1}x^{4+1} + C = \\frac{x^5}{5} + C$.\n• Exemple 2 : On te donne $f(x) = e^{5x}$. Tu regardes la ligne $e^{ax}$ avec $a=5$. La formule dit $\\frac{1}{a}e^{ax}$, donc $F(x) = \\frac{1}{5}e^{5x} + C$.\n• Exemple 3 : On te donne $f(x) = \\cos(x)$. Lecture directe du tableau : $F(x) = \\sin(x) + C$.",
        },
        {
          type: 'text',
          id: 'b7',
          contenu: "SECTION 3.2 — PRIMITIVES DES FONCTIONS COMPOSÉES\nAu BAC, on ne te donnera pas que des fonctions simples. Les professeurs adorent les fonctions composées (les blocs imbriqués). Mais rassure-toi, c'est juste le tableau précédent avec un petit ajustement.\n\nA. La règle de base (Fonction affine à l'intérieur) :\nSi tu connais une primitive $F$ d'une fonction $f$, et qu'on remplace le $x$ par un bloc linéaire du type $ax+b$, la règle est simple : Si $F$ est une primitive de $f$, alors $\\frac{1}{a} \\times F(ax+b)$ est une primitive de $f(ax+b)$.",
        },
        {
          type: 'text',
          id: 'b8',
          contenu: "Exemple détaillé : Trouvons la primitive de $f(x) = e^{3x-2}$.\nLa fonction \"globale\" est l'exponentielle. On sait que la primitive de $e^X$ est $e^X$. À l'intérieur, on a $3x - 2$. Ici, notre coefficient $a$ vaut $3$. On applique la règle : on garde le bloc, et on divise par $a$ : $F(x) = \\frac{13}{e}^{3x-2} + C = \\frac{1}{3}e^{3x-2} + C$.\nVérification rapide : Si tu dérives $\\frac{1}{3}e^{3x-2}$, le $3$ de la dérivée interne va \"tomber\" et annuler le $\\frac{1}{3}$, te ramenant bien à $e^{3x-2}$. C'est facile, n'est-ce pas ?",
        },
        {
          type: 'table',
          id: 'table-composées-reines',
          titre: 'B. Les 4 Formes de Composées Classiques au BAC',
          headers: ['Forme de la dérivée rencontrée', 'Primitive associée $F(x)$', 'Point de vigilance'],
          rows: [
            ['$u\' \\cdot u^n$ ($n \\neq -1$)', '$\\frac{1}{n+1}u^{n+1} + C$', 'Isole la puissance n du bloc total'],
            ['$\\frac{u\'}{u^2}$', '$-\\frac{1}{u} + C$', 'Le carré doit être entier au bas'],
            ['$\\frac{u\'}{\\sqrt{u}}$', '$2\\sqrt{u} + C$', 'Idéal pour lever les racines au dénominateur'],
            ['$u\' \\cdot e^u$', '$e^u + C$', 'La dérivée u\' doit être présente devant'],
            ['$\\frac{u\'}{u}$', '$\\ln|u| + C$', 'Ressort le logarithme absolu de l\'expression'],
          ],
        },
        {
          type: 'text',
          id: 'b9',
          contenu: "C'est le niveau supérieur. Ici, le bloc à l'intérieur s'appelle $u(x)$. Et pour pouvoir primitiver, il faut absolument que la dérivée $u'(x)$ soit présente juste devant ! C'est la règle de la chaîne lue à l'envers.",
        },
        {
          type: 'text',
          id: 'b10-transition',
          contenu: 'Face à cette forêt de formules, tu as besoin d\'une boussole. Découvrons le GPS mental du Grand Frère pour savoir quelle technique activer.',
        },
      ],
    },
    {
      id: 's3',
      titre: '3.2 Suite — L\'Algorithme de Décision & Le Process en 5 Étapes',
      blocs: [
        {
          type: 'text',
          id: 'b11-accroche',
          contenu: 'Ne cherche plus au hasard en tâtonnant. Déploie l\'algorithme d\'interrogatoire pour forcer la fonction à avouer sa vraie nature.',
        },
        {
          type: 'dialogue',
          id: 'dialogue-gps-mental',
          pf: "Vieux père, stop ! Mon cerveau chauffe. Tu me donnes un tableau de 9 formules simples, puis 5 formules composées... Quand je suis devant ma copie de BAC et que je vois une fonction bizarre, comment je sais laquelle utiliser ? Je suis perdu d'avance !",
          gf: "C'est normal de paniquer au début, champion. C'est parce que tu n'as pas encore de GPS. Laisse-moi te donner mon algorithme secret, une méthode de décision en 4 étapes que tu vas te réciter mentalement à chaque fois :",
        },
        {
          type: 'table',
          id: 'table-decision-algorithm',
          titre: 'L\'Algorithme de Décision du Grand Frère',
          headers: ['Étape de Diagnostic', 'Question à poser à la fonction', 'Action à mener'],
          rows: [
            ['Étape 1', '« Est-ce que c\'est une simple somme de termes ? » (ex: $x^2 + 5x$)', 'Si OUI, tu intègres chaque morceau séparément. Si NON, passe à l\'étape 2.'],
            ['Étape 2', '« Y a-t-il une parenthèse avec une puissance ? » (ex: $(2x+1)^4$)', 'Si OUI, tu dois forcer l\'apparition de la forme $u\'u^n$. Si NON, passe à l\'étape 3.'],
            ['Étape 3', '« Y a-t-il un \"e\" (exponentielle) avec un bloc en haut ? » (ex: $xe^{x^2}$)', 'Si OUI, ton objectif est de construire la forme $u\'e^u$. Si NON, passe à l\'étape 4.'],
            ['Étape 4', '« Est-ce que c\'est une grosse fraction ? » (ex: $\\frac{2x}{x^2-5}$)', 'Si OUI, vérifie directement si le haut est la dérivée du bas pour utiliser la forme $\\frac{u\'}{u}$.'],
          ],
        },
        {
          type: 'dialogue',
          id: 'dialogue-gps-mental-fin',
          pf: "Ah, donc au lieu de chercher au hasard, je pose des questions à ma fonction pour l'obliger à avouer sa vraie nature ?",
          gf: "Exactement ! Tu l'interroges comme un commissaire de police à Adjamé. Et une fois qu'elle a avoué, tu appliques le process en 5 étapes que voici pour poser ton calcul sans trembler.",
        },
        {
          type: 'recap',
          id: 'process-5-etapes-primitives',
          titre: 'SECTION 3.3 — LE PROCESS EDUCTOME EN 5 ÉTAPES',
          contenu: [
            '1️⃣ ÉTAPE 1 : Identifier la nature de la fonction d\'après l\'Algorithme.',
            '2️⃣ ÉTAPE 2 : Associer la bonne formule théorique du tableau.',
            '3️⃣ ÉTAPE 3 : Poser u et calculer u\' au brouillon pour ajuster les coefficients parasites.',
            '4️⃣ ÉTAPE 4 : Rassembler l\'expression finale en ajoutant la constante + C.',
            '5️⃣ ÉTAPE 5 : Vérifier par la Règle d\'Or en redérivant ton résultat.',
          ],
        },
        {
          type: 'text',
          id: 'b12',
          contenu: "Voyons ce protocole militaire appliqué à 3 exercices guidés de référence :",
        },
        {
          type: 'exercise',
          id: 'ex-guided-somme',
          niveau: 'BASE',
          enonce: '🟢 NIVEAU BASE : Trouver les primitives de $f(x) = 3x^2 + 2x - 5$',
          etapes: [
            'Étape 1 (Identifier) : C\'est une somme de termes simples. On traite chaque morceau de façon usuelle.',
            'Étape 2 (Formule) : On utilise $x^n \\to \\frac{1}{n+1}x^{n+1}$ et $k \\to kx$.',
            'Étape 3 (Calcul) : Pour $3x^2 \\to 3 \\times \\frac{x^3}{3} = x^3$. Pour $2x \\to 2 \\times \\frac{x^2}{2} = x^2$. Pour $-5 \\to -5x$.',
            'Étape 4 (Assembler) : On réunit l\'ensemble avec la constante : $F(x) = x^3 + x^2 - 5x + C$.',
            'Étape 5 (Vérifier) : On dérive : $(x^3 + x^2 - 5x + C)\' = 3x^2 + 2x - 5 + 0$. C\'est parfait !',
          ],
          reponse: 'x^3 + x^2 - 5x + C',
          conseil: 'Traite chaque monôme séparément en simplifiant immédiatement les fractions de tête.',
        },
        {
          type: 'exercise',
          id: 'ex-guided-moyen-force',
          niveau: 'MOYEN',
          enonce: '🟡 NIVEAU MOYEN : Trouver les primitives de $g(x) = (2x + 1)^4$',
          etapes: [
            'Étape 1 (Identifier) : Parenthèse avec puissance, forme composée $u\'u^n$.',
            'Étape 2 (Formule) : Modèle de primitive : $\\frac{1}{n+1}u^{n+1}$. Ici $u = 2x + 1 \\implies u\' = 2$. Mais le 2 n\'est pas là devant !',
            'Étape 3 (Ajuster) : L\'astuce de compensation : on force le 2 à apparaître et on divise par 2 devant : $g(x) = \\frac{1}{2} \\times 2(2x + 1)^4$. On a bien $\\frac{1}{2} \\times u\'u^4$.',
            'Étape 4 (Assembler) : On intègre le bloc : $G(x) = \\frac{1}{2} \\times \\frac{(2x + 1)^5}{5} + C = \\frac{1}{10}(2x + 1)^5 + C$.',
            'Étape 5 (Vérifier) : Dérivons : $(\\frac{1}{10}(2x + 1)^5)\' = \\frac{1}{10} \\times 5 \\times 2(2x + 1)^4 = \\frac{10}{10}(2x + 1)^4 = (2x + 1)^4$. Validé !',
          ],
          reponse: '\\frac{1}{10}(2x + 1)^5 + C',
          conseil: 'Forcer l\'apparition du coefficient manquant et diviser par ce même nombre devant est la clé des primitives composées.',
        },
        {
          type: 'exercise',
          id: 'ex-guided-difficile-exp',
          niveau: 'BAC',
          enonce: '🔴 NIVEAU DIFFICILE : Trouver les primitives de $h(x) = xe^{x^2}$',
          etapes: [
            'Étape 1 (Identifier) : Exponentielle avec exposant variable complexe, forme $u\'e^u$.',
            'Étape 2 (Formule) : Modèle attendu : $e^u$. Ici $u = x^2 \\implies u\' = 2x$. L\'énoncé nous donne $x$, il manque le coefficient 2.',
            'Étape 3 (Ajuster) : On force le 2 et on compense avec $\\frac{1}{2}$ devant : $h(x) = \\frac{1}{2} \\times (2x)e^{x^2}$. On a bien la structure $\\frac{1}{2}u\'e^u$.',
            'Étape 4 (Assembler) : On applique la formule directe : $H(x) = \\frac{1}{2}e^{x^2} + C$.',
            'Étape 5 (Vérifier) : Dérivons : $(\\frac{1}{2}e^{x^2})\' = \\frac{1}{2} \\times 2xe^{x^2} = xe^{x^2}$. Le compte est bon !',
          ],
          reponse: '\\frac{1}{2}e^{x^2} + C',
          conseil: 'L\'exponentielle composée impose d\'avoir sa dérivée d\'exposant collée devant elle.',
        },
        {
          type: 'text',
          id: 'b13-transition',
          contenu: 'Le protocole d\'ajustement est maîtrisé. Passons à la section de vigilance absolue : l\'exception qui détruit la moyenne de milliers d\'élèves.',
        },
      ],
    },
    {
      id: 's4',
      titre: '3.4 Pièges à Éviter — L\'Exception Incontournable de 1/x',
      blocs: [
        {
          type: 'text',
          id: 'b14-accroche',
          contenu: 'Diviser par zéro est l\'interdit suprême de l\'univers. Découvrez pourquoi la formule des puissances s\'effondre face à la fonction 1/x.',
        },
        {
          type: 'text',
          id: 'b14',
          contenu: "SECTION 3.4 — PIÈGES À ÉVITER : La division par zéro. Champion, s'il te plaît, ouvre grand tes yeux. Cette erreur fait pleurer les correcteurs du BAC chaque année.",
        },
        {
          type: 'warning',
          id: 'piege-division-zero-puissance',
          contenu: "⚠️ PIÈGE À ÉVITER : L'EXCEPTION DE 1/x\n\nBeaucoup d'élèves, face à la fonction $f(x) = \\frac{1}{x}$, se croient malins en écrivant : « $\\frac{1}{x} = x^{-1}$, donc j'applique la formule de $x^n$ ». Et ils écrivent sur leur copie :\n$$F(x) = \\frac{1}{-1+1}x^{-1+1} = \\frac{x^0}{0} = \\frac{1}{0}$$",
        },
        {
          type: 'text',
          id: 'b15',
          contenu: "STOP !!! ALERTE GÉNÉRALE !!! Tu viens d'écrire une division par ZÉRO ! En mathématiques, diviser par zéro, c'est l'interdit absolu. C'est comme essayer de faire démarrer une voiture sans moteur. Le calcul explose. C'est pour cette raison exacte que dans le tableau usuel, la ligne de $x^n$ précise la condition absolue : $n \\neq -1$. La formule des puissances ne marche pas pour l'exposant $-1$.",
        },
        {
          type: 'rule',
          id: 'regle-exception-logarithme',
          titre: '📌 LA SOLUTION : LE ROYAUME DES LOGARITHMES',
          contenu: [
            'Quand la puissance de x est exactement égale à -1 (donc pour la fraction 1/x), on sort du système des puissances et on applique le logarithme :',
            '$$\\int \\frac{1}{x} dx = \\ln|x| + C$$',
            'N\'oublie jamais les barres de valeur absolue |x| autour du x, car la fonction ln n\'accepte dans son domaine que des nombres strictement positifs.',
          ],
        },
        {
          type: 'text',
          id: 'b16-transition',
          contenu: 'La boîte à outils et les consignes de sécurité sont en place. Entrons tout de suite dans la salle d\'entraînement pour faire tes gammes.',
        },
      ],
    },
    {
      id: 's5',
      titre: '3.5 La Salle d\'Entraînement — 10 Exercices Niveau BASE Corrigés',
      blocs: [
        {
          type: 'text',
          id: 'b17-accroche',
          contenu: 'C\'est en forgeant qu\'on devient forgeron. Cache les solutions, résous ces 10 énoncés au brouillon et déploie la vérification de la Règle d\'Or.',
        },
        {
          type: 'text',
          id: 'b17',
          contenu: "L'entraînement fait le maître. Si tu maîtrises parfaitement ces 10 petits exercices, tu auras les bases solides pour attaquer les problèmes du BAC sans trembler. Cache les corrections, essaie au brouillon, puis vérifie ta méthode !",
        },
        {
          type: 'exercise',
          id: 't3-ex-base-1',
          niveau: 'BASE',
          enonce: 'EXERCICE 1 : Déterminer une primitive de la fonction constante : $f(x) = 5$.',
          etapes: [
            'Étape 1 : Identification de la forme : Constante usuelle de type $k$.',
            'Étape 2 : Application de la formule : $k \\to kx$.',
            'Étape 3 : Résultat final avec ajout de la constante : $F(x) = 5x + C$.',
            'Étape 4 (Vérification Règle d\'Or) : La dérivée de $5x+C$ vaut bien $5+0 = 5$. Le résultat est validé.',
          ],
          reponse: '5x + C',
          conseil: 'Toute constante isolée gagne simplement la variable x lors de la recherche de sa primitive parent.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-2',
          niveau: 'BASE',
          enonce: 'EXERCICE 2 : Déterminer une primitive de la fonction puissance : $f(x) = x^3$.',
          etapes: [
            'Étape 1 : Identification de la forme : Puissance usuelle $x^n$ avec $n=3$.',
            'Étape 2 : Application de la formule : $\\frac{x^{n+1}}{n+1} = \\frac{x^{3+1}}{3+1}$.',
            'Étape 3 : Résultat final réduit avec la constante : $F(x) = \\frac{x^4}{4} + C$ ou $\\frac{1}{4}x^4 + C$.',
            'Étape 4 (Vérification Règle d\'Or) : La dérivée de $\\frac{1}{4}x^4$ donne $\\frac{1}{4} \\times 4x^3 = x^3$. Le compte est bon.',
          ],
          reponse: '\\frac{1}{4}x^4 + C',
          conseil: 'L\'exposant augmente d\'une unité et se retrouve en division sous le terme.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-3',
          niveau: 'BASE',
          enonce: 'EXERCICE 3 : Déterminer une primitive de la somme linéaire : $f(x) = 2x + 3$.',
          etapes: [
            'Étape 1 : Identification de la forme : Somme de puissances et constantes distinctes.',
            'Étape 2 : Application de la formule : On intègre $2x$ d\'un côté et $3$ de l\'autre de façon indépendante.',
            'Étape 3 : Résultat brut assemblé : $F(x) = 2 \\times \\frac{x^2}{2} + 3x + C$.',
            'Étape 4 : Simplification des coefficients : $F(x) = x^2 + 3x + C$.',
            'Étape 5 (Vérification Règle d\'Or) : La dérivée de $x^2+3x+C$ redonne bien $2x + 3$. Validé !',
          ],
          reponse: 'x^2 + 3x + C',
          conseil: 'Simplifie les fractions par les coefficients multiplicateurs dès l\'étape d\'assemblage.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-4',
          niveau: 'BASE',
          enonce: 'EXERCICE 4 : Déterminer une primitive du polynôme : $f(x) = x^2 - x + 1$.',
          etapes: [
            'Étape 1 : Identification de la forme : Polynôme standard, somme usuelle.',
            'Étape 2 : Application de la formule : Traitement pas-à-pas monôme par monôme.',
            'Étape 3 : Résultat final structuré : $F(x) = \\frac{x^3}{3} - \\frac{x^2}{2} + x + C$.',
            'Étape 4 (Vérification Règle d\'Or) : La dérivée donne $\\frac{1}{3}(3x^2) - \\frac{1}{2}(2x) + 1 = x^2 - x + 1$. C\'est parfait.',
          ],
          reponse: '\\frac{x^3}{3} - \\frac{x^2}{2} + x + C',
          conseil: 'Conserve précieusement les signes d\'origine attachés à chaque bloc séparé.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-5',
          niveau: 'BASE',
          enonce: 'EXERCICE 5 : Déterminer une primitive de la fraction inverse : $f(x) = \\frac{1}{x}$.',
          etapes: [
            'Étape 1 : Identification de la forme : C\'est le cas spécial de l'exception de l\'inverse.',
            'Étape 2 : Application de la formule : L\'inverse s\'intègre uniquement sous forme logarithmique : $\\frac{1}{x} \\to \\ln|x|$.',
            'Étape 3 : Résultat final avec constante : $F(x) = \\ln|x| + C$.',
            'Étape 4 (Vérification Règle d\'Or) : La dérivée de $\\ln|x|$ est de façon stricte $\\frac{1}{x}$. Validé.',
          ],
          reponse: '\\ln|x| + C',
          conseil: 'Marque toujours les barres verticales de la valeur absolue pour blinder ton expression.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-6',
          niveau: 'BASE',
          enonce: 'EXERCICE 6 : Déterminer une primitive de la fonction exponentielle : $f(x) = e^x$.',
          etapes: [
            'Étape 1 : Identification de la forme : Exponentielle standard de référence.',
            'Étape 2 : Application de la formule : La seule fonction de l\'univers égale à sa propre variation.',
            'Étape 3 : Résultat final direct : $F(x) = e^x + C$.',
            'Étape 4 (Vérification Règle d\'Or) : La dérivée de $e^x + C$ donne bien $e^x$. Validé.',
          ],
          reponse: 'e^x + C',
          conseil: 'L\'exponentielle de base reste inchangée lors du remontage mécanique.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-7',
          niveau: 'BASE',
          enonce: 'EXERCICE 7 : Déterminer une primitive de la composée exponentielle linéaire : $f(x) = e^{2x}$.',
          etapes: [
            'Étape 1 : Identification de la forme : Forme affine imbriquée dans l\'exposant de type $e^{ax}$ avec $a=2$.',
            'Étape 2 : Application de la formule : Règle de compensation par l\'inverse du coefficient : $\\frac{1}{a}e^{ax}$.',
            'Étape 3 : Résultat final assemblé : $F(x) = \\frac{1}{2}e^{2x} + C$.',
            'Étape 4 (Vérification Règle d\'Or) : La dérivée de $\\frac{1}{2}e^{2x}$ donne $\\frac{1}{2} \\times 2e^{2x} = e^{2x}$. Le compte est bon !',
          ],
          reponse: '\\frac{1}{2}e^{2x} + C',
          conseil: 'Divise toujours devant par la dérivée de l\'exposant linéaire pour compenser le calcul.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-8',
          niveau: 'BASE',
          enonce: 'EXERCICE 8 : Déterminer une primitive de la fonction trigonométrique : $f(x) = \\cos(x)$.',
          etapes: [
            'Étape 1 : Identification de la forme : Fonction trigonométrique usuelle du tableau.',
            'Étape 2 : Application de la formule : Lecture directe, le parent du cosinus est le sinus.',
            'Étape 3 : Résultat final direct : $F(x) = \\sin(x) + C$.',
            'Étape 4 (Vérification Règle d\'Or) : La dérivée de $\\sin(x) + C$ redonne strictement $\\cos(x)$. Validé.',
          ],
          reponse: '\\sin(x) + C',
          conseil: 'Aide-toi mentalement du cercle trigonométrique pour ne pas confondre le sens de rotation inverse.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-9',
          niveau: 'BASE',
          enonce: 'EXERCICE 9 : Déterminer une primitive du polynôme complexe : $f(x) = 3x^2 + 2x - 1$.',
          etapes: [
            'Étape 1 : Identification de la forme : Polynôme usuel avec coefficients multiplicateurs.',
            'Étape 2 : Application de la formule : Intégration terme à terme avec simplification immédiate.',
            'Étape 3 : Résultat brut développé : $F(x) = 3\\frac{x^3}{3} + 2\\frac{x^2}{2} - x + C$.',
            'Étape 4 : Expression épurée finale : $F(x) = x^3 + x^2 - x + C$.',
            'Étape 5 (Vérification Règle d\'Or) : La dérivée de l\'expression donne bien $3x^2 + 2x - 1$. Validé.',
          ],
          reponse: 'x^3 + x^2 - x + C',
          conseil: 'Les coefficients s\'annulent d\'eux-mêmes avec les dénominateurs d\'exposants, garde la tête froide.',
        },
        {
          type: 'exercise',
          id: 't3-ex-base-10',
          niveau: 'BASE',
          enonce: 'EXERCICE 10 : Déterminer une primitive de la fonction racine : $f(x) = \\sqrt{x}$.',
          etapes: [
            'Étape 1 : Identification de la forme : Fonction racine usuelle. Note que $\\sqrt{x} = x^{1/2}$.',
            'Étape 2 : Application de la formule : Règle des puissances fractionnaires $\\frac{x^{1/2+1}}{1/2+1} = \\frac{x^{3/2}}{3/2}$.',
            'Étape 3 : Inversion de la fraction du bas : $F(x) = \\frac{2}{3}x^{3/2} + C$, ce qui correspond à $\\frac{2}{3}x\\sqrt{x} + C$.',
            'Étape 4 (Vérification Règle d\'Or) : La dérivée de $\\frac{2}{3}x^{3/2}$ donne $\\frac{2}{3} \\times \\frac{3}{2}x^{3/2-1} = x^{1/2} = \\sqrt{x}$. Splendide !',
          ],
          reponse: '\\frac{2}{3}x\\sqrt{x} + C',
          conseil: 'Manipuler les racines sous forme d\'exposants fractionnaires simplifie toutes les opérations de recherche.',
        },
        {
          type: 'text',
          id: 'b18-bilan-chapter-3',
          contenu: 'Félicitations, Champion(ne) ! Tu viens de plier tes gammes de base de calcul de primitives sans sauter aucune pièce. On avance ensemble vers les applications concrètes.',
        },
      ],
    },
  ],
  quiz: [],
};