// src/data/t3-primitives/chap5.ts
import { Chapitre } from '../../types/course';

export const chapitre4: Chapitre = {
  id: 't3-chap5',
  titre: 'L\'Intégrale Définie et ses Applications',
  duree: 40,
  niveau: 'MOYEN',
  xpGain: 80,
  gratuit: false,
  objectifs: [
    'Appliquer le Théorème Fondamental du calcul intégral sans se tromper',
    'Utiliser les propriétés de l\'intégrale définie (Chasles, linéarité, positivité)',
    'Maîtriser la méthode de calcul en 4 étapes avec les crochets d\'attente',
    'Calculer des surfaces réelles en cm² grâce aux unités d\'aire (u.a.)',
    'Déjouer les pièges de signes et calculer des surfaces entre deux courbes',
    'Résoudre les 10 exercices de synthèse de niveau MOYEN',
  ],
  sections: [
    {
      id: 's1',
      titre: 'Introduction — Ne sois pas une simple calculatrice',
      blocs: [
        {
          type: 'text',
          id: 'b1-accroche',
          contents: 'Champion(ne), tu sais fabriquer des primitives dans ton atelier. Maintenant, découvre à quoi elles servent dans le monde réel pour mesurer l\'espace.',
        },
        {
          type: 'text',
          id: 'b1',
          contents: "Champion(ne), jusqu'ici nous avons passé beaucoup de temps dans l'atelier à apprendre à fabriquer nos outils. Tu sais dériver, et tu sais faire l'opération inverse : trouver une primitive. Mais à quoi ça sert dans la vraie vie ?",
        },
        {
          type: 'text',
          id: 'b2',
          contents: "📖 L'ANECDOTE DU GRAND FRÈRE (Le champ de cacao de la Riviera) :\nQuand j'étais au Lycée Classique d'Abidjan, le fameux \"Cacao\", on avait un camarade excellent en calcul. Il pouvait te trouver la primitive de la fonction la plus tordue en deux minutes. Un jour, le prof de maths lui donne une fonction et lui demande de calculer son intégrale entre 0 et 5. Le camarade trouve \"25\". Le prof le regarde et lui dit : « C'est juste. Mais que représente ce 25 ? » Mon ami est resté muet. Le prof a souri et a dessiné un champ irrégulier au tableau : « Ce 25, mon garçon, c'est la superficie exacte de ce champ en mètres carrés. Si tu ne sais pas ça, tu n'es pas un mathématicien, tu es juste une calculatrice. »",
        },
        {
          type: 'text',
          id: 'b3',
          contents: "Maintenant qu'on sait trouver des primitives, on va les UTILISER pour calculer des choses concrètes : des aires, des valeurs moyennes et des cumuls. Fini l'abstrait, on entre dans le monde réel, là où les mathématiques construisent des ponts, évaluent des terrains et optimisent des récoltes. Prêt ? Allons-y !",
        },
        {
          type: 'text',
          id: 'b4-transition',
          contents: 'Entrons tout de suite dans la définition formelle de la passerelle entre primitive et nombre : l\'intégrale définie.',
        },
      ],
    },
    {
      id: 's2',
      titre: '4.1 L\'Intégrale Définie — Théorème et Propriétés',
      blocs: [
        {
          type: 'text',
          id: 'b5-accroche',
          contents: 'Découvre le crochet d\'attente. C\'est l\'outil d\'urgence pour emballer tes calculs avant de soustraire la valeur basse à la valeur haute.',
        },
        {
          type: 'text',
          id: 'b5',
          contents: "Nous l'avons effleuré au Chapitre 2, mais ici c'est le moment de l'encadrer en or. C'est la passerelle officielle entre la fonction, sa primitive et le nombre final.",
        },
        {
          type: 'rule',
          id: 'b6-theoreme-fondamental',
          titre: '📌 LE THÉORÈME FONDAMENTAL DU CALCUL INTÉGRAL',
          contenu: [
            'Si f est une fonction continue sur un intervalle [a, b], et si F est une de ses primitives, alors l\'intégrale définie de f entre a et b est :',
            '$$\\int_a^b f(x)dx = [F(x)]_a^b = F(b) - F(a)$$',
            'Le crochet $[F(x)]_a^b$ est ta salle d\'attente. Tu mets ta primitive propre à l\'intérieur.',
            'Tu places ta borne de départ (a) en bas et ta borne d\'arrivée (b) en haut.',
            'Ensuite, tu sors du crochet en calculant la valeur du haut $F(b)$ MOINS la valeur du bas $F(a)$.',
            '⚠️ Remarque de sécurité : Pas besoin du \"+ C\" ici, car $(F(b)+C) - (F(a)+C) = F(b) - F(a)$, la constante s\'annule toujours !',
          ],
        },
        {
          type: 'table',
          id: 'table-proprietes-integrales',
          titre: 'Propriétés Fondamentales à connaître par cœur',
          headers: ['Nom de la propriété', 'Formule Mathématique LaTeX', 'En pratique / Utilité'],
          rows: [
            ['Linéarité (Somme)', '$\\int_a^b (f(x)+g(x))dx = \\int_a^b f(x)dx + \\int_a^b g(x)dx$', 'On peut séparer les calculs en blocs distincts.'],
            ['Linéarité (Coefficient)', '$\\int_a^b k\\cdot f(x)dx = k\\cdot\\int_a^b f(x)dx$', 'On fait sortir la constante spectatrice devant.'],
            ['Relation de Chasles', '$\\int_a^b f(x)dx + \\int_b^c f(x)dx = \\int_a^c f(x)dx$', 'Permet de découper un trajet en deux morceaux.'],
            ['Inversion des bornes', '$\\int_b^a f(x)dx = -\\int_a^b f(x)dx$', 'Inverser le sens du calcul change le signe du résultat.'],
            ['Intégrale nulle', '$\\int_a^a f(x)dx = 0$', 'Si le point de départ et d\'arrivée sont identiques, l\'aire est nulle.'],
          ],
        },
        {
          type: 'recap',
          id: 'b7-methode-4-etapes',
          titre: '🟦 LA MÉTHODE UNIVERSELLE DU CALCUL D\'INTÉGRALE',
          contenu: [
            '1️⃣ ÉTAPE 1 : Trouver une primitive F(x) de f(x) au brouillon.',
            '2️⃣ ÉTAPE 2 : Écrire la notation crochet $[F(x)]_a^b$ proprement sur ta copie.',
            '3️⃣ ÉTAPE 3 : Calculer $F(b) - F(a)$ en ouvrant de GRANDES parenthèses pour éviter les pièges de signes.',
            '4️⃣ ÉTAPE 4 : Simplifier le résultat sous forme de fraction irréductible (pas de décimales).',
          ],
        },
        {
          type: 'text',
          id: 'b8',
          contents: "Exemple guidé d'application : Calculons $I = \\int_0^3 (2x + 1) dx$.\n\n• ÉTAPE 1 : La primitive de $2x + 1$ est $x^2 + x$.\n• ÉTAPE 2 : On pose la salle d'attente : $I = [x^2 + x]_0^3$.\n• ÉTAPE 3 : On remplace : $I = (3^2 + 3) - (0^2 + 0) = (9 + 3) - 0$.\n• ÉTAPE 4 : On simplifie : $I = 12$. C'est net, propre et validé !",
        },
        {
          type: 'exercise',
          id: 'micro-ex-integrale-directe',
          niveau: 'BASE',
          enonce: 'À toi de jouer ! Applique la méthode en 4 étapes pour calculer l\'intégrale suivante : $I = \\int_1^2 3x^2 dx$. (Rappel : la primitive de $3x^2$ est $x^3$).',
          etapes: [
            'Étape 1 : Repère la primitive : $F(x) = x^3$.',
            'Étape 2 : Pose le crochet sur ta copie : $[x^3]_1^2$.',
            'Étape 3 : Déploie le calcul : $F(2) - F(1) = (2^3) - (1^3)$.',
            'Étape 4 : Réduis l\'expression numérique : $8 - 1 = 7$.',
          ],
          reponse: '7',
          conseil: 'Ouvre de grandes parenthèses dès que tes bornes comportent des nombres négatifs.',
        },
        {
          type: 'text',
          id: 'b9-transition',
          contents: 'Le mécanisme du calcul numérique est maîtrisé. Donnons-lui du sens géométrique en passant à la mesure des surfaces : le calcul d\'aires.',
        },
      ],
    },
    {
      id: 's3',
      titre: '4.2 Calcul d\'Aires — La Rive de la Lagune Ébrié',
      blocs: [
        {
          type: 'text',
          id: 'b10-accroche',
          contents: 'Découvre comment l\'analyse permet de mesurer des terrains tordus au bord de l\'eau. Fais attention à l\'astuce de conversion de l\'Unité d\'Aire !',
        },
        {
          type: 'text',
          id: 'b10',
          contents: "C'est ici que tu vas rafler la majorité de tes points. Au BAC série D, l'exercice 5 (l'étude de fonction) se termine pratiquement toujours par une question de calcul d'aire.",
        },
        {
          type: 'analogy',
          id: 'b11-analogie-lagune',
          titre: 'L\'AIRE SUR LA LAGUNE ÉBRIÉ',
          contenu: "Imagine que tu possèdes une parcelle de terrain au bord de la lagune Ébrié à Bingerville. Ta parcelle est bordée par une route droite en bas (l'axe des abscisses), deux clôtures rectilignes sur les côtés ($x=a$ et $x=b$), et la rive ondulée et sauvage de la lagune en haut (la courbe de ta fonction $f(x)$). Comment calculer sa superficie exacte ? C'est impossible avec les formules de géométrie du collège (rectangle, triangle). L'intégrale définie va venir découper ton terrain en une infinité de rectangles microscopiques verticaux et additionner leurs surfaces pour te donner l'aire exacte de ce terrain tordu !",
          conceptMath: "Si $f(x) \\ge 0$ sur l'intervalle $[a, b]$, l'aire de la région située sous la courbe est donnée par : $\\text{Aire} = \\int_a^b f(x)dx \\times \\text{u.a.}$",
        },
        {
          type: 'warning',
          id: 'b12-warning-ua',
          contenu: "⚠️ POINT DE VIGILANCE : L'UNITÉ D'AIRE (u.a.)\n\nLe résultat d'une intégrale donne une valeur en \"Unité d'Aire\". Pour avoir le résultat en cm² sur ta copie, regarde l'unité graphique imposée au début de l'énoncé. Si l'unité est de 2 cm sur chaque axe, alors $1 \\text{ u.a.} = 2\\text{ cm} \\times 2\\text{ cm} = 4\\text{ cm}^2$. Tu dois obligatoirement multiplier ton résultat d'intégrale par 4 pour obtenir les points !",
        },
        {
          type: 'text',
          id: 'b13',
          contents: "Étudions 3 exercices corrigés d'application directe :\n\n• Exercice Corrigé 1 : $f(x) = 3x^2$ sur $[1; 2]$. Unité graphique : 1 cm.\n  La fonction est positive. $\\text{Aire} = \\int_1^2 3x^2 dx$.\n  Primitive : $x^3$. Calcul : $[x^3]_1^2 = 2^3 - 1^3 = 8 - 1 = 7$.\n  Conversion : Unité = 1 cm $\\implies 1 \\text{ u.a.} = 1\\text{ cm}^2$.\n  Conclusion : L'aire est de $7\\text{ cm}^2$.\n\n• Exercice Corrigé 2 : $f(x) = e^x$ sur $[0; 1]$. Unité graphique : 2 cm.\n  L'exponentielle est toujours positive. $\\text{Aire} = \\int_0^1 e^x dx$.\n  Primitive : $e^x$. Calcul : $[e^x]_0^1 = e^1 - e^0 = e - 1$.\n  Conversion : Unité = 2 cm $\\implies 1 \\text{ u.a.} = 2 \\times 2 = 4\\text{ cm}^2$.\n  Conclusion : L'aire exacte est de $4(e - 1)\\text{ cm}^2$.\n\n• Exercice Corrigé 3 : $f(x) = \\frac{1}{x}$ sur $[1; e]$. Unité graphique : 1 cm.\n  Sur $[1; e]$, $\\frac{1}{x} > 0$. $\\text{Aire} = \\int_1^e \\frac{1}{x} dx$.\n  Primitive : $\\ln(x)$. Calcul : $[\\ln(x)]_1^e = \\ln(e) - \\ln(1) = 1 - 0 = 1$.\n  Conclusion : L'aire est de $1\\text{ cm}^2$.",
        },
        {
          type: 'text',
          id: 'b14-transition',
          contents: 'Tout est parfait quand la courbe plane au-dessus de l\'axe. Mais que se passe-t-il si elle plonge dans les négatifs ? Évitons l\'erreur incontournable de l\'aire négative.',
        },
      ],
    },
    {
      id: 's4',
      titre: '4.2 Suite — Changement de Signe & Relation de Chasles',
      blocs: [
        {
          type: 'text',
          id: 'b15-accroche',
          contents: 'Une surface physique négative n\'existe pas ! Apprends à découper ton intégrale avec Chasles pour redresser les blocs qui plongent.',
        },
        {
          type: 'dialogue',
          id: 'b16-dialogue-negatif',
          pf: "Vieux père, j'ai calculé mon intégrale pour une question d'aire et j'ai trouvé -15. C'est normal ?",
          gf: "Une intégrale calculée numériquement peut tout à fait être négative ! C'est le cas si ta courbe a plongé sous l'axe des abscisses (dans la zone des ordonnées négatives). L'outil calcule mécaniquement ce qu'il voit.",
        },
        {
          type: 'dialogue',
          id: 'b17-dialogue-negatif-fin',
          pf: "D'accord, donc j'écris fièrement sur ma copie que la surface de mon terrain est de -15 cm² ?",
          gf: "SURTOUT PAS, champion(ne) ! Une aire géométrique réelle ne peut jamais être négative ! Si l'énoncé te demande une AIRE et que la courbe passe en dessous de l'axe, tu dois corriger le tir en ajoutant un signe MOINS devant l'intégrale de cette zone pour inverser le résultat, ou appliquer des valeurs absolues : Aire = -(-15) = +15 u.a.",
        },
        {
          type: 'recap',
          id: 'b18-methode-signe-decoupe',
          titre: '🟥 PROTOCÔLE : DÉCOMPOSER SELON LE SIGNE',
          contenu: [
            '1. Chercher les racines de la fonction : résoudre f(x) = 0.',
            '2. Dresser le tableau de signes de f(x) sur l\'intervalle [a, b] demandé.',
            '3. Découper l\'intégrale globale en plusieurs morceaux grâce à la relation de Chasles.',
            '4. Placer un signe MOINS (−) devant les intégrales des morceaux où f(x) < 0.',
            'Formula : $$\\text{Aire} = \\int_a^c f(x)dx - \\int_c^b f(x)dx$$ (si f est négative entre c et b).',
          ],
        },
        {
          type: 'text',
          id: 'b19',
          contents: "Examinons 2 exercices pratiques d'application de découpage :\n\n• Exercice Corrigé 1 : Calculer l'aire délimitée par $f(x) = x - 2$ sur $[0; 4]$.\n  - Étape 1 & 2 : $x - 2 = 0 \\implies x = 2$. Sur $[0; 2]$, $f(x) \\le 0$ (en dessous). Sur $[2; 4]$, $f(x) \\ge 0$ (au-dessus).\n  - Étape 3 : $\\text{Aire} = -\\int_0^2 (x-2)dx + \\int_2^4 (x-2)dx$.\n  - Calcul 1 : $-[\\frac{x^2}{2} - 2x]_0^2 = -(\\frac{4}{2} - 4) = -(-2) = 2$.\n  - Calcul 2 : $[\\frac{x^2}{2} - 2x]_2^4 = (8 - 8) - (2 - 4) = 0 - (-2) = 2$.\n  - Conclusion : $\\text{Aire totale} = 2 + 2 = 4 \\text{ u.a.}$\n\n• Exercice Corrigé 2 : Calculer l'aire délimitée par $f(x) = x^3$ sur $[-1; 1]$.\n  - Étape 1 & 2 : $x^3 = 0 \\implies x = 0$. Négative sur $[-1; 0]$, positive sur $[0; 1]$.\n  - Étape 3 : $\\text{Aire} = -\\int_{-1}^0 x^3 dx + \\int_0^1 x^3 dx$.\n  - Calcul 1 : $-[\\frac{x^4}{4}]_{-1}^0 = -(0 - \\frac{1}{4}) = \\frac{1}{4}$.\n  - Calcul 2 : $[\\frac{x^4}{4}]_0^1 = \\frac{1}{4} - 0 = \\frac{1}{4}$.\n  - Conclusion : $\\text{Aire totale} = \\frac{1}{4} + \\frac{1}{4} = \\frac{1}{2} \\text{ u.a.}$.",
        },
        {
          type: 'text',
          id: 'b20-transition',
          contents: 'Nous savons gérer une courbe seule par rapport à l\'axe. Passons maintenant au cas le plus fréquent du BAC : l\'aire emprisonnée entre deux courbes qui se croisent.',
        },
      ],
    },
    {
      id: 's5',
      titre: '4.2 Suite — Surface Emprisonnée entre Deux Courbes',
      blocs: [
        {
          type: 'text',
          id: 'b21-accroche',
          contents: 'Qui est le chef en haut ? Exploite l\'étude de position relative effectuée dans ton problème pour soustraire la courbe du bas à celle du dessus.',
        },
        {
          type: 'dialogue',
          id: 'b22-dialogue-entre-courbes',
          pf: "L'aire sous une courbe seule, j'ai capté. Mais si j'ai DEUX courbes qui s'enferment comme un piège, je fais comment ? Je calcule les deux surfaces séparément et je soustrais ?",
          gf: "C'est exactement ça, champion(ne) ! Tu fais l'intégrale de 'La courbe du DESSUS' moins 'La courbe du DESSOUS'. C'est pour ça qu'à la question précédente de ton problème de BAC, on t'a fait étudier 'la position relative'. C'était pour identifier clairement qui domine en haut !",
        },
        {
          type: 'recap',
          id: 'b23-methode-entre-courbes',
          titre: '🎛️ MÉTHODE EN 4 ÉTAPES (Entre deux courbes)',
          contenu: [
            '1. Trouver les points d\'intersection : Résoudre f(x) = g(x) pour trouver tes bornes a et b (si elles ne sont pas fournies).',
            '2. Identifier la courbe dominante : Étudier le signe de la différence f(x) − g(x).',
            '3. Poser et calculer l\'intégrale de la différence : $\\int_a^b (\\text{Courbe Haut} - \\text{Courbe Bas})dx$.',
            '4. Conclure proprement en unités d\'aire (u.a.) ou en cm².',
          ],
        },
        {
          type: 'text',
          id: 'b24',
          contents: "Analysons 3 exercices types entièrement résolus :\n\n• Exercice Corrigé 1 (Simple) : Aire entre $f(x) = x$ et $g(x) = x^2$ sur $[0; 1]$.\n  - Intersections : $x = x^2 \\implies x(1-x) = 0 \\implies x=0$ and $x=1$.\n  - Position : Sur $[0; 1]$, $x \\ge x^2$. La droite est au-dessus de la parabole.\n  - Calcul : $A = \\int_0^1 (x - x^2)dx = [\\frac{x^2}{2} - \\frac{x^3}{3}]_0^1 = (\\frac{1}{2} - \\frac{1}{3}) - 0 = \\frac{1}{6}$. L'aire est de $\\frac{1}{6} \\text{ u.a.}$\n\n• Exercice Corrigé 2 (Exponentielle) : Aire emprisonnée entre $f(x) = e^x$ et $g(x) = x$ sur $[0; 1]$.\n  - Bornes fournies : 0 et 1.\n  - Position : On sait que $e^x > x$ partout sur $\\mathbb{R}$. La courbe de f est au-dessus.\n  - Calcul : $A = \\int_0^1 (e^x - x)dx = [e^x - \\frac{x^2}{2}]_0^1 = (e^1 - \\frac{1}{2}) - (e^0 - 0) = e - \\frac{1}{2} - 1 = e - 1,5 \\text{ u.a.}$\n\n• Exercice Corrigé 3 (Courbes qui se croisent) : Aire entre $f(x) = x^3$ and $g(x) = x$ sur $[-1; 1]$.\n  - Intersections : $x^3 = x \\implies x^3 - x = 0 \\implies x(x-1)(x+1) = 0$. Croisement en -1, 0, et 1.\n  - Position : Sur $[-1; 0]$, $x^3 \\ge x$ (f au-dessus). Sur $[0; 1]$, $x \\ge x^3$ (g au-dessus). Il faut découper !\n  - Calcul 1 : $\\int_{-1}^0 (x^3 - x)dx = [\\frac{x^4}{4} - \\frac{x^2}{2}]_{-1}^0 = 0 - (\\frac{1}{4} - \\frac{1}{2}) = \\frac{1}{4}$.\n  - Calcul 2 : $\\int_0^1 (x - x^3)dx = [\\frac{x^2}{2} - \\frac{x^4}{4}]_0^1 = (\\frac{1}{2} - \\frac{1}{4}) - 0 = \\frac{1}{4}$.\n  - Conclusion : $\\text{Aire totale} = \\frac{1}{4} + \\frac{1}{4} = \\frac{1}{2} \\text{ u.a.}$.",
        },
        {
          type: 'text',
          id: 'b25-transition',
          contents: 'Les surfaces géométriques n\'ont plus aucun secret pour toi. Passons à la dernière grande application théorique du chapitre : le lissage des valeurs ou la valeur moyenne.',
        },
      ],
    },
    {
      id: 's6',
      titre: '4.3 La Valeur Moyenne d\'une Fonction',
      blocs: [
        {
          type: 'text',
          id: 'b26-accroche',
          contents: 'Comment lisser des variations permanentes pour en extraire une tendance stable ? C\'sest le rôle de la formule de la valeur moyenne $\\mu$.',
        },
        {
          type: 'rule',
          id: 'b27-def-valeur-moyenne',
          titre: '📌 DÉFINITION DE LA VALEUR MOYENNE',
          contenu: [
            'La valeur moyenne d\'une fonction f sur un intervalle [a, b] est le nombre réel $\\mu$ (mu) défini par la formule :',
            '$$\\mu = \\frac{1}{b - a} \\int_a^b f(x)dx$$',
            'En pratique, c\'est le même calcul d\'intégrale, multiplié par l\'inverse de la largeur de l\'intervalle.',
          ],
        },
        {
          type: 'text',
          id: 'b28',
          contents: "Analysons 3 exercices de valeur moyenne résolus :\n\n• Exercice 1 : Calculer la valeur moyenne de $f(x) = 2x$ sur $[1; 5]$.\n  - Formule : $\\mu = \\frac{1}{5 - 1} \\int_1^5 2x dx = \\frac{1}{4} [x^2]_1^5$.\n  - Calcul : $\\frac{1}{4} (25 - 1) = \\frac{1}{4} \\times 24 = 6$. La valeur moyenne vaut 6.\n\n• Exercice 2 : Calculer la valeur moyenne de la fonction thermique $f(x) = \\cos(x)$ sur $[0; \\frac{\\pi}{2}]$.\n  - Formule : $\\mu = \\frac{1}{\\frac{\\pi}{2} - 0} \\int_0^{\\frac{\\pi}{2}} \\cos(x) dx = \\frac{2}{\\pi} [\\sin(x)]_0^{\\frac{\\pi}{2}}$.\n  - Calcul : $\\frac{2}{\\pi} (\\sin(\\frac{\\pi}{2}) - \\sin(0)) = \\frac{2}{\\pi} (1 - 0) = \\frac{2}{\\pi}$.\n\n• Exercice 3 : Lissage de croissance de population : $f(x) = e^x$ sur $[0; 2]$.\n  - Formule : $\\mu = \\frac{1}{2 - 0} \\int_0^2 e^x dx = \\frac{1}{2} [e^x]_0^2$.\n  - Calcul : $\\frac{1}{2} (e^2 - e^0) = \\frac{e^2 - 1}{2}$.",
        },
        {
          type: 'text',
          id: 'b29-transition',
          contents: 'Toutes les formules d\'applications sont verrouillées. Entrons immédiatement dans la grande salle d\'entraînement de niveau Terminale D : voici 10 exercices de niveau MOYEN résolus.',
        },
      ],
    },
    {
      id: 's7',
      titre: '4.4 La Salle de Sport — 10 Exercices Niveau MOYEN Corrigés',
      blocs: [
        {
          type: 'text',
          id: 'b30-accroche',
          contents: 'Ici, on arrête de s\'échauffer, on manipule les véritables structures du BAC. Prends une grande respiration et affronte ces 10 défis.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex1',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 1 : Intégrale définie de polynôme simple. Calcule la valeur exacte de : $I = \\int_{-1}^2 (3x^2 - 4x + 3) dx$.',
          etapes: [
            'Étape 1 : Trouve la primitive terme à terme : $F(x) = x^3 - 2x^2 + 3x$.',
            'Étape 2 : Écris ton crochet d\'attente : $I = [x^3 - 2x^2 + 3x]_{-1}^2$.',
            'Étape 3 : Évalue la borne haute : $F(2) = 2^3 - 2(2)^2 + 3(2) = 8 - 8 + 6 = 6$.',
            'Étape 4 : Évalue la borne basse avec des parenthèses de sécurité : $F(-1) = (-1)^3 - 2(-1)^2 + 3(-1) = -1 - 2 - 3 = -6$.',
            'Étape 5 : Effectue la soustraction finale : $I = F(2) - F(-1) = 6 - (-6) = 12$.',
          ],
          reponse: '12',
          bareme: 'Primitive juste (0,5 pt) + Calcul et résultat (0,5 pt) = 1 point.',
          conseil: 'Fais attention au moins devant le -6, moins par moins donne plus.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex2',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 2 : Intégrale avec exposant et logarithme. Calcule la valeur épurée de : $J = \\int_0^{\\ln(2)} e^{2x} dx$.',
          etapes: [
            'Étape 1 : Applique la primitive de $e^{ax}$ qui est $\\frac{1}{a}e^{ax} \\implies F(x) = \\frac{1}{2}e^{2x}$.',
            'Étape 2 : Pose le crochet sur ta copie : $J = [\\frac{1}{2}e^{2x}]_0^{\\ln(2)}$.',
            'Étape 3 : Évalue la borne haute : $\\frac{1}{2}e^{2\\ln(2)} = \\frac{1}{2}e^{\\ln(2^2)} = \\frac{1}{2}e^{\\ln(4)} = \\frac{1}{2} \\times 4 = 2$.',
            'Étape 4 : Évalue la borne basse : $\\frac{1}{2}e^{2(0)} = \\frac{1}{2}e^0 = \\frac{1}{2} \\times 1 = \\frac{1}{2}$.',
            'Étape 5 : Calcule la différence : $J = 2 - \\frac{1}{2} = \\frac{3}{2}$.',
          ],
          reponse: '\\frac{3}{2}',
          bareme: 'Primitive (0,5 pt) + Simplification logarithme (1 pt) = 1,5 point.',
          conseil: 'Utilise la règle de puissance du logarithme $2\\ln(2) = \\ln(4)$ pour faire sauter proprement l\'exponentielle.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex3',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 3 : Intégrale avec le logarithme donné. Sachant qu\'une primitive de $\\ln(x)$ est $F(x) = x\\ln(x) - x$, calcule la valeur exacte de : $K = \\int_1^e \\ln(x) dx$.',
          etapes: [
            'Étape 1 : L\'énoncé te fournit gracieusement la primitive, pose le crochet directement : $K = [x\\ln(x) - x]_1^e$.',
            'Étape 2 : Évalue la borne haute : $F(e) = e\\ln(e) - e = e(1) - e = e - e = 0$.',
            'Étape 3 : Évalue la borne basse : $F(1) = 1\\ln(1) - 1 = 1(0) - 1 = -1$.',
            'Étape 4 : Fais la soustraction finale : $K = F(e) - F(1) = 0 - (-1) = 1$.',
          ],
          reponse: '1',
          bareme: 'Application crochets (0,5 pt) + Résultat final (0,5 pt) = 1 point.',
          conseil: 'Rappelle-toi toujours que $\\ln(e) = 1$ et $\\ln(1) = 0$.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex4',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 4 : Intégrale avec la trigonométrie. Calcule la valeur exacte de : $L = \\int_0^{\\pi} \\sin(x) dx$.',
          etapes: [
            'Étape 1 : La primitive de $\\sin(x)$ est $-\\cos(x)$. Pose la salle d\'attente : $L = [-\\cos(x)]_0^{\\pi}$.',
            'Étape 2 : Évalue la borne haute : $-\\cos(\\pi) = -(-1) = 1$.',
            'Étape 3 : Évalue la borne basse : $-\\cos(0) = -(1) = -1$.',
            'Étape 4 : Calcule la différence : $L = 1 - (-1) = 1 + 1 = 2$.',
          ],
          reponse: '2',
          bareme: 'Primitive de signe correct (0,5 pt) + Valeurs trigo (0,5 pt) = 1 point.',
          conseil: 'Aide-toi mentalement du cercle trigonométrique pour valider que $\\cos(\\pi) = -1$.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex5',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 5 : Calcul d\'aire avec Unité graphique. Soit $f(x) = \\frac{1}{x^2}$ sur $x > 0$. Le plan possède une unité graphique de 2 cm. Calcule la surface exacte délimitée par la courbe, l\'axe horizontal et les droites $x=1$ et $x=3$.',
          etapes: [
            'Étape 1 : Vérifie la positivité : sur $[1; 3]$, $\\frac{1}{x^2} > 0$, la courbe domine l\'axe.',
            'Étape 2 : Pose l\'intégrale de surface : $\\text{Aire} = \\int_1^3 \\frac{1}{x^2} dx \\times \\text{u.a.}$',
            'Étape 3 : Intègre avec la primitive : $[-\\frac{1}{x}]_1^3 = (-\\frac{1}{3}) - (-\\frac{1}{1}) = -\\frac{1}{3} + 1 = \\frac{2}{3} \\text{ u.a.}$.',
            'Étape 4 : Calcule l\'unité d\'aire réelle : unité = 2 cm $\\implies 1 \\text{ u.a.} = 2\\text{ cm} \\times 2\\text{ cm} = 4\\text{ cm}^2$.',
            'Étape 5 : Multiplie le résultat : $\\text{Aire} = \\frac{2}{3} \\times 4 = \\frac{8}{3}\\text{ cm}^2$.',
          ],
          reponse: '\\frac{8}{3}',
          bareme: 'Intégrale couplée justifiée (1 pt) + Conversion finale en cm² (1 pt) = 2 points.',
          conseil: 'Le piège fréquent est d\'oublier de multiplier par les 4 cm² de l\'unité graphique.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex6',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 6 : Calcul d\'aire avec bascule de signe. Soit $f(x) = x^3 - x$. Calcule l\'aire fermée par la courbe et l\'axe horizontal sur l\'intervalle $[-1; 1]$. (Unité graphique : 1 cm).',
          etapes: [
            'Étape 1 : Étudie le signe par factorisation : $x(x-1)(x+1)$. Sur $[-1; 0]$, $f(x) \\ge 0$. Sur $[0; 1]$, $f(x) \\le 0$ (en dessous).',
            'Étape 2 : Découpe avec la relation de Chasles en inversant le bloc négatif : $\\text{Aire} = \\int_{-1}^0 (x^3-x)dx - \\int_0^1 (x^3-x)dx$.',
            'Étape 3 : Utilise la primitive $F(x) = \\frac{x^4}{4} - \\frac{x^2}{2}$.',
            'Étape 4 : Calcule le morceau 1 : $0 - (\\frac{1}{4} - \\frac{1}{2}) = \\frac{1}{4}$. Calcule le morceau 2 avec le moins : $-(\\frac{1}{4} - \\frac{1}{2} - 0) = \\frac{1}{4}$.',
            'Étape 5 : Somme les deux surfaces : $\\frac{1}{4} + \\frac{1}{4} = \\frac{1}{2}\\text{ cm}^2$.',
          ],
          reponse: '\\frac{1}{2}',
          bareme: 'Étude précise du signe (1 pt) + Chasles (0,5 pt) + Calcul final (0,5 pt) = 2 points.',
          conseil: 'Si tu n\'avais pas découpé, l\'intégrale globale directe aurait donné 0 par symétrie. Ce qui est faux pour une surface physique !',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex7',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 7 : Aire emprisonnée entre une courbe et une droite. Soit $f(x) = x^2 - 2x$ et la droite (D) d\'équation $y = x$. Calcule l\'aire de la zone fermée par les deux tracés. Unité graphique : 3 cm.',
          etapes: [
            'Étape 1 : Trouve les bornes par intersection : $x^2 - 2x = x \\implies x^2 - 3x = 0 \\implies x(x-3) = 0$. Bornes : 0 et 3.',
            'Étape 2 : Signe de la différence : $f(x) - y = x^2 - 3x$. Sur $[0; 3]$, ce polynôme est négatif, donc la droite (y) domine la parabole.',
            'Étape 3 : Pose l\'intégrale de la différence positive : $\\int_0^3 (x - (x^2-2x))dx = \\int_0^3 (-x^2 + 3x) dx$.',
            'Note : La primitive associée est $-\\frac{x^3}{3} + \\frac{3x^2}{2}$.',
            'Étape 4 : Évalue les bornes : $(-\\frac{27}{3} + \\frac{3(9)}{2}) - 0 = -9 + 13,5 = 4,5 \\text{ u.a.}$.',
            'Étape 5 : Applique la conversion : unité = 3 cm $\\implies 1 \\text{ u.a.} = 3 \\times 3 = 9\\text{ cm}^2$. Aire finale = $4,5 \\times 9 = 40,5\\text{ cm}^2$.',
          ],
          reponse: '40,5',
          bareme: 'Intersections exactes (1 pt) + Intégration (1 pt) + Unité (0,5 pt) = 2,5 points.',
          conseil: 'Soustrait toujours la courbe du bas à celle du dessus pour manipuler une aire positive.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex8',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 8 : Aire fermée entre deux paraboles. Calcule la surface délimitée par les deux fonctions suivantes : $f(x) = x^2$ et $g(x) = -x^2 + 2$. (Unité graphique : 1 cm).',
          etapes: [
            'Étape 1 : Calcule les bornes d\'intersection : $x^2 = -x^2 + 2 \\implies 2x^2 = 2 \\implies x^2 = 1 \\implies x = -1$ et $x = 1$.',
            'Étape 2 : Étudie la position : $g(x) - f(x) = -2x^2 + 2$. Sur $[-1; 1]$, cette expression est positive, g est donc la courbe supérieure.',
            'Étape 3 : Pose l\'intégrale : $\\text{Aire} = \\int_{-1}^1 (-2x^2 + 2) dx$. La primitive est $-\\frac{2x^3}{3} + 2x$.',
            'Étape 4 : Évalue en 1 : $-\\frac{2}{3} + 2 = \\frac{4}{3}$. Évalue en -1 : $\\frac{2}{3} - 2 = -\\frac{4}{3}$.',
            'Étape 5 : Calcule la différence : $\\frac{4}{3} - (-\\frac{4}{3}) = \\frac{8}{3}\\text{ cm}^2$.',
          ],
          reponse: '\\frac{8}{3}',
          bareme: 'Intersections validées (0,5 pt) + Calcul algébrique complet (1,5 pt) = 2 points.',
          conseil: 'Exploite la parité de la fonction pour calculer deux fois l\'intégrale entre 0 et 1 si tu veux aller plus vite.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex9',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 9 : Calcul de valeur moyenne linéaire. Détermine la valeur moyenne exacte de la fonction $f(x) = 3x^2 + 1$ sur l\'intervalle $[-1; 2]$.',
          etapes: [
            'Étape 1 : Applique la formule de l\'intervalle : $\\mu = \\frac{1}{b-a}\\int_a^b f(x)dx \\implies \\mu = \\frac{1}{2 - (-1)} \\int_{-1}^2 (3x^2 + 1) dx$.',
            'Étape 2 : Le coefficient de lissage devant vaut $\\frac{1}{3}$.',
            'Étape 3 : Extrais la primitive : $F(x) = x^3 + x$. Pose le crochet : $[x^3 + x]_{-1}^2$.',
            'Étape 4 : Calcule l\'intégrale interne : $(2^3 + 2) - ((-1)^3 + (-1)) = (8 + 2) - (-1 - 1) = 10 - (-2) = 12$.',
            'Étape 5 : Multiplie par le lisseur : $\\mu = \\frac{1}{3} \\times 12 = 4$.',
          ],
          reponse: '4',
          bareme: 'Formule correcte avec le lisseur (1 pt) + Calcul et résultat (1 pt) = 2 points.',
          conseil: 'N\'oublie jamais le facteur $\\frac{1}{b-a}$ devant le crochet, sinon tu calcules une intégrale simple et non une valeur moyenne.',
        },
        {
          type: 'exercise',
          id: 't3-moyen-ex10',
          niveau: 'MOYEN',
          enonce: 'EXERCICE 10 : Problème mixte type BAC. Soit les fonctions $f(x) = (x + 1)e^x$ et $F(x) = xe^x$.\na) Démontrer que F est une primitive de f sur $\\mathbb{R}$.\nb) En déduire la valeur exacte de l\'intégrale : $I = \\int_0^1 (x+1)e^x dx$.',
          etapes: [
            'Correction a) : Dérivons F(x) avec la formule du produit uv : $u=x \\implies u\'=1$ and $v=e^x \\implies v\'=e^x$. $F\'(x) = (1)e^x + x(e^x) = e^x(1+x) = (x+1)e^x = f(x)$. D\'après la Règle d\'Or, F est bien une primitive de f.',
            'Correction b) : On applique le théorème fondamental directement avec la primitive validée : $I = [xe^x]_0^1$.',
            'Étape 3 : Évalue les bornes : $F(1) - F(0) = (1 \\cdot e^1) - (0 \\cdot e^0) = e - 0 = e$.',
            'Conclusion : La valeur exacte de l\'intégrale vaut e.',
          ],
          reponse: 'e',
          bareme: 'Dérivation complète juste (1,5 pt) + Calcul intégral direct (1 pt) = 2,5 points.',
          conseil: 'Quand l\'énoncé te fait démontrer qu\'une fonction est une primitive à la question précédente, sers-t-en immédiatement pour remplir tes crochets d\'intégration.',
        },
        {
          type: 'text',
          id: 'b31-conclusion-moyen',
          contenu: 'Champion(ne), tu as plié l\'ensemble des exercices techniques. Tu sais mesurer des parcelles sur la lagune et lisser des tendances.',
        },
      ],
    },
  ],
  quiz: [],
};