// src/data/t2-derivees/chap5.ts
import { Chapitre } from '../../types/course';

export const chapitre4: Chapitre = {
  id: 't2-chap5',
  titre: 'Applications et Études de Fonctions',
  duree: 50,
  niveau: 'BAC',
  xpGain: 100,
  gratuit: false,
  objectifs: [
    'Maîtriser la méthode complète d\'étude de variations en 5 étapes',
    'Identifier et différencier les extremums locaux et globaux',
    'Résoudre des situations complexes d\'optimisation économique et géométrique',
    'Calculer et appliquer des équations de tangentes courantes ou parallèles',
    'Venir à bout du Marathon du BAC contenant 10 exercices progressifs entièrement résolus',
  ],
  sections: [
    {
      id: 's1',
      titre: 'Introduction — Les secrets des traders de Cacao',
      blocs: [
        {
          type: 'text',
          id: 'b1-accroche',
          contenu: 'Champion(ne), tu as souffert pour apprendre à dériver au chapitre précédent. Maintenant, découvre comment cet outil devient ta boussole absolue pour décoder l\'économie et la vraie vie.',
        },
        {
          type: 'text',
          id: 'b1',
          contenu: "📖 L'ANECDOTE DU GRAND FRÈRE (Le Prix du Cacao à la Bourse) :\nTu as déjà écouté le journal de 20h à la RTI ? Tu entends souvent le présentateur dire : \"Le prix du cacao a atteint un pic historique aujourd'hui à la bourse de Londres avant de redescendre.\" Pendant longtemps, je pensais que les traders qui achètent et vendent notre cacao ivoirien utilisaient la magie pour savoir quand vendre. Mais un jour, un aîné qui travaille dans la finance m'a montré ses écrans. Ses graphiques ressemblaient exactement à ce qu'on fait en classe de Terminale ! Il m'a expliqué que pour maximiser les profits de l'État, ils utilisent des algorithmes qui calculent en permanence le taux de variation des prix. Dès que ce taux s'annule et devient négatif, la machine sait que le \"pic\" (le maximum) est atteint, et elle vend ! Le secret des traders de Wall Street ou de la City, ce n'est rien d'autre que l'étude du signe de la dérivée !",
        },
        {
          type: 'text',
          id: 'b2',
          contenu: "Champion(ne), tu as souffert dans le Chapitre 3 pour apprendre à dériver $u \\times v$ ou $u/v$. Maintenant qu'on sait calculer $f'(x)$, on va l'UTILISER. La dérivée n'est pas un but en soi, c'est un outil. C'est ta boussole. Dans ce chapitre, tu vas apprendre à te servir de cette boussole pour tracer des courbes parfaites, trouver les sommets des montagnes (les maximums) et résoudre des problèmes concrets pour optimiser des situations de la vraie vie. On y va !",
        },
        {
          type: 'text',
          id: 'b3-transition',
          contenu: 'Entrons tout de suite dans la première grande application : l\'étude de variations, la question reine de tous les sujets de Terminale D.',
        },
      ],
    },
    {
      id: 's2',
      titre: '4.1 Étude de Variations — La Méthode pas-à-pas',
      blocs: [
        {
          type: 'text',
          id: 'b4-accroche',
          contenu: 'Découvre le protocole universel d\'étude des variations. Applique cette recette à la lettre pour décoder l\'histoire complète d\'une courbe.',
        },
        {
          type: 'text',
          id: 'b4',
          contenu: "C'est la question incontournable du BAC. L'étude des variations te permet de connaître l'histoire complète de la fonction : d'où elle vient, quand elle monte, quand elle descend, et où elle va.",
        },
        {
          type: 'rule',
          id: 'b5-regle-variations',
          titre: '📌 RÈGLE D\'OR : LES 5 ÉTAPES DE L\'ÉTUDE DE VARIATIONS',
          contenu: [
            '1️⃣ ÉTAPE 1 : Calculer f\'(x). (Détermine l\'ensemble de dérivabilité, pose tes formules et calcule la dérivée propre et simplifiée).',
            '2️⃣ ÉTAPE 2 : Résoudre f\'(x) = 0. (Trouve les valeurs exactes de x où la dérivée s\'annule. C\'est là que la pente est plate).',
            '3️⃣ ÉTAPE 3 : Étudier le signe de f\'(x). (Savoir précisément sur quels intervalles f\'(x) > 0 et sur quels intervalles f\'(x) < 0).',
            '4️⃣ ÉTAPE 4 : Construire le tableau de variations. (Place les x, le signe de f\', et les flèches de variation de f : ↗ pour +, ↘ pour −).',
            '5️⃣ ÉTAPE 5 : Interpréter le tableau. (Calcule les images des sommets et les limites aux bornes pour compléter le tableau).',
          ],
        },
        {
          type: 'text',
          id: 'b6',
          contenu: "Exemple guidé complet : Étudions ensemble la fonction $f(x) = x^3 - 3x + 2$ sur $\\mathbb{R}$.\n\n• ÉTAPE 1 : Calculer $f\'(x)$. $f$ est une fonction polynôme, elle est donc dérivable sur $\\mathbb{R}$. On a $f\'(x) = 3x^2 - 3$. On factorise pour faciliter l'étude du signe : $f\'(x) = 3(x^2 - 1) = 3(x - 1)(x + 1)$.\n\n• ÉTAPE 2 : Résoudre $f\'(x) = 0$. $3(x - 1)(x + 1) = 0$. Les solutions sont $x = -1$ et $x = 1$. Ce sont nos \"points critiques\".\n\n• ÉTAPE 3 : Étudier le signe de $f\'(x)$. $f\'(x)$ est un trinôme du second degré ($ax^2 + bx + c$ avec $a = 3$). La règle classique nous dit : \"Signe de a à l'extérieur des racines, signe contraire de a à l'intérieur\". Ici, $a = 3$ (positif). Donc $f\'(x) > 0$ sur $]-\\infty ; -1[ \\cup ]1 ; +\\infty[$. Et $f\'(x) < 0$ sur $]-1 ; 1[$.",
        },
        {
          type: 'text',
          id: 'b7',
          contenu: "• ÉTAPES 4 et 5 : Construire le tableau et interpréter. Calculons d'abord les images et limites nécessaires :\n  - $f(-1) = (-1)^3 - 3(-1) + 2 = -1 + 3 + 2 = 4$ (Maximum local)\n  - $f(1) = 1^3 - 3(1) + 2 = 1 - 3 + 2 = 0$ (Minimum local)\n  - $\\lim_{x \\to -\\infty} f(x) = \\lim_{x \\to -\\infty} x^3 = -\\infty$\n  - $\\lim_{x \\to +\\infty} f(x) = \\lim_{x \\to +\\infty} x^3 = +\\infty$",
        },
        {
          type: 'table',
          id: 'b8-table-variations-exemple',
          titre: 'Tableau de variations complet de f(x) = x³ - 3x + 2',
          headers: ['x', '$-\\infty$', '−1', '1', '$+\\infty$'],
          rows: [
            ['Signe de f\'(x)', '', '+   |   0   |   −   |   0   |   +', ''],
            ['Variations de f(x)', '$-\\infty$', '↗   4', '↘   0', '↗   $+\\infty$'],
          ],
        },
        {
          type: 'dialogue',
          id: 'b9-dialogue-flèches',
          pf: "Vieux père, je sais faire le calcul, mais je t'avoue que je place les flèches machinalement. Pourquoi le \"plus\" (+) donne une flèche qui monte (↗) et le \"moins\" (-) donne une flèche qui descend (↘) ?",
          gf: "C'est une excellente remarque, champion ! Oublie les maths une seconde. Imagine que tu marches sur une route. Ta position, c'est la fonction f. Ta vitesse de marche, c'est la dérivée f'. Si tu avances vers l'avant, ta vitesse est positive (+), donc ta position sur la route augmente : la flèche monte ! Si tu recules, ta vitesse est négative (-), donc ta position diminue : la flèche descend.",
        },
        {
          type: 'dialogue',
          id: 'b10-dialogue-flèches-suite',
          pf: "Ah oui ! C'est super logique mis comme ça. Et quand c'est égal à 0 ?",
          gf: "Quand ta vitesse est de 0 km/h, tu es à l'arrêt ! Sur une courbe, c'est le moment précis où tu t'arrêtes de monter pour commencer à descendre (ou l'inverse). La pente y est totalement plate, horizontale. C'est ce qui forme le sommet ou le fond de la vallée.",
        },
        {
          type: 'text',
          id: 'b11-transition',
          contenu: 'Puisque nous parlons de sommets et de fonds de vallées, étudions de plus près ces points stratégiques qu\'on appelle les extremums.',
        },
      ],
    },
    {
      id: 's3',
      titre: '4.2 Extremums (Maximum et Minimum) — Le Piège du Zéro',
      blocs: [
        {
          type: 'text',
          id: 'b12-accroche',
          contenu: 'Savoir repérer un sommet sur ta copie est une chose, éviter le piège classique des faux extremums en est une autre. Faisons le point.',
        },
        {
          type: 'text',
          id: 'b12',
          contenu: "Un extremum, c'est un mot savant pour dire \"le point le plus haut\" (Maximum) ou \"le point le plus bas\" (Minimum). Il faut distinguer deux choses :\n\n• Extremum GLOBAL : C'est le boss final. Le point le plus haut de TOUTE la courbe sur tout son domaine (comme le sommet du Mont Tonkoui).\n\n• Extremum LOCAL : C'est le chef du quartier. C'est le point le plus haut dans ses environs immédiats, même s'il y a plus grand que lui ailleurs sur la courbe.",
        },
        {
          type: 'recap',
          id: 'b13-methode-extremums',
          titre: 'Méthode pour valider un extremum',
          contenu: [
            '1. Chercher où f\'(x₀) = 0. (La tangente doit obligatoirement être horizontale).',
            '2. Vérifier le CHANGEMENT DE SIGNE de f\'(x) autour de x₀ (passer de + à − pour un maximum, ou de − à + pour un minimum).',
            '3. Calculer f(x₀) pour trouver la hauteur exacte de cet extremum.',
          ],
        },
        {
          type: 'dialogue',
          id: 'b14-dialogue-zero',
          pf: "Attends, vieux père. J'ai bien compris que pour trouver le sommet, il faut résoudre f'(x) = 0. Mais pourquoi ton professeur insiste lourdement sur la deuxième condition : 'il faut que la dérivée change de signe' ? Si c'est zéro, c'est zéro, on a trouvé le sommet non ?",
          gf: "Faut pas te blaguer, c'est le piège classique où beaucoup d'élèves perdent des points au BAC ! Prends la fonction $f(x) = x^3$. Sa dérivée c'est $f'(x) = 3x^2$. Si tu résous $f'(x) = 0$, tu trouves $x = 0$. Donc la pente est bien plate en 0.",
        },
        {
          type: 'dialogue',
          id: 'b15-dialogue-zero-suite',
          pf: "Voilà ! Donc 0 est forcément un minimum ou un maximum !",
          gf: "Faux ! Regarde le signe de $3x^2$. Un carré est toujours positif ! Avant 0, la dérivée est positive (la courbe monte). En 0, la pente devient plate une microseconde. Mais après 0, la dérivée est ENCORE positive (la courbe continue de monter). Il n'y a pas de sommet ni de creux ! C'est un point d'inflexion, un 'palier' où tu te reposes avant de continuer à grimper. Si la dérivée s'annule SANS changer de signe, il n'y a PAS d'extremum !",
        },
        {
          type: 'text',
          id: 'b16',
          contenu: "Analysons 3 exercices corrigés d'application immédiate :\n\n• Exercice 1 (Application directe) : Soit $g(x) = -x^2 + 4x - 3$. Trouver ses extremums.\n  1. On dérive : $g'(x) = -2x + 4$.\n  2. On annule : $-2x + 4 = 0 \\implies 2x = 4 \\implies x = 2$.\n  3. Signe : Pour $x < 2, g'(x) > 0$ (+). Pour $x > 2, g'(x) < 0$ (−). La dérivée s'annule en 2 en passant de (+) à (−). $g$ admet un maximum local en $x = 2$, de valeur $g(2) = -(2)^2 + 4(2) - 3 = 1$.\n\n• Exercice 2 (Extremum avec fraction) : Soit $h(x) = x + \\frac{4}{x}$ sur $]0 ; +\\infty[$. Trouver ses extremums.\n  1. On dérive : $h'(x) = 1 - \\frac{4}{x^2} = \\frac{x^2-4}{x^2}$.\n  2. On annule : $\\frac{x^2-4}{x^2} = 0 \\implies x^2 - 4 = 0 \\implies x = 2$ (car $x > 0$).\n  3. Signe : Le dénominateur $x^2$ est positif. Le numérateur $x^2-4$ est négatif sur $]0; 2[$ et positif sur $]2; +\\infty[$. La dérivée s'annule en 2 en passant de (−) à (+). La fonction descend puis monte : $h$ admet un minimum local en $x = 2$, de valeur $h(2) = 2 + \\frac{4}{2} = 4$.\n\n• Exercice 3 (Le piège d'Abidjan) : Soit $k(x) = (x - 2)^3$. Déterminer ses extremums.\n  1. On dérive (formule $u^n$) : $k'(x) = 3 \\times 1 \\times (x - 2)^2 = 3(x - 2)^2$.\n  2. On annule : $3(x - 2)^2 = 0 \\implies x = 2$.\n  3. Signe : Le carré $(x-2)^2$ est toujours positif ou nul. Donc $k'(x) \\ge 0$ partout. La dérivée s'annule en 2 mais NE CHANGE PAS de signe.\nConclusion : La fonction $k$ n'admet aucun extremum. Elle est strictement croissante.",
        },
        {
          type: 'exercise',
          id: 'micro-ex-extremum-val',
          niveau: 'BASE',
          enonce: 'À toi de jouer ! Sur la base de l\'exercice 1 résolu ci-dessus où $g(x) = -x^2 + 4x - 3$, recalcule la valeur exacte du maximum au point $x = 2$. Quelle valeur obtiens-tu ?',
          etapes: [
            'Étape 1 : Remplace x par 2 dans la fonction d\'origine : $g(2) = -(2)^2 + 4(2) - 3$.',
            'Étape 2 : Effectue les puissances et les produits : $-(4) + 8 - 3$.',
            'Étape 3 : Calcule la somme finale : $-4 + 8 = 4$, et $4 - 3 = 1$.',
          ],
          reponse: '1',
          conseil: 'Fais attention, le signe moins est extérieur au carré : $-(2)^2 = -4$, et non $+4$.',
        },
        {
          type: 'text',
          id: 'b17-transition',
          contenu: "Maintenant que nous savons chasser les sommets, appliquons cette compétence à la résolution de problèmes concrets de la vie réelle : c'est l'optimisation.",
        },
      ],
    },
    {
      id: 's4',
      titre: '4.3 Problèmes d\'Optimisation — Rendre Rentable le Quotidien',
      blocs: [
        {
          type: 'text',
          id: 'b18-accroche',
          contenu: 'Marre des maths abstraites ? Découvre comment les commerçants d\'Adjamé et les planteurs de Bouaké utilisent inconsciemment les dérivées pour amasser un max de gains.',
        },
        {
          type: 'text',
          id: 'b18',
          contenu: "C'est ici que les mathématiques rencontrent la vie réelle. Les ingénieurs, les commerçants et les économistes utilisent les dérivées tous les jours pour \"optimiser\". Optimiser, c'est chercher à rendre un bénéfice le plus grand possible (maximum), ou un coût le plus petit possible (minimum).",
        },
        {
          type: 'recap',
          id: 'b19-methode-optimisation',
          titre: 'Problème d\'optimisation (LA MÉTHODE UNIVERSELLE)',
          contenu: [
            '1️⃣ ÉTAPE 1 : Identifier ce qu\'on veut maximiser ou minimiser. (Aire ? Volume ? Coût ? Bénéfice ?). Appelle cette grandeur f(x).',
            '2️⃣ ÉTAPE 2 : Trouver la contrainte fixée par l\'énoncé (un budget maximum, une longueur de grillage fixe, etc.).',
            '3️⃣ ÉTAPE 3 : Mettre en équation f(x). Exprime la grandeur en fonction d\'une seule variable x en exploitant la contrainte.',
            '4️⃣ ÉTAPE 4 : Dériver et chercher f\'(x) = 0. Trouve la valeur critique de x qui annule la dérivée.',
            '5️⃣ ÉTAPE 5 : Vérifier et conclure. Valide avec un tableau de signes qu\'il s\'agit du bon extremum et fais une phrase de conclusion.',
          ],
        },
        {
          type: 'analogy',
          id: 'b20-analogie-marche',
          titre: 'L\'ANALOGIE DU MARCHÉ D\'ADJAMÉ (La Négociation)',
          contenu: "Imagine que tu vends des jeans au Forum d'Adjamé. Tu veux faire le maximum de bénéfices.\n• Si tu fixes le prix très bas (500 FCFA), tu vas vendre des milliers de jeans, mais ton bénéfice par jean sera ridicule (proche de zéro).\n• Si tu fixes le prix trop haut (50 000 FCFA), ton bénéfice par jean sera énorme, mais aucun client ne viendra l'acheter. Résultat : bénéfice total égal à zéro.\nTa courbe de bénéfice a une forme de cloche (une parabole inversée).",
          conceptMath: "Il existe un prix PARFAIT, ni trop haut ni trop bas, qui te donne le sommet absolu de la richesse. C'est le point exact où la dérivée de ta fonction bénéfice s'annule en changeant de signe !",
        },
        {
          type: 'dialogue',
          id: 'b21-dialogue-optimisation',
          pf: "Vieux père, la méthode des 5 étapes a l'air sympa sur le papier, mais face à une copie de devoir, je n'arrive jamais à trouver la fameuse fonction f(x) au départ. Je bloque à l'étape 3 !",
          gf: "C'est normal, c'est là qu'est le vrai travail mathématique. Le secret, c'est le brouillon. Fais un schéma ! Donne un nom aux choses. Appelle la largeur x et la longueur y. Tu sais que tu veux maximiser l'aire, donc ton but c'est x × y. Mais comme tu ne sais dériver qu'avec une seule lettre, tu dois utiliser l'indice de l'énoncé (le grillage ou périmètre fixe) pour exprimer y en fonction de x. Dès que tu as ça, tu remplaces, et bam ! Tu as ta fonction f(x) prête à être dérivée.",
        },
        {
          type: 'text',
          id: 'b22',
          contenu: "Étudions 5 cas d'école entièrement résolus :",
        },
        {
          type: 'text',
          id: 'b23-les-5-exercices-opt',
          contenu: "• Exercice 1 : Aire maximale avec contrainte. Un paysan de Bouaké veut enclore un champ rectangulaire le long d'un mur rectiligne (il n'a pas besoin de grillage le long du mur). Il possède 100 mètres de grillage. Quelles dimensions choisir pour que l'aire soit maximale ?\n  - Étape 1 & 2 : Soit $x$ la largeur et $y$ la longueur parallèle au mur. Le grillage total vaut $x + y + x = 2x + y = 100 \\implies y = 100 - 2x$.\n  - Étape 3 : L'aire est $A(x) = x \\times y = x(100 - 2x) = 100x - 2x^2$, avec $x \\in [0; 50]$.\n  - Étape 4 : On dérive : $A'(x) = 100 - 4x$. On annule : $100 - 4x = 0 \\implies x = 25$.\n  - Étape 5 : $A'(x)$ est positive pour $x < 25$ et négative pour $x > 25$ : c'est un maximum. Conclusion : Il faut une largeur de 25m et une longueur de $y = 100 - 2(25) = 50$m. L'aire maximale vaut $1250$ m².\n\n• Exercice 2 : Le bénéfice maximal de l'usine de cacao. Le bénéfice journalier en millions de FCFA pour la production de $x$ milliers de sachets est modélisé sur $[1 ; 5]$ par $B(x) = -\\frac{1}{3}x^3 + 9x + 2$. Combien de sachets produire pour maximiser les gains ?\n  - Étape 1 & 3 : La fonction est donnée : $B(x) = -\\frac{1}{3}x^3 + 9x + 2$.\n  - Étape 4 : On dérive : $B'(x) = -x^2 + 9$. On annule : $-x^2 + 9 = 0 \\implies x^2 = 9 \\implies x = 3$ sur $[1; 5]$.\n  - Étape 5 : $B'(x) > 0$ sur $[1; 3]$ et $B'(x) < 0$ sur $[3; 5]$. Le maximum est atteint en 3.\nConclusion : Il faut produire 3 milliers (soit 3000) sachets pour un gain maximal de $B(3) = -\\frac{1}{3}(27) + 9(3) + 2 = -9 + 27 + 2 = 20$ millions de FCFA.\n\n• Exercice 3 : Coût minimal de fabrication. Une entreprise veut fabriquer une cuve cylindrique ouverte en haut d'un volume de 1 m³. Elle cherche à minimiser la surface de tôle utilisée.\n  - Contrainte : Volume $V = \\pi r^2 h = 1 \\implies h = \\frac{1}{\\pi r^2}$.\n  - Fonction Surface : $S = \\pi r^2 + 2\\pi rh = \\pi r^2 + 2\\pi r(\\frac{1}{\\pi r^2}) = \\pi r^2 + \\frac{2}{r}$.\n  - Dérivation : $S'(r) = 2\\pi r - \\frac{2}{r^2} = \\frac{2\\pi r^3 - 2}{r^2}$.\n  - Annulation : $2\\pi r^3 - 2 = 0 \\implies r^3 = \\frac{1}{\\pi} \\implies r = (\\frac{1}{\\pi})^{1/3} \\approx 0,68$ m. On trouve $h = r \\approx 0,68$ m. La surface minimale vaut environ $1,39$ m².\n\n• Exercice 4 : La boîte sans couvercle (Volume maximal). On dispose d'un carton carré de 20 cm de côté. On découpe des petits carrés de côté $x$ aux quatre coins pour faire une boîte ouverte. Quel doit être $x$ ?\n  - Équation : La base aura pour côté $(20 - 2x)$ et la hauteur sera $x$. Le volume est $V(x) = x(20 - 2x)^2 = 4x^3 - 80x^2 + 400x$, avec $x \\in ]0; 10[$.\n  - Dérivation : $V'(x) = 12x^2 - 160x + 400$. On simplifie par 4 pour annuler : $3x^2 - 40x + 100 = 0$.\n  - Résolution : $\\Delta = 400$, les racines sont $x_1 = \\frac{10}{3}$ et $x_2 = 10$. Sur $]0; 10[$, seule $x = \\frac{10}{3}$ cm (environ 3,33 cm) convient et donne le volume maximal.\n\n• Exercice 5 : Distance minimale d'un point à une courbe. Trouver le point M de la courbe $y = \\sqrt{x}$ le plus proche du point $A(2; 0)$.\n  - Équation : Soit $M(x, \\sqrt{x})$. La distance $AM$ au carré est $f(x) = (x-2)^2 + (\\sqrt{x}-0)^2 = x^2 - 4x + 4 + x = x^2 - 3x + 4$.\n  - Dérivation : $f'(x) = 2x - 3$. On annule : $2x - 3 = 0 \\implies x = 1,5$.\nConclusion : Le point le plus proche est $M(1,5; \\sqrt{1,5})$.",
        },
        {
          type: 'text',
          id: 'b24-transition',
          contenu: "L'optimisation n'a plus de secrets pour toi. Revenons à la géométrie de la courbe pour fixer la formule incontournable du coefficient directeur : la tangente.",
        },
      ],
    },
    {
      id: 's5',
      titre: '4.4 La Tangente à une Courbe — Protocole d\'Application',
      blocs: [
        {
          type: 'text',
          id: 'b25-accroche',
          contenu: 'Rappel de la règle d\'or de la tangente. Voyons comment gérer les cas classiques et le piège des tangentes horizontales ou parallèles.',
        },
        {
          type: 'rule',
          id: 'b25-tangente-formule-rappel',
          titre: '📌 RÈGLE D\'OR : ÉQUATION DE LA TANGENTE',
          contenu: [
            'L\'équation de la tangente (T) à la courbe de f au point d\'abscisse x₀ est :',
            '$$y = f\'(x_0)(x - x_0) + f(x_0)$$',
          ],
        },
        {
          type: 'text',
          id: 'b26',
          contenu: "Étudions 3 exercices types du BAC :\n\n• Exercice 1 : Fonction Polynôme. Soit $f(x) = x^2 - 5x + 4$. Déterminer l'équation de la tangente au point $x_0 = 3$.\n  1. Image : $f(3) = 3^2 - 5(3) + 4 = -2$.\n  2. Dérivée : $f'(x) = 2x - 5 \\implies f'(3) = 2(3) - 5 = 1$.\n  3. Équation : $y = 1(x - 3) + (-2) \\implies y = x - 5$.\n\n• Exercice 2 : Fonction Homographique. Soit $g(x) = \\frac{2x}{x+1}$. Trouver la tangente au point $x_0 = 0$.\n  1. Image : $g(0) = 0$.\n  2. Dérivée : $g'(x) = \\frac{2(x+1) - 2x(1)}{(x+1)^2} = \\frac{2}{(x+1)^2} \\implies g'(0) = 2$.\n  3. Équation : $y = 2(x - 0) + 0 \\implies y = 2x$.\n\n• Exercice 3 : Tangente horizontale. Soit $h(x) = x^3 - 3x$. Existe-t-il des points où la tangente est parallèle à l'axe des abscisses ?\n  - Explication : Droite horizontale $\\implies$ pente égale à 0. On cherche donc où $h'(x) = 0$.\n  - Calcul : $h'(x) = 3x^2 - 3 = 0 \\implies x^2 = 1 \\implies x = 1$ ou $x = -1$.\nConclusion : Oui, aux points d'abscisses $1$ et $-1$, la courbe admet des tangentes horizontales.",
        },
        {
          type: 'text',
          id: 'b27-transition',
          contenu: "Tes armes sont parfaitement aiguisées. Il est temps de monter sur le ring. Attaquons le Marathon du BAC : 10 exercices progressifs complets pour faire de toi un major.",
        },
      ],
    },
    {
      id: 's6',
      titre: '4.5 Le Marathon du BAC — 10 Exercices Progressifs Résolus',
      blocs: [
        {
          type: 'text',
          id: 'b28-accroche',
          contenu: 'Ne fuis pas devant l\'effort, champion(ne). Prends ton cahier de brouillon, affronte ces 10 sujets types un par un, et découvre le corrigé militaire du Grand Frère.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex1',
          niveau: 'BASE',
          enonce: '🟩 EXERCICE 1 : Variations d\'un polynôme de degré 3. On donne $f(x) = 2x^3 - 3x^2 - 12x + 1$ sur $\\mathbb{R}$.\n1. Calculer la fonction dérivée $f\'(x)$.\n2. Dresser le tableau de variations complet de $f$.',
          etapes: [
            'Étape 1 : Dérive terme à terme : $f\'(x) = 6x^2 - 6x - 12$. Factorise par 6 : $6(x^2 - x - 2) = 6(x + 1)(x - 2)$.',
            'Étape 2 : Cherche les racines du numérateur : $x^2 - x - 2 = 0 \\implies \\Delta = 9$. Les racines sont $x = -1$ et $x = 2$.',
            'Étape 3 : Applique le signe de $a = 6 > 0$ : positif à l\'extérieur des racines, négatif entre $-1$ et $2$.',
            'Étape 4 : Calcule les images stratégiques : $f(-1) = 8$ (Maximum) et $f(2) = -19$ (Minimum). Les limites en $-\\infty$ vaut $-\\infty$ et en $+\\infty$ vaut $+\\infty$.',
            'Étape 5 : Assemble le tableau : la fonction monte de $-\\infty$ à 8, descend de 8 à $-19$, puis remonte vers $+\\infty$.',
          ],
          reponse: '6(x+1)(x-2)',
          conseil: 'La factorisation initiale par le coefficient commun simplifie énormément la recherche des racines.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex2',
          niveau: 'BASE',
          enonce: '🟩 EXERCICE 2 : Lecture de la dérivée. Une fonction $g$ admet le tableau de signes de dérivée suivant : $g\'(x) < 0$ sur $]-\\infty; 3[$ et $g\'(x) > 0$ sur $]3; +\\infty[$. Que peut-on en déduire pour le point d\'abscisse 3 ?',
          etapes: [
            'Étape 1 : Observe le comportement de la dérivée : elle s\'annule au point $x = 3$.',
            'Étape 2 : Regarde le changement de signe : elle passe de négatif (−) à positif (+).',
            'Étape 3 : Conclus sur la trajectoire : la courbe descend puis remonte. Elle atteint donc un minimum local.',
          ],
          reponse: 'Minimum local',
          conseil: 'Une dérivée qui change de signe en s\'annulant est la signature obligatoire d\'un extremum.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex3',
          niveau: 'MOYEN',
          enonce: '🟨 EXERCICE 3 : Dérivée d\'une fraction rationnelle. Soit $h(x) = \\frac{x^2-2x+5}{x-1}$ définie sur $\\mathbb{R} \\setminus \\{1\\}$.\n1. Démontrer que $h\'(x) = \\frac{x^2-2x-3}{(x-1)^2}$.\n2. En déduire les variations complètes de $h$.',
          etapes: [
            'Étape 1 : Applique la formule du quotient avec $u = x^2-2x+5 \\implies u\'=2x-2$ et $v=x-1 \\implies v\'=1$.',
            'Étape 2 : Développe le numérateur : $(2x-2)(x-1) - (x^2-2x+5) = 2x^2 - 4x + 2 - x^2 + 2x - 5 = x^2 - 2x - 3$. La formule est démontrée !',
            'Étape 3 : Étudie le signe. Le bas $(x-1)^2$ est positif. Le haut $x^2-2x-3$ a pour racines $x = -1$ et $x = 3$ ($\\Delta = 16$).',
            'Étape 4 : Signe de a (1 > 0) positif aux bornes. Dérivée positive sur $]-\\infty; -1[ \\cup ]3; +\\infty[$ et négative entre.',
            'Étape 5 : Calcule les images : $h(-1) = -4$ (Maximum local) et $h(3) = 4$ (Minimum local). Attention à couper le tableau à la valeur interdite 1 (double barre ‖).',
          ],
          reponse: '\\frac{x^2-2x-3}{(x-1)^2}',
          conseil: 'Pour les fractions rationnelles, n\'oublie jamais de marquer la valeur interdite par une double barre ‖ dans ton tableau.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex4',
          niveau: 'MOYEN',
          enonce: '🟨 EXERCICE 4 : Tangente parallèle à une droite. Soit $f(x) = x^2 + 3x - 1$. Existe-t-il un point de la courbe où la tangente est parallèle à la droite d\'équation $y = 5x + 2$ ?',
          etapes: [
            'Étape 1 : Traduis la contrainte géométrique : deux droites parallèles possèdent le même coefficient directeur. La pente imposée vaut donc 5.',
            'Étape 2 : Rappelle que la pente de la tangente est donnée par la dérivée : on doit donc résoudre $f\'(x) = 5$.',
            'Étape 3 : Calcule la dérivée : $f\'(x) = 2x + 3$.',
            'Étape 4 : Résous l\'équation linéaire : $2x + 3 = 5 \\implies 2x = 2 \\implies x = 1$.',
          ],
          reponse: '1',
          conseil: 'Le parallélisme impose d\'égaler la fonction dérivée au coefficient directeur de la droite repère.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex5',
          niveau: 'MOYEN',
          enonce: '🟨 EXERCICE 5 : Trouver des paramètres a et b. Soit $f(x) = ax^2 + bx + 3$. On sait que la courbe passe par le point $A(1 ; 6)$ et admet en ce point une tangente horizontale. Détermine a et b.',
          etapes: [
            'Étape 1 : Traduis l\'appartenance du point : $f(1) = 6 \\implies a(1)^2 + b(1) + 3 = 6 \\implies a + b = 3$ (Équation 1).',
            'Étape 2 : Traduis la tangente horizontale : la pente est nulle au point 1, donc $f\'(1) = 0$.',
            'Étape 3 : Calcule la dérivée générale : $f\'(x) = 2ax + b \\implies f\'(1) = 2a + b = 0$ (Équation 2).',
            'Étape 4 : Résous le système : de l\'Eq 1 on tire $b = 3 - a$. Remplace dans l\'Eq 2 : $2a + (3 - a) = 0 \\implies a + 3 = 0 \\implies a = -3$.',
            'Étape 5 : Déduis la valeur de b : $b = 3 - (-3) = 6$. La fonction est $f(x) = -3x^2 + 6x + 3$.',
          ],
          reponse: 'a = -3, b = 6',
          conseil: 'Une tangente horizontale se traduit toujours mathématiquement par l\'équation f\'(x₀) = 0.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex5bis',
          niveau: 'MOYEN',
          enonce: '🟨 EXERCICE 5 (bis) : Dérivée et inéquation. Soit $f(x) = x^3 - 6x^2 + 9x + 1$.\n1. Calculer $f\'(x)$ et résoudre $f\'(x) \\ge 0$.\n2. Dresser le tableau de variations complet de $f$ et en déduire ses extremums.',
          etapes: [
            'Étape 1 : Calcule la dérivée : $f\'(x) = 3x^2 - 12x + 9 = 3(x^2 - 4x + 3) = 3(x - 1)(x - 3)$.',
            'Étape 2 : Résous $f\'(x) \\ge 0$. Le polynôme est positif à l\'extérieur des racines 1 et 3 (car $a = 3 > 0$). Donc $f\'(x) \\ge 0$ sur $]-\\infty ; 1] \\cup [3 ; +\\infty[$.',
            'Étape 3 : Calcule les points de rebroussement : $f(1) = 5$ (Maximum local) et $f(3) = 1$ (Minimum local).',
            'Étape 4 : Dessine le tableau : la courbe monte de $-\\infty$ à 5, descend de 5 à 1, puis remonte vers $+\\infty$.',
          ],
          reponse: '3(x-1)(x-3)',
          conseil: 'L\'étude de l\'inéquation donne directement le sens des flèches de ton tableau de variations.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex6',
          niveau: 'BAC',
          enonce: '🟥 EXERCICE 6 : Dérivée avec racine carrée. Soit $f(x) = \\sqrt{x^2 + 4}$. Calculer $f\'(x)$ et étudier son signe sur $\\mathbb{R}$.',
          etapes: [
            'Étape 1 : Applique la formule de composition $(\\sqrt{u})\' = \\frac{u\'}{2\\sqrt{u}}$ avec $u = x^2 + 4 \\implies u\' = 2x$.',
            'Étape 2 : Assemble l\'expression : $f\'(x) = \\frac{2x}{2\\sqrt{x^2 + 4}} = \\frac{x}{\\sqrt{x^2 + 4}}$.',
            'Étape 3 : Analyse le signe : le dénominateur est une racine carrée réelle, donc strictement positive. Le signe dépend uniquement du haut, $x$.',
            'Étape 4 : Établis les variations : négatif pour $x < 0$ (décroissant) et positif pour $x > 0$ (croissant). Le minimum est atteint en 0, de hauteur $f(0) = \\sqrt{4} = 2$.',
          ],
          reponse: '\\frac{x}{\\sqrt{x^2 + 4}}',
          conseil: 'Une racine carrée réelle étant positive, tu peux l\'ignorer pour l\'étude du signe de ta fraction.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex7',
          niveau: 'BAC',
          enonce: '🟥 EXERCICE 7 : Démonstration d\'inégalité. Montrer que pour tout $x \\ge 0$, on a l\'inrelation suivante : $x^3 + 2 \\ge 3x$.',
          etapes: [
            'Étape 1 : Bascule tous les termes du même côté pour créer une fonction différence : $h(x) = x^3 - 3x + 2$. On doit prouver que $h(x) \\ge 0$ sur $[0; +\\infty[$.',
            'Étape 2 : Dérive pour étudier les variations : $h\'(x) = 3x^2 - 3 = 3(x^2 - 1) = 3(x - 1)(x + 1)$.',
            'Étape 3 : Sur $[0; +\\infty[$, la seule racine utile est $x = 1$. La dérivée est négative sur $[0; 1[$ et positive sur $]1; +\\infty[$.',
            'Étape 4 : Détermine le point le plus bas (le minimum) : $h(1) = 1^3 - 3(1) + 2 = 0$.',
            'Étape 5 : Conclus : puisque le minimum absolu sur cet intervalle est 0, la fonction $h(x)$ est toujours supérieure ou égale à 0. Donc $x^3 + 2 \\ge 3x$.',
          ],
          reponse: '0',
          conseil: 'Pour démontrer une inégalité complexe au BAC, crée toujours une fonction différence et cherche son minimum.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex8',
          niveau: 'BAC',
          enonce: '🟥 EXERCICE 8 : Composée avec exponentielle. Soit $f(x) = (2x + 1)e^x$. Calculer $f\'(x)$ et dresser son tableau de variations complet.',
          etapes: [
            'Étape 1 : Applique la formule du produit $(uv)\' = u\'v + uv\'$ avec $u = 2x + 1 \\implies u\' = 2$ and $v = e^x \\implies v\' = e^x$.',
            'Étape 2 : Développe l\'assemblage : $f\'(x) = 2e^x + (2x + 1)e^x$. Factorise par le pivot : $f\'(x) = e^x[2 + (2x + 1)] = e^x(2x + 3)$.',
            'Étape 3 : Étudie le signe : $e^x$ étant toujours strictement positif, le signe est uniquement celui de $2x + 3$. Elle s\'annule pour $x = -3/2$.',
            'Étape 4 : Calcule la valeur du creux : $f(-3/2) = (2(-3/2) + 1)e^{-3/2} = -2e^{-3/2} \\approx -0,45$. La limite en $-\\infty$ vaut 0 (croissances comparées) et en $+\\infty$ vaut $+\\infty$.',
            'Étape 5 : Trace le tableau : la courbe descend de 0 jusqu\'au minimum $-2e^{-3/2}$ puis remonte vers $+\\infty$.',
          ],
          reponse: 'e^x(2x + 3)',
          conseil: 'Point de vigilance : factorise TOUJOURS par l\'exponentielle. Comme elle est strictement positive, elle s\'efface lors de l\'étude du signe.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex9',
          niveau: 'BAC',
          enonce: '🟥 EXERCICE 9 : Position d\'une courbe par rapport à sa tangente. Soit $f(x) = x^2$ et (T) sa tangente au point $x_0 = 1$. Étudier la position relative de la courbe par rapport à (T).',
          etapes: [
            'Étape 1 : Trouve l\'équation de la tangente : $f(1) = 1$, $f\'(1) = 2 \\times 1 = 2$. (T) : $y = 2(x - 1) + 1 = 2x - 1$.',
            'Étape 2 : Forme la fonction différence : $d(x) = f(x) - y_{tangente} = x^2 - (2x - 1) = x^2 - 2x + 1$.',
            'Étape 3 : Repère l\'identité remarquable cachée : $d(x) = (x - 1)^2$.',
            'Étape 4 : Déduis le signe : un carré parfait est toujours supérieur ou inférieur à zéro ? Toujours supérieur ou égal à 0 !',
            'Étape 5 : Conclus géométriquement : puisque $d(x) \\ge 0$, la courbe se situe toujours au-dessus de sa tangente (T).',
          ],
          reponse: '(x - 1)^2',
          conseil: 'Étudier la position relative revient à étudier le signe de la différence entre la courbe et la droite repère.',
        },
        {
          type: 'exercise',
          id: 'marathon-ex10',
          niveau: 'BAC',
          enonce: '🟥 EXERCICE 10 : Optimisation d\'enclos accolés. Un éleveur veut construire deux enclos rectangulaires identiques accolés par un côté commun. Il dispose de 60m de grillage au total. Démontre que l\'aire maximale qu\'il peut obtenir est de 150 m².',
          etapes: [
            'Étape 1 (Mise en équation) : Fais un schéma. Soit x la largeur (3 segments verticaux identiques) et y la longueur (2 segments horizontaux). La contrainte de grillage est $3x + 2y = 60 \\implies y = 30 - 1,5x$.',
            'Étape 2 (Fonction) : L\'aire totale vaut $A(x) = x \\times y = x(30 - 1,5x) = 30x - 1,5x^2$, avec $x \\in ]0; 20[$.',
            'Étape 3 (Dériver) : Calcule la dérivée : $A\'(x) = 30 - 3x$. On cherche l\'annulation : $30 - 3x = 0 \\implies 3x = 30 \\implies x = 10$ m.',
            'Étape 4 (Vérifier) : $A\'(x) > 0$ pour $x < 10$ (croissant) et $A\'(x) < 0$ for $x > 10$ (décroissant). C\'est bien un maximum absolu.',
            'Étape 5 (Calculer) : Calcule la hauteur maximale : $A(10) = 30(10) - 1,5(10)^2 = 300 - 150 = 150$ m². Le contrat est rempli !',
          ],
          reponse: '150',
          conseil: 'N\'oublie pas de compter le grillage de séparation centrale intermédiaire dans ta contrainte de départ !',
        },
        {
          type: 'recap',
          id: 'b29-bilan-marathon',
          titre: '🏁 BILAN DE FIN DU MARATHON',
          contenu: [
            '🚀 Exercices 1 et 2 (BASE) : Si tu les as validés, tes bases techniques de variations sont en béton armé.',
            '🚀 Exercices 3 à 5 (MOYEN) : Si tu les gères, tu es assuré d\'obtenir la moyenne sur les problèmes d\'analyse au BAC.',
            '🚀 Exercices 6 à 10 (DIFFICILE) : Si tu maîtrises ces cas, tu as le niveau des caïmans du Cacao, tu vises la mention !',
            'Si tu as buté sur certaines étapes, prends une pause, bois ton eau sous l\'apatam, revois le chapitre 3 et réessaie tranquillement. On avance ensemble !',
          ],
        },
      ],
    },
  ],
  quiz: [
    {
      type: 'quiz',
      id: 'q1',
      question: 'Quelles sont les deux conditions obligatoires pour qu\'un point x₀ soit un extremum local d\'une courbe ?',
      options: [
        'La dérivée doit être positive et l\'image doit valoir 0',
        'La dérivée f\'(x₀) doit s\'annuler ET changer de signe autour de x₀',
        'La fonction doit être continue et croissante',
        'La limite en l\'infini doit donner un nombre réel fini',
      ],
      bonneReponse: 1,
      explication: 'Pour former un sommet ou un creux, la pente doit s\'aplanir (f\'(x₀)=0) ET changer de direction (passer de montée à descente, ou de descente à montée). Sans changement de signe, c\'est un simple palier (point d\'inflexion).',
    },
    {
      type: 'quiz',
      id: 'q2',
      question: 'Dans l\'analogie du vendeur de jeans du Forum d\'Adjamé, pourquoi le bénéfice maximal forme-t-il une cloche ?',
      options: [
        'Parce que le prix du tissu augmente toujours avec le temps',
        'Parce qu\'un prix trop bas ne rapporte rien et un prix trop haut fait fuir tous les clients : il existe un juste milieu optimal où la dérivée s\'annule',
        'Parce que les clients négocient de la même façon le matin et le soir',
        'Parce que la tontine d\'Abobo impose un prix fixe journalier',
      ],
      bonneReponse: 1,
      explication: 'L\'optimisation cherche le point d\'équilibre parfait. Aux deux extrémités (prix nul ou clients nuls), le gain est de zéro. Le sommet de la cloche correspond à l\'annulation de la dérivée du bénéfice.',
    },
    {
      type: 'quiz',
      id: 'q3',
      question: 'Quelle est la règle absolue de simplification concernant le dénominateur lors de l\'étude de variations d\'un quotient ?',
      options: [
        'Il faut le développer le plus vite possible avec les identités remarquables',
        'ON NE LE DÉVELOPPE JAMAIS s\'il est déjà au carré, car un carré est positif et son signe n\'influence pas les variations',
        'Il faut l\'annuler et le remplacer par 1',
        'Il faut en prendre la racine carrée',
      ],
      bonneReponse: 1,
      explication: 'Le dénominateur d\'une dérivée de quotient est un carré $(v^2)$. Un carré étant toujours strictement positif sur son domaine, il n\'altère pas le signe global. Le développer est une perte de temps et une source d\'erreurs.',
    },
    {
      type: 'quiz',
      id: 'q4',
      question: 'Si deux droites sont parallèles sur un graphique, quelle est la relation entre leurs coefficients directeurs ?',
      options: [
        'Ils sont opposés (l\'un est le négatif de l\'autre)',
        'Leur produit est égal à 1',
        'Ils sont strictement égaux (ils ont la même pente)',
        'Leur somme est toujours égale à 0',
      ],
      bonneReponse: 2,
      explication: 'Le parallélisme signifie que deux droites possèdent exactement la même inclinaison. Leurs pentes (ou coefficients directeurs) sont donc strictement égales.',
    },
    {
      type: 'quiz',
      id: 'q5',
      question: 'Que signifie géométriquement la conclusion de l\'exercice 9 : $d(x) = (x - 1)^2 \\ge 0$ ?',
      options: [
        'La courbe traverse la tangente au point 1',
        'La courbe est toujours située au-dessus de sa tangente (T)',
        'La tangente est verticale',
        'La fonction n\'est pas continue sur cet intervalle',
      ],
      bonneReponse: 1,
      explication: 'Puisque la différence entre les ordonnées de la courbe et de la droite est toujours positive ou nulle ($d(x) \\ge 0$), la courbe de la parabole se situe constamment au-dessus de sa tangente.',
    },
  ],
};