// src/data/t2-derivees/chap4.ts
import { Chapitre } from '../../types/course';

export const chapitre3: Chapitre = {
  id: 't2-chap4',
  titre: 'Calculer les Dérivées — La Méthode',
  duree: 40,
  niveau: 'MOYEN',
  xpGain: 75,
  gratuit: false,
  objectifs: [
    'Connaître sur le bout des doigts le tableau des dérivées usuelles',
    'Maîtriser les 5 formules d\'opérations (somme, produit, quotient, composée)',
    'Appliquer le Process EDUCTOME en 5 étapes pour sécuriser tes calculs',
    'Éviter le piège classique des constantes déguisées et des fractions simples',
    'Résoudre avec succès les 10 exercices fondamentaux de niveau BASE',
  ],
  sections: [
    {
      id: 's1',
      titre: 'Introduction — La recette du Garba',
      blocs: [
        {
          type: 'text',
          id: 'b1-accroche',
          contenu: 'Champion(ne), oublie les calculs interminables de limites ! Bienvenue dans l\'atelier des raccourcis mathématiques où dériver devient aussi mécanique que de rouler un bon garba.',
        },
        {
          type: 'text',
          id: 'b1',
          contenu: "Champion(ne), prends une grande inspiration. Ce que nous allons voir aujourd'hui, c'est le cœur du réacteur.",
        },
        {
          type: 'text',
          id: 'b2',
          contenu: "📖 L'ANECDOTE DU GRAND FRÈRE :\nQuand j'étais en classe de Terminale au Lycée Classique d'Abidjan, j'avais un ami qu'on appelait \"le magicien des dérivées\". À chaque devoir, pendant que nous autres transpirions à grosses gouttes sur nos feuilles de brouillon, lui, il finissait la première partie de l'épreuve en quinze minutes chrono. Un jour, sous l'apatam, je lui ai demandé son secret. Il a souri et m'a dit : \"Vieux père, il n'y a pas de magie. Le calcul des dérivées, c'est exactement comme préparer un bon garba. Tu dois juste connaître tes ingrédients (les formules de base) et suivre la recette étape par étape (les opérations), sans jamais brûler les étapes\". Ce jour-là, j'ai compris que la dérivation n'était pas une question d'intelligence supérieure, mais de méthode et de rigueur.",
        },
        {
          type: 'text',
          id: 'b3',
          contenu: "Dans le Chapitre 2, on s'est concentré sur la philosophie. Tu as compris le concept, maintenant on apprend à CALCULER. Fini les longues limites du taux d'accroissement qui prennent une page entière. Les mathématiciens ont créé des \"raccourcis\" puissants : les formules de dérivation. Si tu maîtrises ce chapitre, tu as la clé pour déverrouiller plus de 60% des points du problème d'analyse au BAC. On y va !",
        },
        {
          type: 'text',
          id: 'b4-transition',
          contenu: 'Ouvrons tout de suite le catalogue des formules de base : tes ingrédients fondamentaux pour toute l\'année.',
        },
      ],
    },
    {
      id: 's2',
      titre: '3.1 Le Tableau des Dérivées Usuelles',
      blocs: [
        {
          type: 'text',
          id: 'b5-accroche',
          contenu: 'Voici tes briques élémentaires. Ne cherche pas à les deviner, elles doivent devenir des réflexes automatiques, comme taper ton code de déverrouillage.',
        },
        {
          type: 'text',
          id: 'b5',
          contenu: "Voici tes \"ingrédients de base\". Ces formules sont intouchables. Tu ne dois pas essayer de les deviner, tu dois les connaître par cœur, comme ton propre numéro de téléphone. C'est la fondation de tout ton travail de l'année.",
        },
        {
          type: 'table',
          id: 'b6-table-usuelles',
          titre: 'Formules de dérivation usuelles',
          headers: ['Fonction $f(x)$', 'Dérivée $f\'(x)$', 'Condition d\'existence'],
          rows: [
            ['$k$ (constante)', '$0$', '$x \\in \\mathbb{R}$'],
            ['$x$', '$1$', '$x \\in \\mathbb{R}$'],
            ['$x^n$', '$nx^{n-1}$', '$x \\in \\mathbb{R}$'],
            ['$\\frac{1}{x}$', '$-\\frac{1}{x^2}$', '$x \\neq 0$'],
            ['$\\sqrt{x}$', '$\\frac{1}{2\\sqrt{x}}$', '$x > 0$'],
            ['$e^x$', '$e^x$', '$x \\in \\mathbb{R}$'],
            ['$\\ln(x)$', '$\\frac{1}{x}$', '$x > 0$'],
            ['$\\sin(x)$', '$\\cos(x)$', '$x \\in \\mathbb{R}$'],
            ['$\\cos(x)$', '$-\\sin(x)$', '$x \\in \\mathbb{R}$'],
          ],
        },
        {
          type: 'warning',
          id: 'b7-warning-constante',
          contenu: "⚠️ PIÈGE À ÉVITER : La fausse constante\nBeaucoup d'élèves pensent que si un nombre possède une forme bizarre, c'est forcément une fonction variable. C'est faux ! $\\ln(2)$, $e^3$, $\\sqrt{5}$, ou $\\pi$ sont des CONSTANTES. Si on te demande de dériver $f(x) = \\ln(2)$, la réponse est $f'(x) = 0$. Ne te fais pas avoir par le déguisement !",
        },
        {
          type: 'text',
          id: 'b8',
          contenu: "Observons 5 exemples d'application directe immédiate :\n\n1. Si $f(x) = 1500$, alors $f'(x) = 0$ (Règle de la constante).\n2. Si $f(x) = x^4$, alors $f'(x) = 4x^{4-1} = 4x^3$ (Règle de $x^n$).\n3. Si $f(x) = x^{10}$, alors $f'(x) = 10x^9$.\n4. Si $f(x) = e^x$, alors $f'(x) = e^x$ (C'est la seule fonction égale à sa propre dérivée, un vrai roc !).\n5. Si $f(x) = \\ln(x)$, alors $f'(x) = \\frac{1}{x}$ (Indispensable pour l'étude des fonctions logarithmes).",
        },
        {
          type: 'exercise',
          id: 'micro-ex-usuelles',
          niveau: 'BASE',
          enonce: 'À toi de jouer ! Calcule la dérivée de la fonction constante suivante : $f(x) = e^5 + \\sqrt{3}$',
          etapes: [
            'Étape 1 : Observe s\'il y a une variable x dans l\'expression de f(x).',
            'Étape 2 : Constate que $e^5$ et $\\sqrt{3}$ sont de simples nombres fixes.',
            'Étape 3 : Applique la règle de la constante : la dérivée d\'un nombre fixe vaut $0$.',
          ],
          reponse: '0',
          conseil: 'Pas de x, pas de mouvement, donc la pente vaut strictement 0 !',
        },
        {
          type: 'text',
          id: 'b9-transition',
          contenu: 'Savoir utiliser les blocs isolés est un bon début. Voyons maintenant les règles d\'assemblage pour combiner ces ingrédients.',
        },
      ],
    },
    {
      id: 's3',
      titre: '3.2 Opérations sur les Dérivées — Somme, Produit et Quotient',
      blocs: [
        {
          type: 'text',
          id: 'b10-accroche',
          contenu: 'Savoir mélanger tes ingrédients est indispensable. Découvrons comment dériver une somme, un produit par une constante, et le fameux produit croisé.',
        },
        {
          type: 'text',
          id: 'b10',
          contenu: "Avoir les ingrédients, c'est bien. Savoir les mélanger, c'est mieux. Voici les règles (les opérations) qui te permettront de dériver n'importe quelle fonction complexe.",
        },
        {
          type: 'rule',
          id: 'b11-formule-somme',
          titre: 'A. DÉRIVÉE D\'UNE SOMME',
          contenu: [
            'Formula : $$(u + v)\' = u\' + v\'$$',
            'C\'est la règle la plus simple. Si tu as plusieurs blocs séparés par des plus (+) ou des moins (−), tu dérives chaque bloc tranquillement de son côté.',
            'Exemple : $f(x) = x^3 + e^x$. Tu dérives $x^3$ (ça fait $3x^2$) et tu dérives $e^x$ (ça fait $e^x$). Résultat : $f\'(x) = 3x^2 + e^x$.',
          ],
        },
        {
          type: 'rule',
          id: 'b12-formule-produit-constante',
          titre: 'B. DÉRIVÉE D\'UN PRODUIT PAR UNE CONSTANTE',
          contenu: [
            'Formule : $$(k \\cdot u)\' = k \\cdot u\'$$',
            'Quand une fonction est \"collée\" à un nombre (une constante k) par une multiplication, le nombre reste sagement à sa place en tant que spectateur, et tu dérives uniquement la fonction.',
            'Exemple : $f(x) = 5x^4$. Le 5 reste là. Tu dérives $x^4$ (ça fait $4x^3$). Résultat : $f\'(x) = 5 \\cdot (4x^3) = 20x^3$.',
          ],
          },
        {
          type: 'rule',
          id: 'b13-formule-produit',
          titre: 'C. DÉRIVÉE D\'UN PRODUIT DE DEUX FONCTIONS',
          contenu: [
            'Formule : $$(uv)\' = u\'v + uv\'$$',
            '⚠️ Attention, c\'est ici que les choses sérieuses commencent. La dérivée de $u \\times v$ N\'EST PAS $u\' \\times v\'$. C\'est une erreur classique qui coûte très cher au BAC.',
          ],
        },
        {
          type: 'text',
          id: 'b14',
          contenu: "Exemple détaillé pas à pas : Soit $f(x) = (x^2 + 3) \\cdot \\ln(x)$ \n• On pose $u(x) = x^2 + 3 \\implies u'(x) = 2x$\n• On pose $v(x) = \\ln(x) \\implies v'(x) = \\frac{1}{x}$\n• On applique la formule croisée : $u'v + uv'$\n• $f'(x) = (2x) \\cdot \\ln(x) + (x^2 + 3) \\cdot \\frac{1}{x}$\n• Résultat final : $f'(x) = 2x \\cdot \\ln(x) + \\frac{x^2+3}{x}$",
        },
        {
          type: 'rule',
          id: 'b15-formule-quotient',
          titre: 'D. DÉRIVÉE D\'UN QUOTIENT (DIVISION)',
          contenu: [
            'Formule : $$(\\frac{u}{v})\' = \\frac{u\'v - uv\'}{v^2}$$',
            'Cette formule fait trembler de nombreux candidats, mais elle est en réalité extrêmement mécanique.',
          ],
        },
        {
          type: 'dialogue',
          id: 'b16-dialogue-quotient',
          pf: "Vieux père, sincèrement, pour la division, pourquoi je ne peux pas juste faire u' sur v' et puis on avance ? Ça irait plus vite et ça m'éviterait d'apprendre cette grosse formule.",
          gf: "Hééé, petit ! Si tu fais ça le jour du BAC, le correcteur va te barrer toute ta copie en rouge ! La division mathématique est capricieuse. Retiens bien la formule complète : (u'v - uv')/v². Et attention au signe MOINS au milieu du numérateur.",
        },
        {
          type: 'dialogue',
          id: 'b17-dialogue-quotient-suite',
          pf: "Pourquoi le signe moins impose une vigilance particulière ?",
          gf: "Comme il y a un moins, l'ordre est hyper important. Tu dois TOUJOURS commencer par dériver le numérateur (celui du haut, u) en premier ! Sinon, tout ton signe sera inversé, ton tableau de variations sera faux et ta courbe va plonger au lieu de monter.",
        },
        {
          type: 'text',
          id: 'b18',
          contenu: "Examinons 3 exemples corrigés indispensables :\n\n• 1. Fonction rationnelle : $f(x) = \\frac{2x-1}{x+4}$\n  - $u = 2x - 1 \\implies u' = 2$\n  - $v = x + 4 \\implies v' = 1$\n  - $f'(x) = \\frac{2(x+4) - (2x-1)(1)}{(x+4)^2} = \\frac{2x+8 - 2x+1}{(x+4)^2} = \\frac{9}{(x+4)^2}$\n\n• 2. Avec une exponentielle : $f(x) = \\frac{e^x}{x}$\n  - $u = e^x \\implies u' = e^x$\n  - $v = x \\implies v' = 1$\n  - $f'(x) = \\frac{e^x(x) - e^x(1)}{x^2} = \\frac{e^x(x-1)}{x^2}$\n\n• 3. Avec un logarithme : $f(x) = \\frac{\\ln(x)}{x^2}$\n  - $u = \\ln(x) \\implies u' = \\frac{1}{x}$\n  - $v = x^2 \\implies v' = 2x$\n  - $f'(x) = \\frac{\\frac{1}{x}(x^2) - \\ln(x)(2x)}{(x^2)^2} = \\frac{x - 2x\\ln(x)}{x^4} = \\frac{x(1-2\\ln(x))}{x^4} = \\frac{1-2\\ln(x)}{x^3}$",
        },
        {
          type: 'recap',
          id: 'b18-recap-intermediaire',
          titre: 'Points de vigilance sur les opérations',
          contenu: [
            '✅ Pour une somme, on dérive brique par brique.',
            '✅ Pour un produit, applique rigoureusement u\'v + uv\'.',
            '✅ Pour un quotient, commence par u\'v et garde le dénominateur au carré sans le développer.',
          ],
        },
        {
          type: 'text',
          id: 'b19-transition',
          contenu: 'Nous maîtrisons les mélanges de base. Passons maintenant au niveau supérieur : les fonctions composées, le boss final des calculs de dérivées.',
        },
      ],
    },
    {
      id: 's4',
      titre: '3.2 Suite — Dérivée d\'une Composée (La règle de la chaîne)',
      blocs: [
        {
          type: 'text',
          id: 'b20-accroche',
          contenu: 'Dériver des fonctions imbriquées te semble obscur ? Découvrons la règle de la chaîne pour extraire la dérivée de l\'intérieur sans commettre d\'erreur.',
        },
        {
          type: 'rule',
          id: 'b20-formule-composee-puissance',
          titre: 'E. DÉRIVÉE D\'UNE PUISSANCE COMPOSÉE',
          contenu: [
            'Formule : $$(u^n)\' = n \\cdot u\' \\cdot u^{n-1}$$',
            'Ici, la fonction u est elle-même une expression complète élevée à une puissance.',
          ],
        },
        {
          type: 'rule',
          id: 'b21-formules-composees',
          titre: '📌 RÈGLE D\'OR : LES COMPOSÉES COURANTES',
          contenu: [
            'Voici la liste des structures composées indispensables à maîtriser pour le BAC :',
            '• Dérivée de $e^u$ : $$ (e^u)\' = u\' \\cdot e^u $$',
            '• Dérivée de $\\ln(u)$ : $$ (\\ln(u))\' = \\frac{u\'}{u} $$',
            '• Dérivée de $\\sqrt{u}$ : $$ (\\sqrt{u})\' = \\frac{u\'}{2\\sqrt{u}} $$',
            '• Dérivée de $\\sin(u)$ : $$ (\\sin(u))\' = u\' \\cdot \\cos(u) $$',
            '• Dérivée de $\\cos(u)$ : $$ (\\cos(u))\' = -u\' \\cdot \\sin(u) $$',
            'Le principe reste unique : tu dérives l\'extérieur, puis tu multiplies par la dérivée de l\'intérieur (le fameux u\').',
          ],
        },
        {
          type: 'dialogue',
          id: 'b22-dialogue-chaine',
          pf: "Vieux père, la dérivée de (2x + 3)⁴, c'est juste 4(2x + 3)³, non ? J'applique la règle de x^n et le tour est joué !",
          gf: "Ah, le fameux piège ! Tu as oublié le bébé à l'intérieur du ventre de la mère ! Le (2x + 3) qui est niché là-dedans possède lui aussi sa propre dérivée... Tu dois obligatoirement multiplier par la dérivée de ce qui est à l'intérieur de la parenthèse. C'est le fameux u' de la formule.",
        },
        {
          type: 'text',
          id: 'b23',
          contenu: "Étudions 3 exemples corrigés pour bien comprendre :\n\n• 1. Polynôme à la puissance : $f(x) = (2x + 3)^4$\n  - On a la forme $u^n$ avec $u = 2x + 3$ et $n = 4$\n  - $u' = 2$\n  - $f'(x) = 4 \\cdot (2) \\cdot (2x + 3)^3 = 8(2x + 3)^3$\n\n• 2. Autre puissance courante : $f(x) = (x^2 - 5x)^3$\n  - $u = x^2 - 5x \\implies u' = 2x - 5$\n  - $n = 3$\n  - $f'(x) = 3 \\cdot (2x - 5) \\cdot (x^2 - 5x)^2$\n\n• 3. Puissance négative (l'ascenseur) : $f(x) = \\frac{1}{(3x+1)^2} = (3x + 1)^{-2}$\n  - $u = 3x + 1 \\implies u' = 3$\n  - $n = -2$\n  - $f'(x) = -2 \\cdot (3) \\cdot (3x + 1)^{-3} = \\frac{-6}{(3x+1)^3}$",
        },
        {
          type: 'exercise',
          id: 'micro-ex-composee',
          niveau: 'BASE',
          enonce: 'À toi de jouer ! Calcule la dérivée de la fonction composée suivante : $f(x) = e^{4x - 1}$',
          etapes: [
            'Étape 1 : Identifie la fonction intérieure : $u = 4x - 1$.',
            'Étape 2 : Calcule sa dérivée intérieure : $u\' = 4$.',
            'Étape 3 : Applique la formule $(e^u)\' = u\' \\cdot e^u$ pour obtenir le résultat.',
          ],
          reponse: '4e^{4x - 1}',
          conseil: 'N\'oublie jamais de faire descendre la dérivée de l\'exposant devant l\'exponentielle.',
        },
        {
          type: 'text',
          id: 'b24-transition',
          contenu: 'Toutes les briques et toutes les formules sont prêtes. Structurons tout cela dans un protocole d\'attaque en 5 étapes pour sécuriser ton devoir.',
        },
      ],
    },
    {
      id: 's5',
      titre: '3.3 Le Process EDUCTOME en 5 Étapes Numérotées',
      blocs: [
        {
          type: 'text',
          id: 'b25-accroche',
          contenu: 'Ne pars plus à l\'aventure lors d\'un calcul complexe. Découvre le protocole militaire d\'EDUCTOME pour attaquer n\'importe quelle fonction de l\'univers.',
        },
        {
          type: 'recap',
          id: 'b25-process-details',
          titre: 'Le \"Process EDUCTOME\"',
          contenu: [
            '1️⃣ ÉTAPE 1 : Identifier la forme globale de f(x). (S\'agit-il d\'une Somme ? d\'un Produit ? d\'un Quotient ? d\'une Composée ?).',
            '2️⃣ ÉTAPE 2 : Repérer quelle formule maîtresse appliquer. (Réciter mentalement la formule, ex: (u\'v − uv\')/v²).',
            '3️⃣ ÉTAPE 3 : Calculer les dérivées des \"briques\" élémentaires. (Poser proprement u, v et calculer u\', v\' au brouillon).',
            '4️⃣ ÉTAPE 4 : Assembler selon la formule. (Remplacer méthodiquement les lettres par les blocs d\'expressions trouvés).',
            '5️⃣ ÉTAPE 5 : Simplifier et factoriser le résultat final. (Mettre en facteur commun. Règle absolue : ON NE DÉVELOPPE JAMAIS LE DÉNOMINATEUR s\'il est déjà au carré).',
          ],
        },
        {
          type: 'text',
          id: 'b26',
          contenu: "Mettons en pratique ce protocole à travers 3 exercices guidés complets :",
        },
        {
          type: 'exercise',
          id: 'ex-guide-base',
          niveau: 'BASE',
          enonce: 'EXERCICE GUIDÉ — NIVEAU BASE : Calcule la dérivée de $f(x) = 4x^3 - 2x^2 + 5$',
          etapes: [
            'Étape 1 (Identifier) : C\'est une somme et une soustraction de termes simples polynômes.',
            'Étape 2 (Formule) : On applique $(u + v)\' = u\' + v\'$ et $(k \\cdot u)\' = k \\cdot u\'$.',
            'Étape 3 (Briques) : Les dérivées de $4x^3$ vaut $12x^2$, de $-2x^2$ vaut $-4x$, et de $5$ vaut $0$.',
            'Étape 4 (Assembler) : On réunit le tout : $f\'(x) = 12x^2 - 4x + 0$.',
            'Étape 5 (Simplifier) : Le résultat final est $12x^2 - 4x$. On peut factoriser par $4x$ : $4x(3x - 1)$.',
          ],
          reponse: '12x^2 - 4x',
          conseil: 'La factorisation finale est indispensable car elle te donne directement le signe de la dérivée pour l\'étape suivante du problème.',
        },
        {
          type: 'exercise',
          id: 'ex-guide-moyen',
          niveau: 'MOYEN',
          enonce: 'EXERCICE GUIDÉ — NIVEAU MOYEN : Calcule la dérivée de $g(x) = \\frac{3x+1}{x+2}$',
          etapes: [
            'Étape 1 (Identifier) : C\'est une division (Quotient de fonctions affines).',
            'Étape 2 (Formule) : Formule du quotient : $\\frac{u\'v - uv\'}{v^2}$.',
            'Étape 3 (Briques) : On pose $u = 3x + 1 \\implies u\' = 3$ et $v = x + 2 \\implies v\' = 1$.',
            'Étape 4 (Assembler) : On injecte dans la formule : $g\'(x) = \\frac{3 \\cdot (x + 2) - (3x + 1) \\cdot 1}{(x + 2)^2}$.',
            'Étape 5 (Simplifier) : On développe le haut en gardant le bas intact : $\\frac{3x + 6 - 3x - 1}{(x + 2)^2} = \\frac{5}{(x + 2)^2}$.',
          ],
          reponse: '\\frac{5}{(x + 2)^2}',
          conseil: 'Ne développe JAMAIS le $(x+2)^2$ du bas. Un carré est toujours positif, ce qui simplifie l\'étude du signe de ton expression.',
        },
        {
          type: 'exercise',
          id: 'ex-guide-difficile',
          niveau: 'BAC',
          enonce: 'EXERCICE GUIDÉ — NIVEAU DIFFICILE : Calcule la dérivée de $h(x) = (x^2 - 3x) \\cdot e^{2x}$',
          etapes: [
            'Étape 1 (Identifier) : C\'est un produit de deux fonctions, dont la seconde est une composée.',
            'Étape 2 (Formule) : Formule principale du produit : $(uv)\' = u\'v + uv\'$.',
            'Étape 3 (Briques) : $u = x^2 - 3x \\implies u\' = 2x - 3$. Pour $v = e^{2x}$, sa dérivée composée vaut $2e^{2x}$.',
            'Étape 4 (Assembler) : On applique la formule globale : $h\'(x) = (2x - 3) \\cdot e^{2x} + (x^2 - 3x) \\cdot 2e^{2x}$.',
            'Étape 5 (Simplifier) : On factorise par $e^{2x}$ : $e^{2x}[(2x - 3) + 2(x^2 - 3x)] = e^{2x}[2x - 3 + 2x^2 - 6x] = e^{2x}(2x^2 - 4x - 3)$.',
          ],
          reponse: 'e^{2x}(2x^2 - 4x - 3)',
          conseil: 'L\'exponentielle est un facteur commun magique. Mets-la toujours en avant pour clarifier ton expression.',
        },
        {
          type: 'text',
          id: 'b27-transition',
          contenu: 'C\'est en forgeant qu\'on devient forgeron, et c\'est au Cacao qu\'on devient caïman. Entrons dans la salle de sport : voici 10 exercices fondamentaux pour ancrer tes compétences.',
        },
      ],
    },
    {
      id: 's6',
      titre: '3.4 La Salle d\'Entraînement — 10 Exercices de Niveau BASE Corrigés',
      blocs: [
        {
          type: 'text',
          id: 'b28-accroche',
          contenu: 'Champion(ne), la répétition est le secret de la maîtrise. Attaque ces 10 exercices fondamentaux un par un et compare tes étapes avec mon protocole détaillé.',
        },
        {
          type: 'text',
          id: 'b28',
          contenu: "Le secret des mathématiques, c'est la répétition. Je te propose ici les 10 exercices fondamentaux. Prends une feuille, essaie de les faire seul(e), puis regarde ma correction ultra-détaillée. Si tu maîtrises ça, tu ne craindras plus aucune fonction au BAC.",
        },
        {
          type: 'exercise',
          id: 'ex-base-1',
          niveau: 'BASE',
          enonce: 'Exercice BASE 1 : Dérivée d\'un polynôme simple. Calcule la dérivée de $f(x) = -3x^2 + 5x - 2$',
          etapes: [
            'Étape 1 : Identifie le type : Somme classique, règle de $ax^n$.',
            'Étape 2 : Dérive $-3x^2$, ce qui donne $-3 \\times 2x = -6x$.',
            'Étape 3 : Dérive $5x$, ce qui donne $5 \\times 1 = 5$.',
            'Étape 4 : Dérive la constante $-2$, ce qui donne $0$.',
            'Étape 5 : Additionne les blocs pour obtenir le résultat final : $f\'(x) = -6x + 5$.',
          ],
          reponse: '-6x + 5',
          conseil: 'Garde les signes bien associés aux coefficients lors de la dérivation.',
        },
        {
          type: 'exercise',
          id: 'ex-base-2',
          niveau: 'BASE',
          enonce: 'Exercice BASE 2 : La constante déguisée. Calcule la dérivée de $f(x) = \\frac{\\pi^2}{2} + 4x$',
          etapes: [
            'Étape 1 : Analyse le premier bloc : $\\frac{\\pi^2}{2}$ ne contient pas la variable x. C\'sest une constante fixe.',
            'Étape 2 : Applique la règle : la dérivée de cette constante vaut $0$.',
            'Étape 3 : Dérive le second bloc : la dérivée de $4x$ vaut $4$.',
            'Étape 4 : Assemble les résultats : $f\'(x) = 0 + 4 = 4$.',
          ],
          reponse: '4',
          conseil: 'Ne te laisse pas effrayer par la présence de $\\pi$ ou de fractions de nombres. Sans x, la dérivée s\'annule !',
        },
        {
          type: 'exercise',
          id: 'ex-base-3',
          niveau: 'BASE',
          enonce: 'Exercice BASE 3 : Dérivée avec racine carrée. Calcule la dérivée de $f(x) = 5\\sqrt{x} - 3x^3$',
          etapes: [
            'Étape 1 : Identifie les structures : c\'est une somme combinant une racine et une puissance.',
            'Étape 2 : Dérive $5\\sqrt{x}$ en appliquant la formule de la racine : $5 \\cdot \\frac{1}{2\\sqrt{x}} = \\frac{5}{2\\sqrt{x}}$.',
            'Étape 3 : Dérive $-3x^3$ en appliquant la formule des puissances : $-3 \\cdot 3x^2 = -9x^2$.',
            'Étape 4 : Assemble l\'ensemble des expressions : $f\'(x) = \\frac{5}{2\\sqrt{x}} - 9x^2$.',
          ],
          reponse: '\\frac{5}{2\\sqrt{x}} - 9x^2',
          conseil: 'La racine carrée reste au dénominateur avec son coefficient 2 lors de l\'opération.',
        },
        {
          type: 'exercise',
          id: 'ex-base-4',
          niveau: 'BASE',
          enonce: 'Exercice BASE 4 : Produit de fonctions simples. Calcule la dérivée de $f(x) = (2x - 1)e^x$',
          etapes: [
            'Étape 1 : Identifie la forme : c\'est un produit de type $u \\times v$.',
            'Étape 2 : Pose les briques : $u = 2x - 1 \\implies u\' = 2$ et $v = e^x \\implies v\' = e^x$.',
            'Étape 3 : Applique la formule $(uv)\' = u\'v + uv\'$ : $f\'(x) = (2)(e^x) + (2x - 1)(e^x)$.',
            'Étape 4 : Simplifie par factorisation de la boussole $e^x$ : $f\'(x) = e^x[2 + (2x - 1)] = e^x(2x + 1).$',
          ],
          reponse: 'e^x(2x + 1)',
          conseil: 'Garde l\'automatisme de factoriser par l\'exponentielle, c\'est un gain de temps précieux pour le problème.',
        },
        {
          type: 'exercise',
          id: 'ex-base-5',
          niveau: 'BASE',
          enonce: 'Exercice BASE 5 : Fonction avec logarithme. Calcule la dérivée de $f(x) = x\\ln(x) - x$',
          etapes: [
            'Étape 1 : Dérive en premier le bloc produit $x\\ln(x)$ avec $u=x \\implies u\'=1$ et $v=\\ln(x) \\implies v\'=\\frac{1}{x}$.',
            'Étape 2 : Le produit donne : $(1 \\cdot \\ln(x)) + (x \\cdot \\frac{1}{x}) = \\ln(x) + 1$.',
            'Étape 3 : Dérive ensuite le second terme $-x$, ce qui donne $-1$.',
            'Étape 4 : Assemble l\'ensemble : $f\'(x) = (\\ln(x) + 1) - 1 = \\ln(x)$.',
          ],
          reponse: '\\ln(x)',
          explication: 'Le résultat final épuré est $f\'(x) = \\ln(x)$. C\'est une relation fondamentale à garder en mémoire pour les chapitres de primitives.',
          conseil: 'Ce résultat est magnifique, retiens-le bien !',
        },
        {
          type: 'exercise',
          id: 'ex-base-6',
          niveau: 'BASE',
          enonce: 'Exercice BASE 6 : La fraction simple (inverse). Calcule la dérivée de $f(x) = \\frac{4}{x}$',
          etapes: [
            'Étape 1 : Évite d\'utiliser la lourde formule du quotient. Réécris la fonction sous la forme $4 \\cdot \\frac{1}{x}$.',
            'Étape 2 : Applique la formule de l\'inverse usuelle : la dérivée de $\\frac{1}{x}$ vaut $-\\frac{1}{x^2}$.',
            'Étape 3 : Multiplie par la constante spectatrice : $f\'(x) = 4 \\cdot (-\\frac{1}{x^2}) = -\\frac{4}{x^2}$.',
          ],
          reponse: '-\\frac{4}{x^2}',
          conseil: 'Gagner du temps sur les fractions à numérateur constant te protège de nombreuses erreurs de signes.',
        },
        {
          type: 'exercise',
          id: 'ex-base-7',
          niveau: 'BASE',
          enonce: 'Exercice BASE 7 : Dérivée d\'un quotient simple. Calcule la dérivée de $f(x) = \\frac{\\ln(x)}{x}$',
          etapes: [
            'Étape 1 : Identifie la forme : c\'est un quotient de type $\\frac{u}{v}$.',
            'Étape 2 : Pose les expressions : $u = \\ln(x) \\implies u\' = \\frac{1}{x}$ et $v = x \\implies v\' = 1$.',
            'Étape 3 : Applique le quotient : $f\'(x) = \\frac{(\\frac{1}{x})(x) - (\\ln(x))(1)}{x^2}$.',
            'Étape 4 : Réduis le numérateur : $(\\frac{1}{x}) \\times x = 1$, ce qui laisse $1 - \\ln(x)$.',
            'Étape 5 : Écris le résultat final propre : $f\'(x) = \\frac{1 - \\ln(x)}{x^2}$.',
          ],
          reponse: '\\frac{1 - \\ln(x)}{x^2}',
          conseil: 'Prends soin de simplifier les fractions intérieures dès la première étape du développement.',
        },
        {
          type: 'exercise',
          id: 'ex-base-8',
          niveau: 'BASE',
          enonce: 'Exercice BASE 8 : Dérivée avec x au dénominateur. Calcule la dérivée de $f(x) = \\frac{3}{x} + x$',
          etapes: [
            'Étape 1 : Sépare les termes. $\\frac{3}{x}$ correspond à $3 \\cdot \\frac{1}{x}$.',
            'Étape 2 : La dérivée de ce premier bloc est $3 \\cdot (-\\frac{1}{x^2}) = -\\frac{3}{x^2}$.',
            'Étape 3 : La dérivée du second bloc $x$ vaut $1$. On assemble : $f\'(x) = -\\frac{3}{x^2} + 1$.',
            'Étape 4 : Mets au même dénominateur (crucial pour le signe) : $f\'(x) = \\frac{-3 + x^2}{x^2} = \\frac{x^2 - 3}{x^2}$.',
          ],
          reponse: '\\frac{x^2 - 3}{x^2}',
          conseil: 'Mettre au même dénominateur est le secret des majors pour lire le signe du numérateur en un clin d\'œil.',
        },
        {
          type: 'exercise',
          id: 'ex-base-9',
          niveau: 'BASE',
          enonce: 'Exercice BASE 9 : Dérivée de x au cube en fraction. Calcule la dérivée de $g(x) = \\frac{x^3}{2} - \\frac{x}{3}$',
          etapes: [
            'Étape 1 : ⚠️ Point de vigilance ! Ne fais pas un u/v complexe quand le bas est un simple chiffre. Réécris la fonction : $g(x) = \\frac{1}{2}x^3 - \\frac{1}{3}x$.',
            'Étape 2 : Dérive $x^3 \\implies 3x^2$, ce qui donne avec la constante : $\\frac{1}{2} \\cdot 3x^2 = \\frac{3x^2}{2}$.',
            'Étape 3 : Dérive $x \\implies 1$, ce qui donne avec la constante : $-\\frac{1}{3} \\cdot 1 = -\\frac{1}{3}$.',
            'Étape 4 : Rassemble les deux briques propres : $g\'(x) = \\frac{3x^2}{2} - \\frac{1}{3}$.',
          ],
          reponse: '\\frac{3x^2}{2} - \\frac{1}{3}',
          conseil: 'Un dénominateur constant n\'est pas une fonction. Traite-le comme un simple coefficient spectateur.',
        },
        {
          type: 'exercise',
          id: 'ex-base-10',
          niveau: 'BASE',
          enonce: 'Exercice BASE 10 : Dérivée d\'une composée puissance. Calcule la dérivée de $g(x) = (5x - 2)^3$',
          etapes: [
            'Étape 1 : Repère la structure : c\'est un bloc complet u élevé à la puissance n.',
            'Étape 2 : Pose la brique intérieure : $u = 5x - 2 \\implies u\' = 5$, avec $n = 3$.',
            'Étape 3 : Applique la formule $(u^n)\' = n \\cdot u\' \\cdot u^{n-1}$ : $g\'(x) = 3 \\cdot (5) \\cdot (5x - 2)^{3-1}$.',
            'Étape 4 : Multiplie les constantes extérieures pour finaliser : $g\'(x) = 15(5x - 2)^2$.',
          ],
          reponse: '15(5x - 2)^2',
          conseil: 'Conserve la parenthèse intacte à l\'intérieur, seul son exposant diminue d\'une unité.',
        },
        {
          type: 'tip',
          id: 'b29-bilan-motivation',
          titre: 'Félicitations de ton Grand Frère',
          contenu: [
            'Félicitations, champion(ne) ! Tu viens de faire tes gammes de calcul complets.',
            'La maîtrise parfaite de ces dérivées de base te donnera une confiance en béton armé.',
            'Repose-toi quelques minutes, prends une gorgée d\'eau sous l\'apatam.',
            'On se retrouve tout de suite pour le Chapitre 4 afin de voir comment utiliser cette boussole pour dresser des courbes de pro !',
          ],
        },
      ],
    },
  ],
  quiz: [
    {
      type: 'quiz',
      id: 'q1',
      question: 'Quelle est la dérivée de la fonction constante $f(x) = \\ln(3)$ ?',
      options: [
        '$f\'(x) = \\frac{1}{3}$',
        '$f\'(x) = 0$',
        '$f\'(x) = 3$',
        '$f\'(x) = \\ln(3)$',
      ],
      bonneReponse: 1,
      explication: '$\\ln(3)$ est un nombre fixe, il ne contient pas de variable x. C\'est un piège fréquent. La dérivée d\'une constante vaut toujours 0.',
    },
    {
      type: 'quiz',
      id: 'q2',
      question: 'Quelle est la formule correcte pour calculer la dérivée d\'un produit de deux fonctions $(uv)\'$ ?',
      options: [
        '$(uv)\' = u\' \\times v\'$',
        '$(uv)\' = u\'v - uv\'$',
        '$(uv)\' = u\'v + uv\'$',
        '$(uv)\' = \\frac{u\'v + uv\'}{v^2}$',
      ],
      bonneReponse: 2,
      explication: 'La règle du produit est un assemblage croisé avec un signe plus : $u\'v + uv\'$. Ne confonds jamais avec le produit brut des dérivées.',
    },
    {
      type: 'quiz',
      id: 'q3',
      question: 'Lors du calcul de la dérivée d\'un quotient, quelle est la règle d\'or concernant le dénominateur $v^2$ ?',
      options: [
        'Il faut absolument le développer en utilisant les identités remarquables',
        'Il faut l\'annuler immédiatement pour simplifier',
        'ON NE LE DÉVELOPPE JAMAIS : un carré est positif, ce qui est parfait pour étudier le signe',
        'Il faut le faire monter au numérateur avec un exposant négatif',
      ],
      bonneReponse: 2,
      explication: 'Le dénominateur d\'un quotient dérivé est de la forme $v^2$. Comme un carré est toujours positif sur son domaine, le garder intact permet de se concentrer uniquement sur le signe du numérateur.',
    },
    {
      type: 'quiz',
      id: 'q4',
      question: 'Quelle est la dérivée exacte de la fonction composée puissance $f(x) = (2x + 1)^3$ ?',
      options: [
        '$f\'(x) = 3(2x + 1)^2$',
        '$f\'(x) = 6(2x + 1)^2$',
        '$f\'(x) = 2(2x + 1)^2$',
        '$f\'(x) = 6x(2x + 1)^2$',
      ],
      bonneReponse: 1,
      explication: 'On applique la formule $(u^n)\' = n \\cdot u\' \\cdot u^{n-1}$. Ici $u = 2x + 1 \\implies u\' = 2$, et $n = 3$. Ce qui donne $3 \\times 2 \\times (2x + 1)^2 = 6(2x + 1)^2$.',
    },
    {
      type: 'quiz',
      id: 'q5',
      question: 'Comment dérive-t-on de la façon la plus rapide et astucieuse la fraction simple $f(x) = \\frac{7}{x}$ ?',
      options: [
        'En appliquant la lourde formule du quotient $\\frac{u\'v - uv\'}{v^2}$',
        'En écrivant $7 \\cdot \\frac{1}{x}$ et en appliquant directement la formule de l\'inverse : $7 \\cdot (-\\frac{1}{x^2}) = -\\frac{7}{x^2}$',
        'En disant que la dérivée du haut vaut 0 et celle du bas vaut 1',
        'En annulant le numérateur',
      ],
      bonneReponse: 1,
      explication: 'Pour une fraction à numérateur constant, l\'isoler sous forme de produit par $\\frac{1}{x}$ permet d\'obtenir instantanément $-\\frac{k}{x^2}$, évitant des étapes de calcul inutiles.',
    },
  ],
};