// src/data/t2-derivees/chap6.ts
import { Chapitre } from '../../types/course';

export const chapitre5: Chapitre = {
  id: 't2-chap6',
  titre: 'Exercices Type BAC',
  duree: 45,
  niveau: 'BAC',
  xpGain: 100,
  gratuit: false,
  objectifs: [
    'Démystifier le mythe du Problème du BAC en le découpant en questions simples',
    'Résoudre les 5 exercices d\'Échauffement de niveau BASE (Polynôme, Produit, Quotient, Composée, Tangente)',
    'Maîtriser les 5 exercices de Technique de niveau MOYEN (Variations, Extremums, Optimisation, Équations complexes)',
    'Dominer le Marathon du BAC composé de 10 grands sujets de synthèse entièrement corrigés',
    'S\'entraîner en autonomie complète sans filet sur 10 défis flash avec validation finale',
  ],
  sections: [
    {
      id: 's1',
      titre: 'Introduction — Monter sur le Ring de l\'Analyse',
      blocs: [
        {
          type: 'text',
          id: 'b1-accroche',
          contenu: 'Champion(ne), tu as accumulé la théorie et la technique. Maintenant, il est temps de chausser tes crampons et de toucher le ballon. Découvrons comment pulvériser la peur des sujets de l\'examen.',
        },
        {
          type: 'text',
          id: 'b1',
          contenu: "📖 L'ANECDOTE DU GRAND FRÈRE :\nJe me rappelle mon premier grand devoir de niveau au Lycée Classique d'Abidjan, en Terminale. J'avais appris toutes mes formules par cœur. Je pouvais réciter le tableau des dérivées les yeux fermés. Mais quand on a distribué le sujet, face au fameux \"Problème (10 points)\", j'ai paniqué. Les questions s'enchaînaient, le texte était long, et j'ai eu l'impression que c'était une langue étrangère. J'ai eu 06/20. En rentrant chez moi, mon grand frère a regardé ma copie, a souri et m'a dit : \"Champion, connaître les règles du football ne fait pas de toi un bon joueur si tu ne touches jamais le ballon. On a vu la théorie, la méthode, maintenant on monte sur le ring !\". Il m'a obligé à faire des annales, encore et encore, jusqu'à ce que les questions deviennent des automatismes. Le secret, c'est l'entraînement.",
        },
        {
          type: 'dialogue',
          id: 'b2',
          pf: "Vieux père, quand je vois 'Niveau BAC' écrit sur un exercice, mes mains commencent à transpirer. J'ai l'impression que les professeurs font exprès de chercher des fonctions bizarres pour nous 'daba' (nous faire échouer). Je suis prêt à abandonner avant même de commencer !",
          gf: "Hé, champion ! Faut pas te blaguer, le BAC ce n'est pas un monstre mythologique. Enlève ce blocage de ta tête. Un exercice 'Type BAC', c'est juste une succession de petites questions faciles que tu sais DÉJÀ faire, mais qui sont attachées les unes aux autres. Si tu sais dériver, étudier un signe et tracer une tangente, tu as déjà 70% des points du problème. Aujourd'hui, on va démystifier ça ensemble. On commence doucement, puis on augmente le rythme. Prêt à gâter le coin ?",
        },
        {
          type: 'dialogue',
          id: 'b3',
          pf: "Prêt, vieux père ! Allons gâter le coin !",
          gf: "C'est ça même ! On commence tout de suite par l'échauffement.",
        },
        {
          type: 'text',
          id: 'b4-transition',
          contenu: 'Démarrons notre protocole d\'entraînement par la section de BASE pour activer tes réflexes musculaires de calcul.',
        },
      ],
    },
    {
      id: 's2',
      titre: '5.1 Exercices Niveau BASE (Échauffement Rapide)',
      blocs: [
        {
          type: 'text',
          id: 'b5-accroche',
          contenu: 'Prends 5 minutes chrono par exercice. L\'objectif ici est de valider tes automatismes de dérivation brute.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-1',
          niveau: 'BASE',
          enonce: '5.1.1 — Dérivée d\'un Polynôme :\nSoit la fonction f définie sur $\\mathbb{R}$ par $f(x) = \\frac{1}{4}x^4 - 2x^3 + \\frac{5}{2}x^2 - 7x + 10$. Calcule sa fonction dérivée $f\'(x)$.',
          etapes: [
            'Étape 1 (Identification) : Polynôme simple, somme de termes du type $ax^n$.',
            'Étape 2 (Calcul) : On dérive terme par terme en conservant les fractions : $f\'(x) = \\frac{1}{4}(4x^3) - 2(3x^2) + \\frac{5}{2}(2x) - 7(1) + 0$.',
            'Étape 3 (Simplification) : On réduit les coefficients jumeaux : $\\frac{4}{4}=1$ et $\\frac{2}{2}=1$. On obtient : $x^3 - 6x^2 + 5x - 7$.',
          ],
          reponse: 'x^3 - 6x^2 + 5x - 7',
          warning: 'Piège à éviter : Oublier que la dérivée d\'une constante isolée comme 10 s\'annule et vaut strictement 0.',
          conseil: 'Effectue tes simplifications de fractions calmement au brouillon pour ne pas traîner de faux coefficients.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-2',
          niveau: 'BASE',
          enonce: '5.1.2 — Dérivée de Produit avec Exponentielle :\nSoit la fonction g définie sur $\\mathbb{R}$ par $g(x) = (3x - 2)e^x$. Calcule sa fonction dérivée $g\'(x)$.',
          etapes: [
            'Étape 1 (Identification) : Produit de deux blocs distincts, formule maîtresse : $(u \\cdot v)\' = u\'v + uv\'$.',
            'Étape 2 (Briques) : On pose $u = 3x - 2 \\implies u\' = 3$ et $v = e^x \\implies v\' = e^x$.',
            'Étape 3 (Calcul) : On déploie la formule croisée : $g\'(x) = 3(e^x) + (3x - 2)(e^x)$.',
            'Étape 4 (Simplification) : On factorise par l\'exponentielle : $e^x[3 + (3x - 2)] = e^x(3x + 1)$.',
          ],
          reponse: 'e^x(3x + 1)',
          warning: 'Piège à éviter : Écrire que la dérivée d\'un produit est égale au produit des dérivées $g\'(x) = u\' \\times v\' = 3e^x$. C\'est une erreur incontournable à éviter qui annule tous tes points.',
          conseil: 'Mets systématiquement l\'exponentielle en facteur commun pour épurer ton expression.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-3',
          niveau: 'BASE',
          enonce: '5.1.3 — Dérivée de Quotient Simple (Homographique) :\nSoit la fonction h définie sur $\\mathbb{R} \\setminus \\{3\\}$ par $h(x) = \\frac{2x+5}{x-3}$. Calcule sa fonction dérivée $h\'(x)$.',
          etapes: [
            'Étape 1 (Identification) : Quotient de deux expressions, formule maîtresse : $(\\frac{u}{v})\' = \\frac{u\'v - uv\'}{v^2}$.',
            'Étape 2 (Briques) : On pose $u = 2x + 5 \\implies u\' = 2$ et $v = x - 3 \\implies v\' = 1$.',
            'Étape 3 (Calcul) : On injecte au numérateur : $h\'(x) = \\frac{2(x-3) - (2x+5)(1)}{(x-3)^2}$.',
            'Étape 4 (Simplification) : On développe le haut en conservant le carré du bas : $\\frac{2x - 6 - 2x - 5}{(x-3)^2} = \\frac{-11}{(x-3)^2}$.',
          ],
          reponse: '\\frac{-11}{(x-3)^2}',
          warning: 'Piège à éviter : Oublier de distribuer le signe moins sur l\'ensemble du second bloc. $-(2x+5)$ devient $-2x - 5$ et non $-2x + 5$.',
          conseil: 'Laisse le dénominateur au carré bien emballé sans jamais chercher à le développer.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-4',
          niveau: 'BASE',
          enonce: '5.1.4 — Dérivée de Composée Simple (Logarithme) :\nSoit la fonction k définie sur $\\mathbb{R}$ par $k(x) = \\ln(x^2 + 4)$. Calcule sa fonction dérivée $k\'(x)$.',
          etapes: [
            'Étape 1 (Identification) : Fonction composée de type $\\ln(u)$, dont la formule de dérivation est $\\frac{u\'}{u}$.',
            'Étape 2 (Briques) : On identifie l\'expression intérieure : $u = x^2 + 4 \\implies u\' = 2x$.',
            'Étape 3 (Calcul) : On assemble directement selon le modèle : $k\'(x) = \\frac{2x}{x^2 + 4}$.',
          ],
          reponse: '\\frac{2x}{x^2 + 4}',
          warning: 'Piège à éviter : Écrire que la dérivée vaut simplement $\\frac{1}{x^2+4}$ en oubliant la dérivée de l\'expression nichée à l\'intérieur.',
          conseil: 'Repère le \"bébé\" dans le ventre de la mère et multiplie toujours par sa dérivée u\'.',
        },
        {
          type: 'exercise',
          id: 'ex-5-1-5',
          niveau: 'BASE',
          enonce: '5.1.5 — Application Géométrique : Tangente standard :\nSoit la fonction f définie sur $\\mathbb{R}$ par $f(x) = x^2 - 4x + 3$. Détermine l\'équation réduite de la droite tangente (T) au point d\'abscisse $x_0 = 4$.',
          etapes: [
            'Étape 1 (Formule) : Rappelle la formule officielle : $y = f\'(x_0)(x - x_0) + f(x_0)$. Ici $x_0 = 4$.',
            'Étape 2 (Image) : Calcule la hauteur du point de contact : $f(4) = 4^2 - 4(4) + 3 = 16 - 16 + 3 = 3$.',
            'Étape 3 (Nombre Dérivé) : Calcule la dérivée $f\'(x) = 2x - 4$, puis évalue en 4 : $f\'(4) = 2(4) - 4 = 4$.',
            'Étape 4 (Assembler) : Injecte les trois valeurs : $y = 4(x - 4) + 3$.',
            'Étape 5 (Réduire) : Développe l\'expression : $y = 4x - 16 + 3 \\implies y = 4x - 13$.',
          ],
          reponse: 'y = 4x - 13',
          warning: 'Piège à éviter : Confondre les rôles de l\'image f(x₀) et du nombre dérivé f\'(x₀) lors de la mise en place dans l\'équation.',
          conseil: 'Termine toujours ton calcul sous la forme épurée d\'une équation de droite affine $y = mx + p$.',
        },
        {
          type: 'text',
          id: 'b6-transition',
          contenu: 'L\'échauffement est terminé, tes muscles numériques sont prêts. Élevons le niveau : passons aux exercices techniques de niveau MOYEN.',
        },
      ],
    },
    {
      id: 's3',
      titre: '5.2 Exercices Niveau MOYEN (Technique et Rigueur)',
      blocs: [
        {
          type: 'text',
          id: 'b7-accroche',
          contenu: 'Champion(ne), ici on ne cherche plus seulement des formules isolées, on construit des raisonnements complets d\'analyse. Prends ton brouillon.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-1',
          niveau: 'MOYEN',
          enonce: '5.2.1 — Étude de Variations Complète :\nSoit la fonction f définie sur $]0 ; +\\infty[$ par $f(x) = \\frac{x^2 - x + 4}{x}$. Étudie de façon rigoureuse ses variations.',
          etapes: [
            'Étape 1 (Astuce) : Ne te lance pas dans un u/v lourd. Sépare ta fraction par terme : $f(x) = \\frac{x^2}{x} - \\frac{x}{x} + \\frac{4}{x} = x - 1 + \\frac{4}{x}$.',
            'Étape 2 (Dériver) : Dérive cette somme simplifiée : $f\'(x) = 1 - 0 - \\frac{4}{x^2} = \\frac{x^2 - 4}{x^2}$.',
            'Étape 3 (Annulation) : On cherche où la dérivée s\'annule : $x^2 - 4 = 0 \\implies (x-2)(x+2) = 0$. Sur notre domaine, la seule racine retenue est $x = 2$.',
            'Étape 4 (Signe) : Le bas $x^2$ est strictement positif. Le signe dépend du haut $x^2-4$. Pour $x \\in ]0; 2[$, $f\'(x) < 0$ (négatif). Pour $x \\in ]2; +\\infty[$, $f\'(x) > 0$ (positif).',
            'Étape 5 (Conclusion) : La fonction f est strictement décroissante sur $]0; 2]$ et strictement croissante sur $[2; +\\infty[$.',
          ],
          reponse: 'Décroissante sur ]0;2], Croissante sur [2;+inf[',
          warning: 'Piège à éviter : Passer à côté du raccourci de la scission de fraction, ce qui t\'expose à des erreurs de réduction sur un u/v complet.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-2',
          niveau: 'MOYEN',
          enonce: '5.2.2 — Recherche d\'Extremums Locaux :\nSoit la fonction g définie sur $\\mathbb{R}$ par $g(x) = 2x^3 - 3x^2 - 12x + 1$. Trouve les coordonnées complètes (abscisse et ordonnée) de ses extremums.',
          etapes: [
            'Étape 1 (Dérive) : On extrait la fonction dérivée : $g\'(x) = 6x^2 - 6x - 12$.',
            'Étape 2 (Racines) : On résout $6x^2 - 6x - 12 = 0$. On simplifie par 6 : $x^2 - x - 2 = 0$. Le discriminant $\\Delta = 9$, ce qui donne les abscisses critiques $x_1 = -1$ et $x_2 = 2$.',
            'Étape 3 (Hauteurs) : On calcule obligatoirement les images correspondantes : $g(-1) = 2(-1)^3 - 3(-1)^2 - 12(-1) + 1 = -2 - 3 + 12 + 1 = 8$. Et $g(2) = 2(8) - 3(4) - 12(2) + 1 = -19$.',
            'Étape 4 (Analyse) : Le coefficient leader (6) étant positif, la courbe grimpe, s\'aplanit en -1, plonge vers 2, puis remonte.',
            'Étape 5 (Conclusion) : g admet un maximum local au point $A(-1; 8)$ et un minimum local au point $B(2; -19)$.',
          ],
          reponse: 'Max A(-1;8), Min B(2;-19)',
          warning: 'Piège à éviter : Trouver les valeurs de x et s\'arrêter au milieu du chemin. Un extremum est une altitude, le calcul de l\'image est obligatoire !',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-3',
          niveau: 'MOYEN',
          enonce: '5.2.3 — Optimisation Économique d\'Entreprise :\nUne entreprise produit x centaines d\'objets ($x \\in [0; 10]$). Le bénéfice en millions de FCFA est modélisé par $B(x) = -x^2 + 10x - 16$. Détermine la quantité idéale à fabriquer et le profit maximal associé.',
          etapes: [
            'Étape 1 (Dériver) : On cherche le sommet de la parabole inversée : $B\'(x) = -2x + 10$.',
            'Étape 2 (Annuler) : On cherche le point critique : $-2x + 10 = 0 \\implies 2x = 10 \\implies x = 5$.',
            'Étape 3 (Signe) : Pour $x < 5$, la pente est positive (+), et pour $x > 5$ la pente est négative (−). Le profit monte puis descend : c\'est bien un maximum.',
            'Étape 4 (Profit) : On évalue la hauteur du gain en 5 : $B(5) = -(5)^2 + 10(5) - 16 = -25 + 50 - 16 = 9$.',
            'Étape 5 (Conclusion) : Il faut produire 5 centaines (soit 500 objets) pour dégager un bénéfice maximal de 9 millions de FCFA.',
          ],
          reponse: '500 objets pour 9 millions',
          warning: 'Piège à éviter : Faire une erreur de signe grossière sur $-(5)^2$. Le moins n\'étant pas englobé dans le carré, cela donne $-25$ et non $+25$.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-4',
          niveau: 'MOYEN',
          enonce: '5.2.4 — Tangente Horizontale avec Exponentielle :\nSoit la fonction f définie sur $\\mathbb{R}$ par $f(x) = (x - 1)e^x$. Existe-t-il un point sur la courbe où la tangente est parfaitement couchée (horizontale) ?',
          etapes: [
            'Étape 1 (Traduction) : Dire que la tangente est horizontale signifie que son coefficient directeur (sa pente) est nul. On doit donc résoudre $f\'(x) = 0$.',
            'Étape 2 (Dériver) : On dérive le produit de fonctions : $f\'(x) = 1(e^x) + (x - 1)e^x = e^x(1 + x - 1) = xe^x$.',
            'Étape 3 (Résoudre) : On cherche l\'annulation : $xe^x = 0$. Comme l\'exponentielle $e^x$ est strictement positive et ne s\'annule jamais, la seule solution est $x = 0$.',
            'Étape 4 (Ordonnée) : On calcule la hauteur de ce point fixe : $f(0) = (0 - 1)e^0 = -1 \\times 1 = -1$.',
            'Étape 5 (Conclusion) : Oui, au point exact de coordonnées $(0; -1)$, la courbe possède une tangente horizontale.',
          ],
          reponse: '(0; -1)',
          conseil: 'Retiens que l\'annulation d\'un produit contenant une exponentielle dépend uniquement de l\'autre facteur.',
        },
        {
          type: 'exercise',
          id: 'ex-5-2-5',
          niveau: 'MOYEN',
          enonce: '5.2.5 — Dérivée Composée Complexe (Racine) :\nSoit la fonction h définie sur $\\mathbb{R}$ par $h(x) = \\sqrt{e^{2x} + 4x}$. Détermine sa fonction dérivée propre sous sa forme la plus réduite.',
          etapes: [
            'Étape 1 (Formule) : Structure générale de type $\\sqrt{u}$, la dérivée est donnée par $\\frac{u\'}{2\\sqrt{u}}$.',
            'Étape 2 (Intérieur) : On extrait le bloc sous la racine : $u = e^{2x} + 4x$.',
            'Étape 3 (Dérive interne) : On calcule $u\'$ en faisant attention à la composée de l\'exponentielle : $(e^{2x})\' = 2e^{2x}$. On obtient $u\' = 2e^{2x} + 4$.',
            'Étape 4 (Assembler) : On réunit dans la fraction globale : $h\'(x) = \\frac{2e^{2x} + 4}{2\\sqrt{e^{2x} + 4x}}$.',
            'Étape 5 (Simplifier) : On factorise par 2 au numérateur pour le simplifier avec le bas : $\\frac{2(e^{2x} + 2)}{2\\sqrt{e^{2x} + 4x}} = \\frac{e^{2x} + 2}{\\sqrt{e^{2x} + 4x}}$.',
          ],
          reponse: '\\frac{e^{2x} + 2}{\\sqrt{e^{2x} + 4x}}',
          warning: 'Piège à éviter : Oublier de dériver l\'exposant de $e^{2x}$ lors de la dérivation interne, ou rendre une copie sans effectuer la simplification par 2.',
        },
        {
          type: 'text',
          id: 'b8-transition',
          contenu: 'Les entraînements intermédiaires ont porté leurs fruits. Tu as du muscle, tu as la technique. Range ton smartphone de côté un instant, concentre-toi au maximum : on monte sur le ring du Marathon du BAC.',
        },
      ],
    },
    {
      id: 's4',
      titre: '5.3 Exercices Niveau BAC — Le Grand Marathon de Synthèse',
      blocs: [
        {
          type: 'text',
          id: 'b9-accroche',
          contenu: 'Champion(ne), voici 10 grands sujets de synthèse calqués au millimètre près sur les exigences réelles du BAC ivoirien. Ne fuis pas, affronte-les pas-à-pas.',
        },
        {
          type: 'tip',
          id: 'b9-motiv-marathon',
          titre: 'Le Grand Frère te parle',
          contenu: [
            'Ces 10 sujets sont structurés EXACTEMENT comme ce que tu auras devant toi le jour du BAC.',
            'Même format, même difficulté, même notation.',
            'Sers-toi d\'une feuille blanche, chronomètre-toi et essaie seul(e) avant de lire ma correction croisée. C\'est ça la mentalité d\'un caïman !',
          ],
        },
        {
          type: 'exercise',
          id: 'sujet-bac-1',
          niveau: 'BAC',
          enonce: 'Sujet 1 : Étude Complète d\'une Fonction Polynôme\n[Durée recommandée : 25 min | Barème : 4 points]\n\nSoit la fonction f définie sur $\\mathbb{R}$ par $f(x) = \\frac{1}{3}x^3 - \\frac{1}{2}x^2 - 2x + 1$. On note (C) sa courbe représentative.\n\na) Calculer $f\'(x)$ et étudier son signe. (1 pt)\nb) Dresser le tableau de variations complet de f en incluant les limites aux infinis. (1,5 pt)\nc) Déterminer l\'équation de la droite tangente (T) au point d\'abscisse $x_0 = 0$. (0,5 pt)\nd) Étudier la position relative de la courbe (C) par rapport à sa tangente (T). (1 pt)',
          etapes: [
            'Correction a) : Dérivée et signe. On dérive terme à terme : $f\'(x) = x^2 - x - 2$. On cherche les racines du trinôme : $\\Delta = (-1)^2 - 4(1)(-2) = 9 \\implies \\sqrt{\\Delta} = 3$. Les racines sont $x_1 = -1$ et $x_2 = 2$. Le coefficient dominant $a=1>0$ impose un signe positif à l\'extérieur des racines : $f\'(x) > 0$ sur $]-\\infty; -1[ \\cup ]2; +\\infty[$ (croissante) et $f\'(x) < 0$ sur $]-1; 2[$ (décroissante).',
            'Correction b) : Limites et tableau. Comme f est un polynôme, sa limite dépend de son terme de plus haut degré : $\\lim_{x \\to -\\infty} f(x) = \\lim \\frac{1}{3}x^3 = -\\infty$, et $\\lim_{x \\to +\\infty} f(x) = +\\infty$. Images stratégiques : $f(-1) = \\frac{13}{6} \\approx 2,17$ (Maximum local) et $f(2) = -\\frac{7}{3} \\approx -2,33$ (Minimum local).',
            'Correction c) : Tangente. Formule : $y = f\'(0)(x - 0) + f(0)$. On calcule l\'image $f(0) = 1$ et le nombre dérivé $f\'(0) = -2$. L\'équation de la tangente est (T) : $y = -2x + 1$.',
            'Correction d) : Position relative. On forme la différence $d(x) = f(x) - y_{(T)} = (\\frac{1}{3}x^3 - \\frac{1}{2}x^2 - 2x + 1) - (-2x + 1) = \\frac{1}{3}x^3 - \\frac{1}{2}x^2$. On factorise par le carré : $d(x) = x^2(\\frac{1}{3}x - \\frac{1}{2}) = x^2 \\frac{2x-3}{6}$. Comme $x^2 \\ge 0$, le signe dépend de $2x-3$. Pour $x < 3/2$, $d(x) \\le 0 \\implies$ (C) est en dessous de (T). Pour $x > 3/2$, $d(x) \\ge 0 \\implies$ (C) est au-dessus de (T). Au point d\'abscisse 3/2, la courbe traverse sa tangente (point d\'inflexion).',
          ],
          reponse: 'y = -2x + 1',
          warning: 'Piège à éviter : Si tu rates ton calcul de discriminant ou de dérivée à la question a), c\'est l\'ensemble de ton tableau et de ta position qui s\'effondre. Reste concentré !',
          conseil: 'Garde en tête qu\'au point d\'intersection $x=3/2$, la courbe traverse doucement sa tangente.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-2',
          niveau: 'BAC',
          enonce: 'Sujet 2 : Fonction Composee avec Exponentielle\n[Durée recommandée : 25 min | Barème : 4 points]\n\nSoit la fonction f définie sur $\\mathbb{R}$ par $f(x) = (x + 1)e^{-x}$.\n\na) Déterminer la limite de f en $-\\infty$. (1 pt)\nb) Déterminer la limite de f en $+\\infty$ (on rappelle que $\\lim_{x \\to +\\infty} xe^{-x} = 0$). Interpréter graphiquement. (1 pt)\nc) Calculer $f\'(x)$ et montrer qu\'elle se ramène à $f\'(x) = -xe^{-x}$. (1 pt)\nd) Dresser le tableau de variations complet de f. (1 pt)',
          etapes: [
            'Correction a) : Limite en $-\\infty$. Analysons les facteurs : $\\lim_{x \\to -\\infty} (x+1) = -\\infty$ et $\\lim_{x \\to -\\infty} e^{-x} = +\\infty$. Par produit des bornes, $(-\\infty) \\times (+\\infty) = -\\infty$.',
            'Correction b) : Limite en $+\\infty$. On développe l\'expression : $f(x) = xe^{-x} + e^{-x}$. Par croissance comparée rappelée, $\\lim xe^{-x} = 0$ et $\\lim e^{-x} = 0$. Par somme, $\\lim_{x \\to +\\infty} f(x) = 0$. Interprétation : L\'axe des abscisses (droite $y = 0$) constitue une asymptote horizontale à la courbe en $+\\infty$.',
            'Correction c) : Calcul de la dérivée. C\'est un produit de type $u \\times v$ avec $u = x + 1 \\implies u\' = 1$ et $v = e^{-x} \\implies v\' = -e^{-x}$ (attention au signe de la composée !). On assemble : $f\'(x) = (1)(e^{-x}) + (x + 1)(-e^{-x}) = e^{-x} - (x + 1)e^{-x} = e^{-x}[1 - (x + 1)] = -xe^{-x}$. La formule est démontrée !',
            'Correction d) : Variations. L\'exponentielle $e^{-x}$ étant strictement positive, le signe de la dérivée est dicté par $-x$. Pour $x < 0$, $f\'(x) > 0$ (croissante). Pour $x > 0$, $f\'(x) < 0$ (décroissante). Le sommet est atteint en 0, de hauteur $f(0) = (0+1)e^0 = 1$.',
          ],
          reponse: '-xe^{-x}',
          warning: 'Piège à éviter : Écrire que la dérivée de $e^{-x}$ est $e^{-x}$ en oubliant le signe moins de la dérivation composée de l\'exposant. C\'est la source de 80% des contresens sur ce type d\'exercice.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-3',
          niveau: 'BAC',
          enonce: 'Sujet 3 : Étude d\'une Fonction Auxiliaire Logarithme\n[Durée recommandée : 20 min | Barème : 4,5 points]\n\nSoit la fonction g définie sur $]0 ; +\\infty[$ par $g(x) = x - 1 - \\ln(x)$.\n\na) Calculer les limites de g aux bornes de son domaine. (1,5 pt)\nb) Calculer $g\'(x)$ et étudier son signe sur son intervalle. (1 pt)\nc) Dresser le tableau de variations complet de g. (1 pt)\nd) En déduire que pour tout $x > 0$, on a la relation : $\\ln(x) \\le x - 1$. (1 pt)',
          etapes: [
            'Correction a) : Limites aux bornes. En $0^+$ : $\\lim (x - 1) = -1$ et $\\lim -\\ln(x) = -(-\\infty) = +\\infty$. Par somme, $\\lim_{x \\to 0^+} g(x) = +\\infty$. En $+\\infty$ : on a une forme indéterminée $\\infty - \\infty$. On factorise par le fort : $g(x) = x(1 - \\frac{1}{x} - \\frac{\\ln(x)}{x})$. D\'après les croissances comparées, $\\frac{\\ln(x)}{x} \\to 0$. La parenthèse tend vers 1, d\'où par produit : $\\lim_{x \\to +\\infty} g(x) = +\\infty$.',
            'Correction b) : Dérivée. On calcule directement : $g\'(x) = 1 - 0 - \\frac{1}{x} = \\frac{x-1}{x}$. Le bas x étant positif sur notre domaine, le signe est uniquement celui de $x-1$. Pour $x \\in ]0; 1[$, $g\'(x) < 0$ (décroissante). Pour $x \\in ]1; +\\infty[$, $g\'(x) > 0$ (croissante).',
            'Correction c) : Tableau de variations. On calcule l\'altitude du point le plus bas (le minimum) : $g(1) = 1 - 1 - \\ln(1) = 0$. La courbe descend de $+\\infty$ jusqu\'au plancher 0 en $x=1$, puis remonte vers $+\\infty$.',
            'Correction d) : Déduction. Puisque le minimum absolu de la fonction g sur son domaine est égal à 0, cela signifie que pour tout $x > 0$, $g(x) \\ge 0 \\implies x - 1 - \\ln(x) \\ge 0 \\implies \\ln(x) \\le x - 1$. La relation est validée !',
          ],
          reponse: '\\ln(x) \\le x - 1',
          conseil: 'Cette question classique d\'inégalités se résout toujours en observant le plancher (minimum) de ta fonction différence.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-4',
          niveau: 'BAC',
          enonce: 'Sujet 4 : Situation Complexe d\'Optimisation Agricole\n[Durée recommandée : 15 min | Barème : 3 points]\n\nUne coopérative gère une broyeuse de manioc pour extraire de l\'amidon. Son bénéfice journalier en milliers de FCFA pour x tonnes traitées ($x \\in [0 ; 5]$) est modélisé par l\'expression : $B(x) = -x^3 + 3x^2 + 9x - 5$.\n\na) Calculer $B\'(x)$. (1 pt)\nb) Résoudre l\'équation $B\'(x) = 0$ sur son intervalle d\'étude. (1 pt)\nc) Déterminer la quantité idéale de tonnes à traiter pour maximiser le profit et calculer ce gain maximal. (1 pt)',
          etapes: [
            'Correction a) : Dérivée. On applique les règles de puissances brique par brique : $B\'(x) = -3x^2 + 6x + 9$.',
            'Correction b) : Résolution. On pose $-3x^2 + 6x + 9 = 0$. Pour simplifier les calculs, on divise tous les coefficients par −3, ce qui donne le trinôme épuré : $x^2 - 2x - 3 = 0$. Le discriminant $\\Delta = 16 \\implies \\sqrt{\\Delta} = 4$. Les deux racines sont $x_1 = -1$ et $x_2 = 3$. Sur notre intervalle d\'étude $[0; 5]$, la seule solution retenue est $x = 3$.',
            'Correction c) : Profit optimal. Le coefficient de départ du trinôme étant négatif (−3), la dérivée est positive à l\'intérieur des racines et négative à l\'extérieur. Sur $[0; 5]$, $B\'(x) > 0$ avant 3 (on grimpe) et $B\'(x) < 0$ après 3 (on descend). Le maximum absolu est donc atteint pour $x = 3$ tonnes. On évalue la hauteur du gain : $B(3) = -(3)^3 + 3(3)^2 + 9(3) - 5 = -27 + 27 + 27 - 5 = 22$. Le bénéfice maximal s\'élève donc à 22 000 FCFA.',
          ],
          reponse: '3 tonnes pour 22000 FCFA',
          conseil: 'Dans un problème concret de Situation Complexe, élimine toujours les solutions qui n\'ont pas de sens physique (comme un tonnage négatif x = -1) et explique pourquoi sur ta copie.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-5',
          niveau: 'BAC',
          enonce: 'Sujet 5 : Variations d\'une Fonction Homographique\n[Durée recommandée : 20 min | Barème : 4 points]\n\nSoit la fonction f définie sur $\\mathbb{R} \\setminus \\{1\\}$ par $f(x) = \\frac{2x-3}{x-1}$. On note (C) sa courbe représentative.\n\na) Calculer les limites de f aux bornes de son domaine et en déduire les équations de ses asymptotes. (1,5 pt)\nb) Montrer que sa fonction dérivée est donnée par la relation : $f\'(x) = \\frac{1}{(x-1)^2}$. (1 pt)\nc) Dresser le tableau de variations complet de f. (0,5 pt)\nd) Déterminer les coordonnées précises du point d\'intersection de la courbe (C) avec l\'axe des abscisses. (1 pt)',
          etapes: [
            'Correction a) : Limites et asymptotes. Aux infinis, on retient le rapport des termes de plus haut degré : $\\lim_{x \\to \\pm\\infty} \\frac{2x}{x} = 2$. La droite d\'équation $y = 2$ est une asymptote horizontale. En $1^-$ : le haut tend vers $-1$ et le bas tend vers $0^-$, d\'où par quotient : $(-1)/(0^-) = +\\infty$. En $1^+$ : le haut tend vers $-1$ et le bas tend vers $0^+$, d\'où $(-1)/(0^+) = -\\infty$. La droite d\'équation $x = 1$ est une asymptote verticale.',
            'Correction b) : Dérivée. Règle du quotient avec $u = 2x-3 \\implies u\'=2$ et $v = x-1 \\implies v\'=1$. On applique : $f\'(x) = \\frac{2(x-1) - (2x-3)(1)}{(x-1)^2} = \\frac{2x - 2 - 2x + 3}{(x-1)^2} = \\frac{1}{(x-1)^2}$. La relation est validée !',
            'Correction c) : Variations. Le numérateur vaut 1 (positif) et le bas est un carré parfait strictement positif sur notre domaine. La dérivée $f\'(x)$ est donc strictement positive partout. La fonction f est strictement croissante sur $]-\\infty; 1[$ et strictement croissante sur $]1; +\\infty[$.',
            'Correction d) : Intersection. On cherche où $f(x) = 0 \\implies \\frac{2x-3}{x-1} = 0$. Un quotient est nul si et seulement si son numérateur s\'annule : $2x - 3 = 0 \\implies x = 3/2$. Le point de contact avec l\'axe horizontal est donc $A(3/2; 0)$.',
          ],
          reponse: 'A(3/2; 0)',
          warning: 'Piège à éviter : Ne commets jamais l\'erreur de dire que f est \"croissante sur $\\mathbb{R} \\setminus \\{1\\}$\" globalement. C\'sest faux ! Elle est croissante sur chaque intervalle séparément, car la valeur interdite brise la continuité. Marque bien ta double barre ‖ dans ton tableau !',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-6',
          niveau: 'BAC',
          enonce: 'Sujet 6 : Utilisation de l\'Expression Conjuguee (Racine)\n[Durée recommandée : 20 min | Barème : 4 points]\n\nSoit la fonction f définie sur $\\mathbb{R}$ par $f(x) = \\sqrt{x^2 + 4} - x$.\n\na) Justifier proprement que son domaine de définition est $\\mathbb{R}$ tout entier. (0,5 pt)\nb) Déterminer la limite de f en $-\\infty$. (1 pt)\nc) Déterminer la limite de f en $+\\infty$ en levant l\'indétermination par l\'expression conjuguée. (1,5 pt)\nd) Calculer $f\'(x)$ et prouver que pour tout réel x, on a la relation : $f\'(x) < 0$. (1 pt)',
          etapes: [
            'Correction a) : Domaine. L\'expression sous la racine doit être positive ou nulle. Or, pour tout réel x, $x^2 \\ge 0 \\implies x^2 + 4 \\ge 4 > 0$. L\'expression est toujours strictement positive, le domaine est donc $\\mathbb{R}$.',
            'Correction b) : Limite en $-\\infty$. Analysons les blocs : $\\lim_{x \\to -\\infty} \\sqrt{x^2+4} = +\\infty$ et $\\lim -x = -(-\\infty) = +\\infty$. Par somme directe des infinis, on obtient : $\\lim_{x \\to -\\infty} f(x) = +\\infty$.',
            'Correction c) : Limite en $+\\infty$. On est face à la forme indéterminée $\\infty - \\infty$. Multiplions par le conjugué en haut et en bas : $f(x) = \\frac{(\\sqrt{x^2+4}-x)(\\sqrt{x^2+4}+x)}{\\sqrt{x^2+4}+x} = \\frac{(x^2+4) - x^2}{\\sqrt{x^2+4}+x} = \\frac{4}{\\sqrt{x^2+4}+x}$. Quand $x \\to +\\infty$, le bas tend vers $+\\infty$, d\'où par quotient inversé : $\\lim_{x \\to +\\infty} f(x) = 0$.',
            'Correction d) : Dérivée et signe. On dérive la somme : $f\'(x) = \\frac{2x}{2\\sqrt{x^2+4}} - 1 = \\frac{x}{\\sqrt{x^2+4}} - 1 = \\frac{x - \\sqrt{x^2+4}}{\\sqrt{x^2+4}}$. Pour le signe du haut : on sait que $x^2 < x^2 + 4 \\implies \\sqrt{x^2} < \\sqrt{x^2+4} \\implies |x| < \\sqrt{x^2+4}$. Par conséquent, $x$ est toujours strictement inférieur à $\\sqrt{x^2+4}$, ce qui implique que $x - \\sqrt{x^2+4} < 0$. Le bas étant positif, la dérivée $f\'(x)$ est strictement négative sur $\\mathbb{R}$ (fonction décroissante).',
          ],
          reponse: '\\lim_{x \\to +\\infty} = 0, f\'(x) < 0',
          conseil: 'Face à une forme indéterminée de soustraction d\'infinis avec une racine carrée, l\'expression conjuguée est l\'outil le plus rapide et le plus efficace.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-7',
          niveau: 'BAC',
          enonce: 'Sujet 7 : Identification de Coefficients par Contraintes\n[Durée recommandée : 15 min | Barème : 2 points]\n\nSoit la fonction polynôme f d\'équation générale $f(x) = ax^2 + bx + 3$. On sait que sa courbe représentative (C) passe par le point de repère $A(1 ; 6)$ et qu\'elle admet en ce point précis une droite tangente horizontale.\n\na) Traduire ces deux informations géométriques du français vers deux équations mathématiques de contraintes. (1 pt)\nb) Résoudre le système pour en déduire les valeurs exactes des réels a et b. (1 pt)',
          etapes: [
            'Correction a) : Traduction des contraintes. \n1. \"La courbe passe par le point A(1;6)\" se traduit par l\'égalité des hauteurs : $f(1) = 6$.\n2. \"Admet en ce point une tangente horizontale\" signifie que le coefficient directeur (la pente) s\'aplanit en ce point, ce qui se traduit par l\'annulation du nombre dérivé : $f\'(1) = 0$.',
            'Correction b) : Résolution du système. Développons l\'équation 1 : $f(1) = a(1)^2 + b(1) + 3 = 6 \\implies a + b + 3 = 6 \\implies a + b = 3$. Dérivons la fonction : $f\'(x) = 2ax + b$. Développons l\'équation 2 : $f\'(1) = 2a(1) + b = 0 \\implies 2a + b = 0$. Nous avons le système linéaire classique : \n  - $b = -2a$ (d\'après la contrainte de la dérivée).\n  - On injecte dans la première : $a + (-2a) = 3 \\implies -a = 3 \\implies a = -3$.\n  - On en déduit b : $b = -2(-3) = 6$. La fonction épurée est donc $f(x) = -3x^2 + 6x + 3$.',
          ],
          reponse: 'a = -3, b = 6',
          conseil: 'C\'sest un exercice classique de début de problème d\'analyse au BAC. Apprends à traduire instantanément le français des énoncés en langage de fonctions.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-8',
          niveau: 'BAC',
          enonce: 'Sujet 8 : Asymptote Oblique et Parallélisme de Tangente\n[Durée recommandée : 20 min | Barème : 3,5 points]\n\nSoit la fonction f définie sur $]-1 ; +\\infty[$ par l\'expression $f(x) = \\frac{x^2+3}{x+1}$.\n\na) Montrer que f(x) peut s\'écrire sous la forme réduite $f(x) = ax + b + \\frac{c}{x+1}$, puis déterminer l\'équation de son asymptote oblique (D). (1,5 pt)\nb) Étudier la position relative de la courbe (C) par rapport à sa droite repère (D). (1 pt)\nc) Calculer $f\'(x)$ et déterminer s\'il existe des points où la tangente est parallèle à la droite (D). (1 pt)',
          etapes: [
            'Correction a) : Décomposition et Asymptote. Mettons l\'expression théorique au même dénominateur : $\\frac{(ax+b)(x+1)+c}{x+1} = \\frac{ax^2 + (a+b)x + (b+c)}{x+1}$. Par identification terme à terme avec le numérateur d\'origine $x^2 + 0x + 3$, on résout le système immédiat : $a = 1$, $a+b = 0 \\implies b = -1$, et $b+c = 3 \\implies -1+c = 3 \\implies c = 4$. On obtient : $f(x) = x - 1 + \\frac{4}{x+1}$. Quand $x \\to +\\infty$, le bloc résiduel $\\frac{4}{x+1} \\to 0$. La droite (D) d\'équation $y = x - 1$ est donc une asymptote oblique à la courbe.',
            'Correction b) : Position relative. On forme la fonction différence : $d(x) = f(x) - y_{(D)} = (x - 1 + \\frac{4}{x+1}) - (x - 1) = \\frac{4}{x+1}$. Sur notre domaine d\'étude $]-1; +\\infty[$, le terme $x+1 > 0$, donc la fraction est strictement positive ($d(x) > 0$). Conclusion : La courbe (C) se situe strictement AU-DESSUS de son asymptote oblique (D) sur tout son intervalle.',
            'Correction c) : Parallélisme de tangente. La pente de notre droite (D) d\'équation $y = x - 1$ vaut 1. On cherche donc les points d\'abscisses x qui satisfont l\'équation : $f\'(x) = 1$. Dérivons l\'expression décomposée de f : $f\'(x) = 1 - 0 - \\frac{4}{(x+1)^2}$. Posons l\'égalité : $1 - \\frac{4}{(x+1)^2} = 1 \\implies -\\frac{4}{(x+1)^2} = 0 \\implies \\frac{4}{(x+1)^2} = 0$. C\'est mathématiquement IMPOSSIBLE qu\'une fraction à numérateur constant non nul (4) soit égale à 0. Conclusion : Il n\'existe aucun point sur la courbe où la tangente est parallèle à (D).',
          ],
          reponse: 'Impossible, pas de point parallèle',
          warning: 'Piège à éviter : Ne panique pas si tu trouves un résultat \"impossible\". Ce n\'est pas une erreur de ta part, c\'est la bonne conclusion géométrique. Écris-le proprement pour empocher ton point.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-9',
          niveau: 'BAC',
          enonce: 'Sujet 9 : Modélisation et Optimisation d\'un Coût Économique\n[Durée recommandée : 15 min | Barème : 3 points]\n\nLe coût total de fabrication de x tonnes d\'engrais ($x \\in [1 ; 20]$) est modélisé en dizaines de milliers de FCFA par : $C(x) = 0,5x^2 + 2x + 18$. On définit le coût unitaire moyen par la relation : $C_m(x) = \\frac{C(x)}{x}$.\n\na) Exprimer le coût unitaire moyen $C_m(x)$ sous forme d\'une somme simplifiée en fonction de x. (1 pt)\nb) Calculer la fonction dérivée du coût moyen $C\'_m(x)$. (1 pt)\nc) Déterminer la production optimale en tonnes pour minimiser ce coût unitaire et calculer ce coût minimal. (1 pt)',
          etapes: [
            'Correction a) : Expression du coût moyen. On divise chaque composante du coût global par la variable x : $C_m(x) = \\frac{0,5x^2 + 2x + 18}{x} = \\frac{0,5x^2}{x} + \\frac{2x}{x} + \\frac{18}{x} = 0,5x + 2 + \\frac{18}{x}$. L\'expression est simplifiée.',
            'Correction b) : Dérivation. On dérive cette somme épurée, ce qui est beaucoup plus rapide que d\'appliquer la formule de quotient sur la forme brute : $C\'_m(x) = 0,5 + 0 - \\frac{18}{x^2} = \\frac{0,5x^2 - 18}{x^2}$.',
            'Correction c) : Minimisation du coût. On cherche le point critique où la dérivée s\'annule : $0,5x^2 - 18 = 0 \\implies 0,5x^2 = 18 \\implies x^2 = \\frac{18}{0,5} = 36$. La variable étant positive, la seule solution est $x = 6$ tonnes. Pour la validation du signe : si $x < 6$, $0,5x^2 < 18 \\implies$ dérivée négative (on descend). Si $x > 6$, la dérivée est positive (on monte). On atteint bien le fond du cratère (le minimum) en 6. Évaluons le coût moyen minimal : $C_m(6) = 0,5(6) + 2 + \\frac{18}{6} = 3 + 2 + 3 = 8$. Conclusion : Le coût unitaire moyen est minimal pour une production de 6 tonnes, et sa valeur s\'élève à 80 000 FCFA par tonne.',
          ],
          reponse: '6 tonnes pour un coût de 80000 FCFA',
          conseil: 'L\'astuce des majors qui fait gagner un temps précieux : scinde toujours ta fraction en plusieurs blocs simples avant de te lancer dans la dérivation d\'un coût moyen.',
        },
        {
          type: 'exercise',
          id: 'sujet-bac-10',
          niveau: 'BAC',
          enonce: 'Sujet 10 : Étude d\'une Fonction Trigonométrique Composée\n[Durée recommandée : 20 min | Barème : 4 points]\n\nSoit la fonction f définie sur l\'intervalle $I = [0 ; \\pi]$ par l\'expression : $f(x) = \\sin(2x) - 2\\sin(x)$.\n\na) Calculer $f\'(x)$ et montrer qu\'elle se factorise sous la forme : $f\'(x) = 2(2\\cos(x) + 1)(\\cos(x) - 1)$. On rappelle l\'identité trigonométrique : $\\cos(2x) = 2\\cos^2(x) - 1$. (1,5 pt)\nb) Étudier méthodiquement le signe de la fonction dérivée $f\'(x)$ sur l\'intervalle I. (1,5 pt)\nc) Dresser le tableau de variations complet de f. (1 pt)',
          etapes: [
            'Correction a) : Dérivation et factorisation. On dérive terme à terme en faisant attention à la composée du premier bloc : $(\\sin(2x))\' = 2\\cos(2x)$. On obtient : $f\'(x) = 2\\cos(2x) - 2\\cos(x)$. Utilisons le rappel de l\'énoncé pour substituer $\\cos(2x)$ : $f\'(x) = 2(2\\cos^2(x) - 1) - 2\\cos(x) = 4\\cos^2(x) - 2\\cos(x) - 2$. Effectuons le changement de variable des majors : posons $X = \\cos(x)$. Notre expression devient le trinôme du second degré : $4X^2 - 2X - 2$. Le discriminant de ce trinôme est $\\Delta = 36 \\implies \\sqrt{\\Delta} = 6$. Les racines sont $X_1 = 1$ and $X_2 = -1/2$. La forme factorisée est donc $4(X - 1)(X + 1/2) = 2(X - 1)(2X + 1)$. En revenant à la variable d\'origine, on retrouve exactement : $f\'(x) = 2(\\cos(x) - 1)(2\\cos(x) + 1)$. La factorisation est validée !',
            'Correction b) : Étude du signe sur $[0; \\pi]$. Analysons chaque facteur séparément : \n1. Le coefficient 2 est strictement positif.\n2. Le bloc $(\\cos(x) - 1)$ : sur $[0; \\pi]$, le cosinus est toujours inférieur ou égal à 1, donc $(\\cos(x) - 1) \\le 0$. Ce terme est constamment négatif ou nul.\n3. Le bloc $(2\\cos(x) + 1)$ : s\'annule quand $\\cos(x) = -1/2 \\implies x = 2\\pi/3$ sur notre intervalle. Pour $x \\in [0; 2\\pi/3[$, $\\cos(x) > -1/2 \\implies$ le bloc est positif (+). Pour $x \\in ]2\\pi/3; \\pi]$, $\\cos(x) < -1/2 \\implies$ le bloc est négatif (−).\nEffectuons le produit des signes : sur $[0; 2\\pi/3]$, nous avons $(+) \\times (-) \\times (+) = $ négatif ($f\'(x) \\le 0$). Sur $[2\\pi/3; \\pi]$, nous avons $(+) \\times (-) \\times (-) = $ positif ($f\'(x) \\ge 0$).',
            'Correction c) : Tableau de variations. Calculons les altitudes des bornes et du creux : $f(0) = \\sin(0) - 2\\sin(0) = 0$. $f(2\\pi/3) = \\sin(4\\pi/3) - 2\\sin(2\\pi/3) = -\\frac{\\sqrt{3}}{2} - 2\\frac{\\sqrt{3}}{2} = -\\frac{3\\sqrt{3}}{2} \\approx -2,60$. Et $f(\\pi) = \\sin(2\\pi) - 2\\sin(\\pi) = 0$. La courbe part de 0, descend jusqu\'au minimum absolu $-\\frac{3\\sqrt{3}}{2}$ en $2\\pi/3$, puis remonte jusqu\'à la hauteur 0 en $\\pi$.',
          ],
          reponse: 'Min en 2\\pi/3 de valeur -3\\sqrt{3}/2',
          warning: 'Piège à éviter : Les fonctions trigonométriques effrayent souvent les candidats, mais garde en tête qu\'il s\'agit simplement d\'algèbre classique déguisée. Le changement de variable par X balaye toute la complexité.',
        },
        {
          type: 'text',
          id: 'b10-transition',
          contenu: 'Le Marathon du BAC est bouclé, tu as combattu comme un caïman du Cacao. Pour finaliser ton entraînement, passons à la dernière section : le sac de frappe, où tu vas t\'exercer en autonomie complète sans filet.',
        },
      ],
    },
    {
      id: 's5',
      titre: '5.4 Exercices pour t\'Entraîner Seul (Le Sac de Frappe sans Filet)',
      blocs: [
        {
          type: 'text',
          id: 'b11-accroche',
          contenu: 'Ici, pas de filet de sécurité, pas de correction détaillée. Sors ta feuille, résous ces 10 défis flash et valide tes réponses avec mes résultats finaux.',
        },
        {
          type: 'text',
          id: 'b11',
          contenu: "Maintenant, pas de pitié, pas de filet de sécurité. Voici 10 petites questions directes pour t'entraîner. Les réponses finales sont données pour que tu te corriges, mais la démarche t'appartient de bout en bout.",
        },
        {
          type: 'exercise',
          id: 'sac-1',
          niveau: 'BASE',
          enonce: 'DÉFI 1 : Calcule la fonction dérivée de l\'expression suivante : $f(x) = x^3 - 5x^2 + \\frac{1}{x}$',
          etapes: ['Exécute ton calcul en autonomie complète et valide avec la réponse ci-dessous.'],
          reponse: '3x^2 - 10x - \\frac{1}{x^2}',
          conseil: 'Applique la formule standard de la puissance et de l\'inverse usuel de façon indépendante.',
        },
        {
          type: 'exercise',
          id: 'sac-2',
          niveau: 'BASE',
          enonce: 'DÉFI 2 : Calcule la fonction dérivée du quotient de l\'expression suivante : $g(x) = \\frac{x}{e^x}$',
          etapes: ['Exécute ton calcul en utilisant la règle u/v ou l\'exposant négatif, puis valide.'],
          reponse: '\\frac{1-x}{e^x}',
          conseil: 'Pense à factoriser et simplifier par l\'exponentielle après avoir appliqué ta formule.',
        },
        {
          type: 'exercise',
          id: 'sac-3',
          niveau: 'BASE',
          enonce: 'DÉFI 3 : Détermine l\'équation réduite de la droite tangente au point d\'abscisse $x_0 = 0$ pour la fonction $h(x) = \\ln(x + 1)$',
          etapes: ['Calcule l\'image, le nombre dérivé en 0, mets en place dans la formule et réduis.'],
          reponse: 'y = x',
          conseil: 'La tangente en 0 de $\\ln(x+1)$ est une droite linéaire de pente 1 très célèbre.',
        },
        {
          type: 'exercise',
          id: 'sac-4',
          niveau: 'MOYEN',
          enonce: 'DÉFI 4 : Calcule la fonction dérivée de la racine composée suivante : $f(x) = \\sqrt{3x^2 - x}$',
          etapes: ['Applique la formule $\\frac{u\'}{2\\sqrt{u}}$ de façon directe.'],
          reponse: '\\frac{6x-1}{2\\sqrt{3x^2-x}}',
          conseil: 'Garde bien l\'ensemble du bloc initial sous le radical du dénominateur multiplié par 2.',
        },
        {
          type: 'exercise',
          id: 'sac-5',
          niveau: 'MOYEN',
          enonce: 'DÉFI 5 : Trouve la valeur exacte de l\'abscisse critique x (qui annule la dérivée) pour la fonction de profit : $B(x) = -2x^2 + 80x - 10$',
          etapes: ['Calcule la dérivée, pose l\'équation $B\'(x) = 0$ et résous.'],
          reponse: '20',
          conseil: 'Cette valeur correspond géométriquement à l\'abscisse du sommet de ta cloche.',
        },
        {
          type: 'exercise',
          id: 'sac-6',
          niveau: 'MOYEN',
          enonce: 'DÉFI 6 : Détermine le signe général de la fonction dérivée pour l\'expression homographique : $f(x) = \\frac{x+2}{x-1}$',
          etapes: ['Calcule la dérivée u\'v-uv\' et observe attentivement le signe obtenu au numérateur.'],
          reponse: 'Toujours strictement négatif',
          conseil: 'Le numérateur simplifié donne -3, ce qui assure que la dérivée est négative sur tout son domaine.',
        },
        {
          type: 'exercise',
          id: 'sac-7',
          niveau: 'MOYEN',
          enonce: 'DÉFI 7 : Calcule la fonction dérivée de la puissance composée suivante : $k(x) = (2x - 5)^4$',
          etapes: ['Applique le modèle de la puissance déclinée : $n \\cdot u\' \\cdot u^{n-1}$.'],
          reponse: '8(2x - 5)^3',
          conseil: 'N\'oublie pas de sortir le coefficient 2 issu de la dérivée interne de la parenthèse.',
        },
        {
          type: 'exercise',
          id: 'sac-8',
          niveau: 'BAC',
          enonce: 'DÉFI 8 : Trouve l\'abscisse exacte x où la droite tangente à la courbe $f(x) = x^2 - 6x$ se retrouve parfaitement parallèle à l\'axe horizontal des abscisses.',
          etapes: ['Traduis la contrainte : pente égale à 0, résous donc l\'équation f\'(x) = 0.'],
          reponse: '3',
          conseil: 'La dérivée $2x - 6 = 0$ te donne directement la coordonnée du point bas de ta parabole.',
        },
        {
          type: 'exercise',
          id: 'sac-9',
          niveau: 'BAC',
          enonce: 'DÉFI 9 : Détermine la fonction dérivée de la composée exponentielle suivante : $g(x) = e^{x^2 - 3x}$',
          etapes: ['Applique le modèle de dérivation en chaîne : $u\' \\cdot e^u$.'],
          reponse: '(2x - 3)e^{x^2 - 3x}',
          conseil: 'L\'exposant d\'origine reste inchangé, seule sa dérivée vient se placer en facteur devant.',
        },
        {
          type: 'exercise',
          id: 'sac-10',
          niveau: 'BAC',
          enonce: 'DÉFI 10 : Soit la fonction d\'analyse $f(x) = x + 2 - \\frac{\\ln(x)}{x}$. Quelle est sa limite exacte lorsque x s\'éloigne vers $+\\infty$ ?',
          etapes: ['Analyse la limite terme à terme en appliquant les théorèmes de croissances comparées.'],
          reponse: '+\\infty',
          conseil: 'Le terme fractionnaire s\'efface et tend vers 0 à l\'infini, laissant le bloc linéaire dominer le comportement.',
        },
        {
          type: 'text',
          id: 'b12',
          contenu: "=== 🏁 DIALOGUE DE FIN DE CHAPITRE ===",
        },
        {
          type: 'dialogue',
          id: 'b13-dialogue-final',
          pf: "Vieux père, je me sens prêt ! J'ai commis quelques erreurs de calcul de signes au début du marathon, mais une fois que j'ai pris le rythme, le Process en 5 étapes glissait tout seul ! Les dérivées, finalement, c'est comme un jeu de Lego, tu assembles les bonnes pièces et ça marche. Ça ne me fait plus peur !",
          gf: "Voilà la mentalité que je voulais voir, champion(ne) ! Tu viens de franchir la montagne. La peur a laissé la place à la maîtrise de l\'outil. Souviens-toi de cette confiance le jour de ton examen au BAC. Maintenant, repose ton cerveau, mange un bon plat, et on se retrouve dans le Chapitre 6 pour mettre en place la STRATÉGIE ultime pour rafler tous les points de l\'épreuve sans te fatiguer. On est ensemble !",
        },
      ],
    },
  ],
  quiz: [],
};