// src/data/t1-limites/chap6.ts
// CHAPITRE 5 — EXERCICES TYPE BAC
// Tome 1 : Les Limites · Collection Les Clés Maths

import { Chapitre } from '../../types/course';

export const chapitre5: Chapitre = {
  id: 't1-chap6',
  titre: 'Exercices Type BAC',
  duree: 45,
  niveau: 'BAC',
  xpGain: 100,
  gratuit: false,
  objectifs: [
    'Maîtriser les exercices de niveau BASE sans hésitation',
    'Résoudre les exercices MOYEN avec les formes indéterminées',
    'Aborder les exercices BAC complets avec méthode',
    'Transformer tes connaissances en réflexes automatiques',
  ],
  sections: [
    {
      id: 's1',
      titre: 'Introduction — La salle d\'entraînement du Champion',
      blocs: [
        {
          type: 'text',
          id: 'b1',
          contenu: "\"BAC C 2019 au 'Cacao'. Épreuve de mathématiques. J'ouvre le sujet. Problème d'analyse (12 points) : Question 1a (2pts) : Calculer lim f(x) sachant que f(x) = (x³-8)/(x-2). Mon voisin a regardé ça et a écrit direct : « 0/0 donc pas de limite ERREU ». Il a perdu 2 points.\n\nMoi, j'ai appliqué le protocole : 1. Je remplace → 0/0 (forme indéterminée). 2. Je factorise → x³ - 8 = (x-2)(x²+2x+4). 3. Je simplifie → f(x) = x²+2x+4. 4. Je recalcule → (2)²+2(2)+4 = 12. Résultat : 12 ✅ (2 points gagné en 2 minutes).\n\nQuestion 1b (2pts) : En déduire que x = 2 n'est pas un point de discontinuité. Là, beaucoup ont bloqué. Moi j'ai compris : Si lim f(x) = 12 et f(2) = 12, alors il n'y a pas de trou ! Encore 2 points faciles. Sur 12 points du problème, j'en avais déjà 4 en 5 minutes.\n\nCe jour-là, j'ai compris : le BAC ne cherche PAS à te piéger. Il vérifie que tu APPLIQUES les méthodes du cours. Dans ce chapitre, on s'entraîne sur des exercices TYPE BAC pour que tu sois prêt le jour J.\"",
        },
        {
          type: 'text',
          id: 'b2',
          contenu: "On a vu la théorie, on a vu la méthode. Maintenant, on monte sur le ring. C'est ici que tu vas transformer tes connaissances en réflexes. J'ai classé les exercices par niveau de difficulté. Ne triche pas : essaie de les faire avant de regarder ma correction !",
        },
      ],
    },
    {
      id: 's2',
      titre: 'Niveau BASE — Substitution directe',
      blocs: [
        {
          type: 'exercise',
          id: 'ex_b1',
          niveau: 'BASE',
          enonce: 'Calculer lim(x→2) (x² - 1)',
          etapes: [
            'Test de substitution directe : x = 2',
            'f(2) = (2)² - 1 = 4 - 1 = 3',
            'Résultat direct — pas de forme indéterminée',
          ],
          reponse: '3',
          conseil: 'Toujours commencer par substituer. Si ça donne un nombre → C\'EST FINI !',
        },
        {
          type: 'exercise',
          id: 'ex_b2',
          niveau: 'BASE',
          enonce: 'Calculer lim(x→0) (eˣ + x)',
          etapes: [
            'Test : x = 0',
            'e⁰ + 0 = 1 + 0 = 1',
          ],
          reponse: '1',
        },
        {
          type: 'exercise',
          id: 'ex_b3',
          niveau: 'BASE',
          enonce: 'Calculer lim(x→3⁺) 2/(x-3)',
          etapes: [
            'x → 3⁺ signifie qu\'on s\'approche de 3 par la droite',
            'x - 3 → 0⁺ (petit positif)',
            '2/0⁺ = +∞',
          ],
          reponse: '+∞',
          conseil: 'Pour les limites avec asymptote, identifier le SIGNE du dénominateur est crucial !',
          piege: 'Ne pas oublier le signe : 2/0⁺ = +∞ mais 2/0⁻ = −∞',
        },
        {
          type: 'exercise',
          id: 'ex_b4',
          niveau: 'BASE',
          enonce: 'Calculer lim(x→+∞) (3 + 1/x)',
          etapes: [
            '1/x → 0 quand x → +∞',
            '3 + 0 = 3',
          ],
          reponse: '3',
          conseil: 'Règle : k/x → 0 quand x → +∞, pour tout nombre k fixe.',
        },
      ],
    },
    {
      id: 's3',
      titre: 'Niveau MOYEN — Formes indéterminées',
      blocs: [
        {
          type: 'exercise',
          id: 'ex_m1',
          niveau: 'MOYEN',
          enonce: 'Calculer lim(x→1) (x²-1)/(x-1)',
          etapes: [
            'Test : (1-1)/(1-1) = 0/0 → Forme indéterminée !',
            'Factoriser : x² - 1 = (x-1)(x+1) car a² - b² = (a-b)(a+b)',
            'Simplification : (x-1)(x+1)/(x-1) = x + 1',
            'Recalcul : lim(x→1) (x + 1) = 1 + 1 = 2',
          ],
          reponse: '2',
          conseil: 'Si ça s\'annule en 1, c\'est qu\'il y a obligatoirement (x - 1) caché en haut et en bas. Traque-le !',
        },
        {
          type: 'exercise',
          id: 'ex_m2',
          niveau: 'MOYEN',
          enonce: 'Calculer lim(x→+∞) (√(x+2) − √x)',
          etapes: [
            'Test : +∞ − ∞ → Forme indéterminée !',
            'Méthode : Expression conjuguée. Multiplier par (√(x+2) + √x)',
            'Numérateur : (x+2) - x = 2',
            'Dénominateur : √(x+2) + √x → tend vers +∞',
            'Résultat : 2/+∞ = 0',
          ],
          reponse: '0',
        },
        {
          type: 'exercise',
          id: 'ex_m3',
          niveau: 'MOYEN',
          enonce: 'Calculer lim(x→+∞) (3x³ + 2x)/(x³ - 1)',
          etapes: [
            'Test : +∞/+∞ → Forme indéterminée ∞/∞',
            'Factoriser par le Chef (x³) en haut et en bas',
            'x³(3 + 2/x²) / x³(1 - 1/x³)',
            'Simplifier les x³ : (3 + 2/x²)/(1 - 1/x³)',
            'À l\'infini : 2/x² → 0 et 1/x³ → 0',
            'Résultat : 3/1 = 3',
          ],
          reponse: '3',
          conseil: 'Degrés égaux → rapport des coefficients leaders. 3x³/x³ = 3. Calcul mental possible !',
        },
      ],
    },
    {
      id: 's4',
      titre: 'Niveau BAC — Exercices complets',
      blocs: [
        {
          type: 'exercise',
          id: 'ex_bac1',
          niveau: 'BAC',
          enonce: 'Soit f(x) = (x³-8)/(x-2). Calculer lim(x→2) f(x). En déduire si x = 2 est un point de discontinuité.',
          etapes: [
            'Étape 1 — Calculer la limite : Test x = 2 → (8-8)/(2-2) = 0/0 → F.I.',
            'Factoriser : x³ - 8 = (x-2)(x²+2x+4)',
            'Simplifier : f(x) = x²+2x+4 pour x ≠ 2',
            'Recalculer : lim(x→2) (x²+2x+4) = 4+4+4 = 12',
            'Étape 2 — Continuité : f(2) n\'existe pas (division par 0)',
            'Mais lim(x→2) f(x) = 12 ✓',
            'Si on définit f(2) = 12, alors f serait continue en 2.',
            'Conclusion : x = 2 est une discontinuité PROLONGEABLE.',
          ],
          reponse: 'lim(x→2) f(x) = 12. x = 2 est un point de discontinuité prolongeable.',
          conseil: 'Au BAC, "en déduire la continuité" c\'est comparer la limite et f(a). Si elles sont égales → continue. Si f(a) n\'existe pas → discontinuité prolongeable.',
          piege: 'Ne pas confondre "f(2) n\'existe pas" avec "la limite n\'existe pas". La limite peut exister même si f(2) n\'existe pas !',
        },
        {
          type: 'exercise',
          id: 'ex_bac2',
          niveau: 'BAC',
          enonce: 'Calculer lim(x→+∞) [x - √(x²+3x)]',
          etapes: [
            'Test : +∞ − ∞ → Forme indéterminée',
            'Expression conjuguée : multiplier par [x + √(x²+3x)]',
            'Numérateur : x² - (x²+3x) = -3x',
            'Dénominateur : x + √(x²+3x) ≈ x + x = 2x quand x → +∞',
            'Résultat : -3x / 2x = -3/2',
          ],
          reponse: '-3/2',
          conseil: 'Pour x - √(polynôme de degré 2), utilise TOUJOURS le conjugué. Et quand x → +∞, √(x²+ax) ≈ x.',
        },
      ],
    },
  ],
  quiz: [
    {
      type: 'quiz',
      id: 'q1',
      question: 'Tu obtiens 0/0 pour $\\lim_{x \\to 1} \\frac{x^2-1}{x-1}$. La bonne factorisation est :',
      options: [
        'x² - 1 = (x-1)²',
        'x² - 1 = (x-1)(x+1)',
        'x² - 1 = x(x-1)',
        'x² - 1 ne se factorise pas',
      ],
      bonneReponse: 1,
      explication: 'x² - 1 = x² - 1² = (x-1)(x+1) par l\'identité a² - b² = (a-b)(a+b). Résultat : lim(x+1) = 2.',
    },
    {
      type: 'quiz',
      id: 'q2',
      question: 'Que vaut $\\lim_{x \\to +\\infty} \\frac{5x^4 + 3}{2x^4 - 1}$ ?',
      options: [
        '+∞',
        '5/2',
        '0',
        '3',
      ],
      bonneReponse: 1,
      explication: 'Degrés égaux (4 = 4) → rapport des coefficients leaders. 5x⁴/2x⁴ = 5/2.',
    },
    {
      type: 'quiz',
      id: 'q3',
      question: 'Si $\\lim_{x \\to 3} f(x) = 7$ et $f(3) = 7$, alors f est :',
      options: [
        'Discontinue en 3',
        'Continue en 3',
        'Non définie en 3',
        'Indéterminée en 3',
      ],
      bonneReponse: 1,
      explication: 'Les 3 conditions de continuité sont vérifiées : f(3) existe (= 7), la limite existe (= 7), et elles sont égales. Donc f est CONTINUE en 3.',
    },
    {
      type: 'quiz',
      id: 'q4',
      question: 'Que vaut $\\lim_{x \\to 3^-} \\frac{2}{x-3}$ ?',
      options: [
        '+∞',
        '0',
        '−∞',
        'N\'existe pas',
      ],
      bonneReponse: 2,
      explication: 'x → 3⁻ signifie qu\'on approche de 3 par la GAUCHE (ex: 2,999). Donc x - 3 → 0⁻ (petit négatif). 2/0⁻ = −∞.',
    },
    {
      type: 'quiz',
      id: 'q5',
      question: 'Pour calculer $\\lim_{x \\to +\\infty} (x - \\sqrt{x^2+2x})$, la technique est :',
      options: [
        'Substitution directe',
        'Factorisation par x',
        'Expression conjuguée — multiplier par (x + √(x²+2x))',
        'Croissances comparées',
      ],
      bonneReponse: 2,
      explication: 'Forme ∞ − ∞ avec une racine carrée → Expression conjuguée. On multiplie par (x + √(x²+2x)). Numérateur : x² - (x²+2x) = -2x. Dénominateur ≈ 2x. Résultat : -2x/2x = -1.',
    },
  ],
};
